import { between, check, exactSet, field, type CloudCheck, type CloudLesson, type CloudPlan } from "./model";

const terraformSource = { label: "HashiCorp Terraform: Remote state", url: "https://developer.hashicorp.com/terraform/language/state/remote" };
const actionsSource = { label: "GitHub Actions: About workflows", url: "https://docs.github.com/en/actions/writing-workflows/about-workflows" };
const kubernetesSource = { label: "Kubernetes Deployments", url: "https://kubernetes.io/docs/concepts/workloads/controllers/deployment/" };
const sreSource = { label: "Google SRE Workbook: Alerting on SLOs", url: "https://sre.google/workbook/alerting-on-slos/" };
const architectureSource = { label: "AWS Well-Architected Framework", url: "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html" };
const nistSource = { label: "NIST SP 800-207: Zero Trust Architecture", url: "https://csrc.nist.gov/pubs/sp/800/207/final" };
const slsaSource = { label: "SLSA supply-chain specification", url: "https://slsa.dev/spec/v1.1/" };
const finopsSource = { label: "FinOps Framework", url: "https://www.finops.org/framework/" };

type LessonSeed = {
  id: number; title: string; minutes: number; objective: string; story: string;
  concepts: CloudLesson["concepts"]; example: string; exampleNote: string; mistake: string; mission: string;
  starter: CloudPlan; solution: CloudPlan; help: Record<string, string>; checks: CloudCheck[];
  source: CloudLesson["source"];
};

const lesson = (seed: LessonSeed): CloudLesson => ({
  ...seed,
  fields: Object.entries(seed.solution).map(([key, value]) => field(key, Array.isArray(value) ? "strings" : typeof value as "string" | "number" | "boolean", seed.help[key] ?? "Required scenario value.")),
  observations: (plan) => seed.checks.map((item) => item.name + ": " + (item.test(plan) ? "ready" : "needs repair") + "."),
});
const ordered = (value: unknown, expected: string[]) => Array.isArray(value) && value.length === expected.length && value.every((item, index) => item === expected[index]);
const semver = (value: unknown) => typeof value === "string" && /^\d+\.\d+\.\d+$/.test(value);
const digest = (value: unknown) => typeof value === "string" && /^sha256:[a-f0-9]{12,64}$/.test(value);

const INTERMEDIATE_CLOUD_LESSON_PARTS: CloudLesson[] = [
  lesson({
    id: 1, title: "Protect infrastructure state", minutes: 10,
    objective: "Choose a collaborative state design that prevents conflicting infrastructure changes.",
    story: "Two engineers changed the same network from different laptops. Byte needs one protected record of the deployed infrastructure.",
    concepts: [
      { title: "State connects plans to resources", body: "Infrastructure tools use state to map declared resources to real objects. Losing or editing that record can produce incorrect plans, so state is operational data rather than ordinary source code." },
      { title: "Remote storage enables teamwork", body: "A shared backend gives approved automation and engineers one current state. Locking stops concurrent writers, while encryption and versioning protect sensitive content and make accidental changes recoverable." },
      { title: "Access stays narrow", body: "State can contain resource identifiers and sensitive values. Keep it out of Git, limit read and write access, record changes, and use outputs or a dedicated configuration store when consumers need only a small value." },
    ],
    example: "team plan → acquire lock → read remote state → calculate change → write versioned state",
    exampleNote: "The lock surrounds every operation that can write state; it does not replace review of the proposed infrastructure change.",
    mistake: "Committing a state file to the repository because the configuration itself belongs in version control.",
    mission: "Configure a remote, encrypted, versioned backend with locking. The state file must not be stored in Git.",
    starter: { stateBackend: "local", locking: false, encryption: false, versioning: false, stateInGit: true },
    solution: { stateBackend: "remote", locking: true, encryption: true, versioning: true, stateInGit: false },
    help: { stateBackend: "Where the team stores infrastructure state.", locking: "Prevent simultaneous writers.", encryption: "Encrypt stored state.", versioning: "Retain recoverable state versions.", stateInGit: "Whether state is committed to source control." },
    checks: [
      check("One shared writer", "Use a remote backend and enable locking.", (p) => p.stateBackend === "remote" && p.locking === true),
      check("State is recoverable", "Enable encryption and versioning.", (p) => p.encryption === true && p.versioning === true),
      check("Sensitive state stays out of Git", "Set stateInGit to false.", (p) => p.stateInGit === false),
    ], source: terraformSource,
  }),
  lesson({
    id: 2, title: "Build reusable modules", minutes: 10,
    objective: "Reuse a versioned infrastructure module without hiding environment-specific decisions.",
    story: "Every team copied a slightly different network definition. Byte wants a reviewed building block with deliberate inputs.",
    concepts: [
      { title: "Modules encode a useful boundary", body: "A module should package a stable capability such as a service network, not every resource in an organization. Clear inputs and outputs let teams reuse it without knowing its internal wiring." },
      { title: "Pin the version", body: "A moving module reference can change future plans without an application commit. A semantic version makes upgrades visible, reviewable, and reversible instead of silently changing every environment." },
      { title: "Configuration is not a secret store", body: "Pass environment-specific settings as inputs and obtain credentials from a secret reference at runtime. Hardcoded account IDs, passwords, or production sizes make a module unsafe to reuse." },
    ],
    example: 'module "service_network" { source = "registry/network"; version = "3.2.1"; environment = "staging" }',
    exampleNote: "The example pins the building block and supplies context; a secret value would be referenced separately.",
    mistake: "Using the main branch of a module so every consumer receives unreviewed changes.",
    mission: "Use the registry/network module at a semantic version for staging. Pass secrets by reference and avoid hardcoded environment values.",
    starter: { moduleSource: "git/main", moduleVersion: "latest", environment: "production", secretInput: "plain-password", hardcodedValues: true },
    solution: { moduleSource: "registry/network", moduleVersion: "3.2.1", environment: "staging", secretInput: "secret-reference", hardcodedValues: false },
    help: { moduleSource: "Approved module location.", moduleVersion: "Pinned semantic version.", environment: "Target environment for this drill.", secretInput: "How credentials are supplied.", hardcodedValues: "Whether environment data is embedded in the module." },
    checks: [
      check("Reviewed module is pinned", "Use registry/network and a numeric semantic version.", (p) => p.moduleSource === "registry/network" && semver(p.moduleVersion)),
      check("Environment stays explicit", "Target staging and disable hardcoded values.", (p) => p.environment === "staging" && p.hardcodedValues === false),
      check("Secrets remain references", "Use secret-reference.", (p) => p.secretInput === "secret-reference"),
    ], source: terraformSource,
  }),
  lesson({
    id: 3, title: "Review a risky change plan", minutes: 11,
    objective: "Put review and recovery controls around an infrastructure plan before applying it.",
    story: "A network plan proposes replacing the Relay gateway. Byte pauses the run until the blast radius and recovery path are known.",
    concepts: [
      { title: "A plan is a decision artifact", body: "A preview shows additions, updates, replacements, and deletions before they happen. Reviewers should connect each proposed change to the request and question unexpected destruction." },
      { title: "Replacement can interrupt service", body: "A configuration edit that looks small may force a resource replacement. Identify dependencies, protect stateful resources, and schedule disruptive work within an owned change window." },
      { title: "Rollback must be executable", body: "A sentence saying roll back is not enough. Preserve the previous configuration or data, define a trigger, and make sure the team can run the recovery steps during the planned window." },
    ],
    example: "plan: 2 add, 1 update, 0 destroy → peer review → approval → apply → verify",
    exampleNote: "A zero-destroy plan still needs review because updates can change connectivity or permissions.",
    mistake: "Treating an automatically generated plan as approval to apply it.",
    mission: "Approve a reviewed plan with no destructive changes, a tested rollback path, and a 15–120 minute change window.",
    starter: { planReviewed: false, destructiveChanges: 2, approvalRequired: false, rollbackPlan: false, changeWindowMinutes: 5 },
    solution: { planReviewed: true, destructiveChanges: 0, approvalRequired: true, rollbackPlan: true, changeWindowMinutes: 45 },
    help: { planReviewed: "Whether a peer inspected the plan.", destructiveChanges: "Resources deleted or replaced.", approvalRequired: "Require an explicit apply approval.", rollbackPlan: "A runnable recovery path exists.", changeWindowMinutes: "Reserved verification and recovery time." },
    checks: [
      check("Plan receives human review", "Enable review and approval.", (p) => p.planReviewed === true && p.approvalRequired === true),
      check("Unexpected destruction is removed", "Set destructiveChanges to zero.", (p) => p.destructiveChanges === 0),
      check("Recovery fits the window", "Provide rollback and reserve 15–120 minutes.", (p) => p.rollbackPlan === true && between("changeWindowMinutes", 15, 120)(p)),
    ], source: terraformSource,
  }),
  lesson({
    id: 4, title: "Trust a container artifact", minutes: 11,
    objective: "Promote an immutable container artifact with evidence about its contents and origin.",
    story: "The tag relay-api:latest now points to an unknown build. Byte needs an artifact that can be identified and verified.",
    concepts: [
      { title: "A digest identifies bytes", body: "A mutable tag can point to a different image later, while a content digest identifies one exact artifact. Deploying by digest makes environments reproducible and incident evidence unambiguous." },
      { title: "Scanning finds known risk", body: "A vulnerability scan compares packages with known advisories. A release gate should block unresolved critical findings, while lower findings still need owners and documented risk decisions." },
      { title: "Provenance strengthens trust", body: "A signature connects an artifact to an approved build identity, and an SBOM lists its components. Together they support verification and faster response when a dependency becomes vulnerable." },
    ],
    example: "source commit → isolated build → scan + SBOM → sign digest → promote the same digest",
    exampleNote: "The simulation uses a shortened digest. Real image digests are longer and generated by the registry.",
    mistake: "Scanning one image, then deploying a rebuilt image with the same human-readable tag.",
    mission: "Pin a digest, pass the vulnerability gate with zero critical findings, attach an SBOM, and verify a signature.",
    starter: { imageDigest: "latest", vulnerabilityScan: false, criticalVulnerabilities: 4, signed: false, sbom: false },
    solution: { imageDigest: "sha256:41b27d90acfe", vulnerabilityScan: true, criticalVulnerabilities: 0, signed: true, sbom: true },
    help: { imageDigest: "Immutable content identifier.", vulnerabilityScan: "Artifact was scanned.", criticalVulnerabilities: "Unresolved critical findings.", signed: "Approved build identity signed the digest.", sbom: "A component inventory accompanies the artifact." },
    checks: [
      check("Artifact is immutable", "Use a sha256 digest with at least 12 hexadecimal characters.", (p) => digest(p.imageDigest)),
      check("Critical gate passes", "Run the scan and resolve critical findings.", (p) => p.vulnerabilityScan === true && p.criticalVulnerabilities === 0),
      check("Origin and contents are recorded", "Require both a signature and SBOM.", (p) => p.signed === true && p.sbom === true),
    ], source: actionsSource,
  }),
  lesson({
    id: 5, title: "Project: Repeatable staging", minutes: 16,
    objective: "Combine protected state, a pinned module, reviewed plans, and lifecycle safety.",
    story: "The Infrastructure Forge must create staging the same way twice without exposing secrets or deleting the database.",
    concepts: [
      { title: "Repeatability needs controlled inputs", body: "The same versioned configuration, module versions, and explicit inputs should produce an explainable plan. Environment differences belong in reviewed variables rather than copied resource files." },
      { title: "State and secrets need separate controls", body: "Remote state coordinates infrastructure ownership, while a secret manager supplies runtime credentials. Treating either as ordinary repository content expands access and complicates rotation." },
      { title: "Lifecycle rules protect critical data", body: "Deletion protection is a final barrier, not a substitute for review or backups. Apply it to stateful resources and require an intentional, separately reviewed process before removal." },
    ],
    example: "versioned module + staging inputs + protected remote state → reviewed plan → approved apply",
    exampleNote: "This project verifies the control chain. It does not execute Terraform or contact a provider.",
    mistake: "Adding deletion protection while still allowing an unreviewed automation identity to change every resource.",
    mission: "Design repeatable staging with remote locked state, a pinned module, secret references, reviewed approval, and database deletion protection.",
    starter: { stateBackend: "local", locking: false, moduleVersion: "main", environment: "staging", secretReference: false, planReviewed: false, approvalRequired: false, destroyProtection: false },
    solution: { stateBackend: "remote", locking: true, moduleVersion: "3.2.1", environment: "staging", secretReference: true, planReviewed: true, approvalRequired: true, destroyProtection: true },
    help: { stateBackend: "Collaborative state location.", locking: "Prevent concurrent writes.", moduleVersion: "Pinned module release.", environment: "Environment created by this project.", secretReference: "Credentials come from a secret reference.", planReviewed: "Peer review completed.", approvalRequired: "Apply requires approval.", destroyProtection: "Protect the stateful database." },
    checks: [
      check("Infrastructure input is repeatable", "Use staging with a pinned semantic module version.", (p) => p.environment === "staging" && semver(p.moduleVersion)),
      check("State supports a team", "Use remote state with locking.", (p) => p.stateBackend === "remote" && p.locking === true),
      check("Change is reviewed", "Enable plan review and approval.", (p) => p.planReviewed === true && p.approvalRequired === true),
      check("Data and credentials are protected", "Use a secret reference and deletion protection.", (p) => p.secretReference === true && p.destroyProtection === true),
    ], source: terraformSource,
  }),
  lesson({
    id: 6, title: "Design a delivery pipeline", minutes: 11,
    objective: "Order fast feedback and release gates in a CI/CD workflow.",
    story: "A commit reached production without tests because every pipeline job ran independently. Byte rebuilds the delivery sequence.",
    concepts: [
      { title: "Feedback moves from cheap to expensive", body: "Linting and focused tests should fail quickly before a container build consumes more time. Security checks inspect the built artifact before any deployment job can use it." },
      { title: "The pipeline is a trust boundary", body: "Workflow permissions, dependencies, and secrets can affect production. Pin reusable actions, grant each job minimal permissions, and protect the branch that defines the release process." },
      { title: "Deploy an observed artifact", body: "A deployment should use the artifact produced and checked by the same run. Rebuilding during deployment breaks the connection between test evidence and the released bytes." },
    ],
    example: "pull request: lint → test → build → scan | protected main: deploy checked artifact",
    exampleNote: "Production deployment is gated by branch protection; the sequence represents required dependencies between jobs.",
    mistake: "Running deploy at the same time as test and hoping a later failure will undo the release.",
    mission: "Order lint, test, build, scan, and deploy. Trigger validation on pull requests and permit deployment from protected main.",
    starter: { stages: ["build", "deploy", "test"], trigger: "manual", protectedBranch: false, deployFromMain: false },
    solution: { stages: ["lint", "test", "build", "scan", "deploy"], trigger: "pull-request", protectedBranch: true, deployFromMain: true },
    help: { stages: "Required jobs in dependency order.", trigger: "Event that starts validation.", protectedBranch: "The release workflow branch is protected.", deployFromMain: "Only the protected main path deploys." },
    checks: [
      check("Pipeline orders its evidence", "Use lint, test, build, scan, deploy in that order.", (p) => ordered(p.stages, ["lint", "test", "build", "scan", "deploy"])),
      check("Changes receive early feedback", "Run validation on pull-request.", (p) => p.trigger === "pull-request"),
      check("Release path is protected", "Protect the branch and deploy from main.", (p) => p.protectedBranch === true && p.deployFromMain === true),
    ], source: actionsSource,
  }),
  lesson({
    id: 7, title: "Promote one artifact", minutes: 10,
    objective: "Move the same verified artifact through staging and production.",
    story: "Production was rebuilt from source and no longer matched the image that passed staging. Byte follows the digest.",
    concepts: [
      { title: "Promotion preserves evidence", body: "Testing is strongest when staging and production run identical bytes. Promote an immutable digest and change only environment configuration that has its own review." },
      { title: "Environment gates answer different questions", body: "Development checks speed, staging checks integration, and production approval checks readiness and ownership. Rebuilding at each gate answers none of them reliably." },
      { title: "Traceability shortens incidents", body: "Record which commit, workflow run, signature, and digest reached each environment. During an incident the team can identify and roll back the exact release." },
    ],
    example: "sha256:41b27d90acfe → development → staging verification → production approval → production",
    exampleNote: "Only deployment metadata changes; the digest remains identical.",
    mistake: "Promoting the tag stable while allowing it to point to a new image between environments.",
    mission: "Use one digest in development, staging, and production, disable mutable tags, and require production approval.",
    starter: { developmentDigest: "sha256:aaaa", stagingDigest: "sha256:bbbb", productionDigest: "latest", mutableTag: true, productionApproval: false },
    solution: { developmentDigest: "sha256:41b27d90acfe", stagingDigest: "sha256:41b27d90acfe", productionDigest: "sha256:41b27d90acfe", mutableTag: false, productionApproval: true },
    help: { developmentDigest: "Artifact tested in development.", stagingDigest: "Artifact tested in staging.", productionDigest: "Artifact released to production.", mutableTag: "Whether the reference can move.", productionApproval: "Explicit release approval." },
    checks: [
      check("Every environment uses one artifact", "Set all three values to the same valid digest.", (p) => digest(p.developmentDigest) && p.developmentDigest === p.stagingDigest && p.stagingDigest === p.productionDigest),
      check("Reference cannot move", "Disable mutableTag.", (p) => p.mutableTag === false),
      check("Production has a gate", "Require productionApproval.", (p) => p.productionApproval === true),
    ], source: actionsSource,
  }),
  lesson({
    id: 8, title: "Give a workload safe resources", minutes: 12,
    objective: "Configure a Kubernetes workload with capacity boundaries and a readiness signal.",
    story: "One container consumed every node resource while another received traffic before it could answer. Byte adds scheduling and health contracts.",
    concepts: [
      { title: "Requests support scheduling", body: "A scheduler uses resource requests to place pods where expected demand fits. Missing requests make placement optimistic and can cause contention when several workloads become busy." },
      { title: "Limits bound consumption", body: "Limits constrain resource use, but tight CPU or memory limits can throttle or terminate healthy work. Start from measurements and keep each limit at or above its request." },
      { title: "Readiness protects users", body: "A readiness probe removes an unready pod from service traffic without necessarily restarting it. The endpoint should test dependencies required to serve a request and return quickly." },
    ],
    example: "3 replicas · CPU 250m request / 500m limit · memory 256Mi / 512Mi · GET /ready",
    exampleNote: "The numbers are a training workload profile. Real values should come from load tests and production measurements.",
    mistake: "Using a liveness probe as readiness and repeatedly restarting a pod while a dependency is temporarily unavailable.",
    mission: "Run three non-root replicas with valid CPU and memory request/limit pairs and a /ready endpoint.",
    starter: { replicas: 1, cpuRequestMillicores: 0, cpuLimitMillicores: 100, memoryRequestMiB: 0, memoryLimitMiB: 128, readinessPath: "/health", runAsNonRoot: false },
    solution: { replicas: 3, cpuRequestMillicores: 250, cpuLimitMillicores: 500, memoryRequestMiB: 256, memoryLimitMiB: 512, readinessPath: "/ready", runAsNonRoot: true },
    help: { replicas: "Available pod copies.", cpuRequestMillicores: "Reserved CPU.", cpuLimitMillicores: "CPU ceiling.", memoryRequestMiB: "Reserved memory.", memoryLimitMiB: "Memory ceiling.", readinessPath: "Traffic readiness endpoint.", runAsNonRoot: "Container user policy." },
    checks: [
      check("Service has redundant replicas", "Use three replicas.", (p) => p.replicas === 3),
      check("Resource contracts are valid", "Use positive requests with limits at least as large.", (p) => typeof p.cpuRequestMillicores === "number" && typeof p.cpuLimitMillicores === "number" && typeof p.memoryRequestMiB === "number" && typeof p.memoryLimitMiB === "number" && p.cpuRequestMillicores > 0 && p.cpuLimitMillicores >= p.cpuRequestMillicores && p.memoryRequestMiB > 0 && p.memoryLimitMiB >= p.memoryRequestMiB),
      check("Only ready, non-root pods receive traffic", "Use /ready and runAsNonRoot.", (p) => p.readinessPath === "/ready" && p.runAsNonRoot === true),
    ], source: kubernetesSource,
  }),
  lesson({
    id: 11, title: "Define service objectives", minutes: 11,
    objective: "Turn user-visible reliability into measurable indicators and a time-bound objective.",
    story: "The dashboard shows green CPU while users see errors. Byte replaces machine health with a service contract.",
    concepts: [
      { title: "An SLI measures user experience", body: "A service level indicator is a measured signal such as successful request proportion or latency. Choose events and thresholds that represent whether a user received a useful response." },
      { title: "An SLO sets a target and window", body: "A service level objective states the desired level over a period, such as 99.9% successful requests across 30 days. The time window makes the promise testable." },
      { title: "An error budget supports decisions", body: "The gap between perfect reliability and the objective is the error budget. Teams can use its remaining amount to balance release speed, risk reduction, and operational work." },
    ],
    example: "SLI: successful eligible requests / eligible requests · SLO: 99.9% over 30 days",
    exampleNote: "A separate latency SLI uses the 95th percentile and a 400 ms target in this drill.",
    mistake: "Defining availability from whether a virtual machine is running while requests still fail.",
    mission: "Define a user-facing 99.9% availability objective over 30 days and a p95 latency target at or below 500 ms.",
    starter: { availabilitySli: "cpu-healthy", targetPercent: 100, windowDays: 1, latencyPercentile: 50, latencyTargetMs: 2000, userFacing: false },
    solution: { availabilitySli: "successful-requests", targetPercent: 99.9, windowDays: 30, latencyPercentile: 95, latencyTargetMs: 400, userFacing: true },
    help: { availabilitySli: "Event ratio representing availability.", targetPercent: "Availability objective.", windowDays: "Evaluation period.", latencyPercentile: "Latency distribution percentile.", latencyTargetMs: "Allowed latency at that percentile.", userFacing: "Indicator reflects a user outcome." },
    checks: [
      check("Availability reflects requests", "Use successful-requests and mark it user-facing.", (p) => p.availabilitySli === "successful-requests" && p.userFacing === true),
      check("Objective has a useful target and window", "Use 99.9% across 30 days.", (p) => p.targetPercent === 99.9 && p.windowDays === 30),
      check("Tail latency is bounded", "Use p95 with a target from 100 to 500 ms.", (p) => p.latencyPercentile === 95 && between("latencyTargetMs", 100, 500)(p)),
    ], source: sreSource,
  }),
  lesson({
    id: 12, title: "Connect logs, metrics, and traces", minutes: 11,
    objective: "Build observability signals that can follow one request without recording sensitive data.",
    story: "An alert identifies an error spike, but no one can connect it to a deployment or request. Byte adds shared context.",
    concepts: [
      { title: "Signals answer different questions", body: "Metrics summarize rates and distributions, logs preserve discrete events, and traces show work across service boundaries. A useful investigation moves between them instead of collecting each in isolation." },
      { title: "Correlation creates a path", body: "A request or trace identifier connects an alert to relevant spans and structured log events. Include deployment and service metadata so investigators can compare failures with recent changes." },
      { title: "Telemetry has a data boundary", body: "Logs and traces can accidentally capture credentials, tokens, or personal information. Redact sensitive fields, restrict access, define retention, and budget for signal volume." },
    ],
    example: "error-rate alert → trace_id 7f2a → API span → structured database timeout event",
    exampleNote: "A correlation identifier supports navigation; it does not replace access control or redaction.",
    mistake: "Logging complete request headers to make debugging easier, including authorization tokens.",
    mission: "Enable structured logs, traces, correlation IDs, RED metrics, no sensitive data, and 7–30 days of retention.",
    starter: { structuredLogs: false, correlationId: false, metrics: ["cpu"], traces: false, sensitiveData: true, retentionDays: 365 },
    solution: { structuredLogs: true, correlationId: true, metrics: ["request-rate", "error-rate", "duration"], traces: true, sensitiveData: false, retentionDays: 30 },
    help: { structuredLogs: "Machine-queryable event fields.", correlationId: "Shared request context across signals.", metrics: "Required request signals.", traces: "Distributed request spans.", sensitiveData: "Credentials or personal data are recorded.", retentionDays: "Telemetry retention period." },
    checks: [
      check("Requests can be followed", "Enable structured logs, correlation IDs, and traces.", (p) => p.structuredLogs === true && p.correlationId === true && p.traces === true),
      check("RED signals are present", "Collect request-rate, error-rate, and duration.", (p) => exactSet(p.metrics, ["request-rate", "error-rate", "duration"])),
      check("Telemetry respects its boundary", "Exclude sensitive data and retain 7–30 days.", (p) => p.sensitiveData === false && between("retentionDays", 7, 30)(p)),
    ], source: sreSource,
  }),
  lesson({
    id: 13, title: "Alert on error-budget burn", minutes: 12,
    objective: "Page on sustained user impact before the service consumes its reliability budget.",
    story: "The team receives hundreds of CPU alerts but misses a fast request outage. Byte moves the page to the SLO.",
    concepts: [
      { title: "Symptoms are closer to users", body: "A page should usually represent meaningful service impact such as elevated failed requests. Resource saturation can help diagnosis, but a raw infrastructure threshold is often a poor reason to wake someone." },
      { title: "Burn rate adds urgency", body: "Burn rate compares current bad-event consumption with the rate allowed by the SLO. A high fast-window burn detects severe incidents; a lower sustained window catches slower budget loss." },
      { title: "Multiple windows reduce noise", body: "Requiring impact across a short and a longer window helps avoid paging on a single transient sample. Every page still needs an owner, a runbook, and enough context to begin response." },
    ],
    example: "page when fast burn ≥14× for 5 min and sustained burn ≥2× for 60 min",
    exampleNote: "The values are simplified for the Relay scenario; teams tune alerting from their objective and operational history.",
    mistake: "Paging on every elevated error sample without waiting long enough to distinguish an incident from noise.",
    mission: "Alert on SLO symptoms with a 10–20× fast burn over 5 minutes, a 2–6× slow burn over 60 minutes, and an on-call owner.",
    starter: { symptomBased: false, fastBurnRate: 1, fastWindowMinutes: 1, slowBurnRate: 1, slowWindowMinutes: 5, pagesOnCall: false },
    solution: { symptomBased: true, fastBurnRate: 14, fastWindowMinutes: 5, slowBurnRate: 2, slowWindowMinutes: 60, pagesOnCall: true },
    help: { symptomBased: "Alert measures user-impacting errors.", fastBurnRate: "Severe incident budget multiplier.", fastWindowMinutes: "Short confirmation window.", slowBurnRate: "Sustained budget multiplier.", slowWindowMinutes: "Long confirmation window.", pagesOnCall: "An accountable responder is notified." },
    checks: [
      check("Page represents user impact", "Make the alert symptom-based.", (p) => p.symptomBased === true),
      check("Fast burn catches severe incidents", "Use a 10–20× burn over exactly five minutes.", (p) => between("fastBurnRate", 10, 20)(p) && p.fastWindowMinutes === 5),
      check("Slow burn confirms sustained impact", "Use 2–6× over 60 minutes and page on-call.", (p) => between("slowBurnRate", 2, 6)(p) && p.slowWindowMinutes === 60 && p.pagesOnCall === true),
    ], source: sreSource,
  }),
  lesson({
    id: 14, title: "Prove backup recovery", minutes: 12,
    objective: "Design backups around business recovery targets and demonstrate a successful restore.",
    story: "The backup job reports success, but no one has restored it. Byte schedules a recovery drill before the next incident.",
    concepts: [
      { title: "RPO limits acceptable data loss", body: "The recovery point objective defines how far back restored data may be. Backup or replication frequency must meet that target under real failure conditions." },
      { title: "RTO limits acceptable downtime", body: "The recovery time objective includes detection, decision, restore, validation, and traffic recovery. A stored backup alone says nothing about how long these steps take." },
      { title: "A restore test completes the control", body: "Regular drills verify credentials, tooling, capacity, runbooks, and data integrity. Keep at least one isolated or immutable copy so the same failure cannot alter production and every backup." },
    ],
    example: "RPO 15 min · RTO 60 min · encrypted cross-region copy · restore drill every 30 days",
    exampleNote: "The targets belong to this fictional service. A real team agrees them with business owners.",
    mistake: "Reporting backup-job success as proof that the application can be restored.",
    mission: "Use encrypted backups in a separate region, an immutable copy, RPO 15 minutes, RTO 60 minutes, and a restore test within 30 days.",
    starter: { backupEncrypted: false, backupLocation: "same-zone", immutableCopy: false, rpoMinutes: 1440, rtoMinutes: 480, restoreTested: false, lastRestoreDays: 400 },
    solution: { backupEncrypted: true, backupLocation: "separate-region", immutableCopy: true, rpoMinutes: 15, rtoMinutes: 60, restoreTested: true, lastRestoreDays: 20 },
    help: { backupEncrypted: "Stored recovery data is encrypted.", backupLocation: "Failure boundary for the recovery copy.", immutableCopy: "At least one copy resists alteration.", rpoMinutes: "Maximum data-loss window.", rtoMinutes: "Maximum recovery duration.", restoreTested: "A complete restore was verified.", lastRestoreDays: "Days since the latest drill." },
    checks: [
      check("Recovery copy survives the primary failure", "Use encrypted separate-region storage and an immutable copy.", (p) => p.backupEncrypted === true && p.backupLocation === "separate-region" && p.immutableCopy === true),
      check("Targets meet the Relay contract", "Use RPO at most 15 and RTO at most 60 minutes.", (p) => typeof p.rpoMinutes === "number" && p.rpoMinutes > 0 && p.rpoMinutes <= 15 && typeof p.rtoMinutes === "number" && p.rtoMinutes > 0 && p.rtoMinutes <= 60),
      check("Recovery has recent evidence", "Complete a restore within the last 30 days.", (p) => p.restoreTested === true && between("lastRestoreDays", 0, 30)(p)),
    ], source: architectureSource,
  }),
  lesson({
    id: 15, title: "Project: Reliable delivery system", minutes: 24,
    objective: "Design a repeatable path from infrastructure plan to measurable, recoverable production service.",
    story: "The Relay is ready for production. Byte asks for one system that preserves evidence from infrastructure review through incident recovery.",
    concepts: [
      { title: "Production is a chain of contracts", body: "Protected state, reviewed plans, verified artifacts, workload health, and service objectives each answer a different risk. The system is reliable only when evidence survives across every handoff." },
      { title: "Release and reliability share feedback", body: "A deployment event should appear in telemetry, while SLO burn controls release decisions. When user impact rises, the team can stop promotion, identify the digest, and restore a known-good revision." },
      { title: "Recovery is part of normal delivery", body: "Backups, rollback revisions, and runbooks decay unless exercised. Schedule tests and record results alongside release evidence so recovery readiness is visible before an incident." },
    ],
    example: "reviewed IaC → verified digest → safe rollout → SLO signals → tested rollback and restore",
    exampleNote: "This world project combines independent drills. It does not provision infrastructure, run a cluster, or certify production readiness.",
    mistake: "Optimizing each tool separately while losing the identity of the change, artifact, or owner between stages.",
    mission: "Join IaC, CI/CD, Kubernetes, SLO alerting, and recovery into one reviewed, traceable delivery plan.",
    starter: { remoteState: false, stateLocking: false, planReviewed: false, stages: ["build", "deploy"], sameDigest: false, signedArtifact: false, replicas: 1, readinessPath: "/live", maxUnavailable: 2, availabilitySlo: 100, burnAlert: false, correlationId: false, rpoMinutes: 1440, rtoMinutes: 480, restoreTested: false },
    solution: { remoteState: true, stateLocking: true, planReviewed: true, stages: ["lint", "test", "build", "scan", "deploy"], sameDigest: true, signedArtifact: true, replicas: 3, readinessPath: "/ready", maxUnavailable: 0, availabilitySlo: 99.9, burnAlert: true, correlationId: true, rpoMinutes: 15, rtoMinutes: 60, restoreTested: true },
    help: { remoteState: "Shared protected infrastructure state.", stateLocking: "One infrastructure writer.", planReviewed: "Proposed change received peer review.", stages: "Required release evidence order.", sameDigest: "Promote one artifact.", signedArtifact: "Build identity is verified.", replicas: "Production pod copies.", readinessPath: "Traffic readiness endpoint.", maxUnavailable: "Availability budget during rollout.", availabilitySlo: "Thirty-day request objective.", burnAlert: "Alert consumes SLO budget.", correlationId: "Join telemetry for one request.", rpoMinutes: "Data-loss target.", rtoMinutes: "Recovery-time target.", restoreTested: "Recovery drill completed." },
    checks: [
      check("Infrastructure change is coordinated", "Use remote locked state and plan review.", (p) => p.remoteState === true && p.stateLocking === true && p.planReviewed === true),
      check("Pipeline establishes artifact trust", "Use the ordered five stages, one digest, and a signature.", (p) => ordered(p.stages, ["lint", "test", "build", "scan", "deploy"]) && p.sameDigest === true && p.signedArtifact === true),
      check("Rollout preserves service", "Use three replicas, /ready, and zero unavailable.", (p) => p.replicas === 3 && p.readinessPath === "/ready" && p.maxUnavailable === 0),
      check("User impact drives response", "Use a 99.9 SLO, burn alert, and correlation ID.", (p) => p.availabilitySlo === 99.9 && p.burnAlert === true && p.correlationId === true),
      check("Data recovery meets its target", "Use RPO ≤15, RTO ≤60, and a tested restore.", (p) => typeof p.rpoMinutes === "number" && p.rpoMinutes > 0 && p.rpoMinutes <= 15 && typeof p.rtoMinutes === "number" && p.rtoMinutes > 0 && p.rtoMinutes <= 60 && p.restoreTested === true),
    ], source: sreSource,
  }),
];

export const EXPERT_CLOUD_LESSONS: CloudLesson[] = [
  lesson({
    id: 1, title: "Design account boundaries", minutes: 12,
    objective: "Separate organizational duties and workloads into governed cloud accounts.",
    story: "Every Relay workload shares one administrator account. Byte needs boundaries that contain mistakes and preserve independent evidence.",
    concepts: [
      { title: "Accounts are isolation boundaries", body: "Separate accounts can constrain credentials, quotas, billing, and the effect of a compromised workload. Production, nonproduction, security, and shared services have different trust and change needs." },
      { title: "Central identity replaces local sprawl", body: "Federated workforce access gives people short sessions and one lifecycle. Emergency access remains tightly controlled, monitored, and tested without turning the root identity into a daily administrator." },
      { title: "Security evidence needs independence", body: "An isolated log archive and security account reduce the chance that a workload administrator can alter its own audit trail. Organization policies then set boundaries that local administrators cannot bypass." },
    ],
    example: "organization → security + log archive + shared services + production + nonproduction",
    exampleNote: "The labels are functional boundaries. A real organization may use more accounts based on teams, data classes, or regulatory scope.",
    mistake: "Creating many accounts while using one permanent administrator credential across all of them.",
    mission: "Separate security, log archive, shared services, production, and nonproduction. Use central identity, protect root access, and isolate production.",
    starter: { accounts: ["everything"], centralIdentity: false, rootUserLocked: false, productionSeparated: false, securityEvidenceIndependent: false },
    solution: { accounts: ["security", "log-archive", "shared-services", "production", "nonproduction"], centralIdentity: true, rootUserLocked: true, productionSeparated: true, securityEvidenceIndependent: true },
    help: { accounts: "Functional account boundaries.", centralIdentity: "Federated workforce access.", rootUserLocked: "Root credentials are protected for emergencies.", productionSeparated: "Production has a distinct account boundary.", securityEvidenceIndependent: "Workloads cannot administer their audit archive." },
    checks: [
      check("Core duties have account boundaries", "Use all five functional accounts exactly once.", (p) => exactSet(p.accounts, ["security", "log-archive", "shared-services", "production", "nonproduction"])),
      check("Human access is centrally governed", "Enable central identity and protect root access.", (p) => p.centralIdentity === true && p.rootUserLocked === true),
      check("Production and evidence are isolated", "Separate production and keep security evidence independent.", (p) => p.productionSeparated === true && p.securityEvidenceIndependent === true),
    ], source: architectureSource,
  }),
  lesson({
    id: 2, title: "Build a hub-and-spoke network", minutes: 13,
    objective: "Connect workload networks through shared inspection without flattening their trust boundaries.",
    story: "Direct peering has become a mesh of hidden routes. Byte introduces a governed transit path between Relay networks.",
    concepts: [
      { title: "Transit centralizes connectivity", body: "A hub can provide controlled routing, inspection, and shared egress for many spoke networks. It reduces pairwise connections while each workload retains a separate address and policy boundary." },
      { title: "Routes express intended trust", body: "A route table should permit only required paths between environments and services. Sending traffic through the hub is useful only when inspection and return routes are correct." },
      { title: "Address plans prevent future collisions", body: "Overlapping network ranges make routing and acquisitions painful. Allocate nonoverlapping ranges centrally, reserve growth space, and record ownership before connecting a new spoke." },
    ],
    example: "production spoke ↔ inspection transit hub ↔ shared-services spoke",
    exampleNote: "Nonproduction remains a separate spoke and cannot reach production through an uninspected shortcut.",
    mistake: "Adding a transit hub but leaving direct peerings that bypass its inspection policy.",
    mission: "Use a transit hub, route east-west traffic through inspection, prevent overlapping ranges, and keep production separate from nonproduction.",
    starter: { transitHub: false, spokeDefaultRoute: "direct-internet", eastWestInspection: false, overlappingCidrs: true, productionNonproductionSeparated: false },
    solution: { transitHub: true, spokeDefaultRoute: "inspection", eastWestInspection: true, overlappingCidrs: false, productionNonproductionSeparated: true },
    help: { transitHub: "Central network transit exists.", spokeDefaultRoute: "Next hop for governed spoke traffic.", eastWestInspection: "Traffic between workloads is inspected.", overlappingCidrs: "Network ranges collide.", productionNonproductionSeparated: "Environment route boundaries remain distinct." },
    checks: [
      check("Spokes use governed transit", "Enable the hub and use inspection as the default governed route.", (p) => p.transitHub === true && p.spokeDefaultRoute === "inspection"),
      check("East-west paths are visible", "Enable eastWestInspection.", (p) => p.eastWestInspection === true),
      check("Network boundaries can scale", "Remove CIDR overlap and separate production from nonproduction.", (p) => p.overlappingCidrs === false && p.productionNonproductionSeparated === true),
    ], source: architectureSource,
  }),
  lesson({
    id: 3, title: "Keep service traffic private", minutes: 12,
    objective: "Reach a managed service through a private endpoint with a narrow data boundary.",
    story: "Relay workloads use public service endpoints even though every request begins inside a private network. Byte closes the route.",
    concepts: [
      { title: "Private endpoints remove a public hop", body: "A service endpoint can place managed-service access on private provider networking. Applications still need identity authorization; network location alone does not grant access." },
      { title: "DNS controls which path clients choose", body: "Private DNS should resolve the normal service name to the endpoint from approved networks. Test resolution and routing because an endpoint that clients never select provides no protection." },
      { title: "Endpoint policy limits data movement", body: "A narrow endpoint policy can restrict which resources or actions traverse the path. Combined with identity controls, it reduces unintended cross-account access and data exfiltration." },
    ],
    example: "private workload → private DNS → service endpoint → approved artifact bucket",
    exampleNote: "The endpoint policy and the workload identity must both allow the request.",
    mistake: "Creating a private endpoint while leaving clients configured with a public hostname and unrestricted egress.",
    mission: "Use private DNS and a private service endpoint, remove public internet routing, apply least privilege, and enable an exfiltration guard.",
    starter: { serviceEndpoint: false, publicInternetRoute: true, privateDns: false, endpointPolicy: "allow-all", exfiltrationGuard: false },
    solution: { serviceEndpoint: true, publicInternetRoute: false, privateDns: true, endpointPolicy: "least-privilege", exfiltrationGuard: true },
    help: { serviceEndpoint: "Private managed-service access path.", publicInternetRoute: "Traffic uses a public internet route.", privateDns: "Clients resolve the private endpoint.", endpointPolicy: "Resources/actions permitted through the endpoint.", exfiltrationGuard: "Unexpected data destinations are denied." },
    checks: [
      check("Client selects a private path", "Enable the service endpoint and private DNS.", (p) => p.serviceEndpoint === true && p.privateDns === true),
      check("Public route is absent", "Set publicInternetRoute to false.", (p) => p.publicInternetRoute === false),
      check("Data boundary is narrow", "Use least-privilege and an exfiltration guard.", (p) => p.endpointPolicy === "least-privilege" && p.exfiltrationGuard === true),
    ], source: nistSource,
  }),
  lesson({
    id: 4, title: "Enforce policy as code", minutes: 12,
    objective: "Prevent unsafe infrastructure properties before and during deployment.",
    story: "A review missed a public data store. Byte turns critical architecture rules into repeatable policy checks.",
    concepts: [
      { title: "Guardrails define the safe envelope", body: "Preventive policy can deny classes of unsafe changes such as public storage or missing encryption. Teams retain choices inside that envelope rather than waiting for a manual reviewer to find every violation." },
      { title: "Test before enforcing", body: "Evaluate a new policy against existing resources and plans in audit mode. Review false positives, repair known exceptions, then move to deny with an owner and rollout record." },
      { title: "Exceptions are explicit debt", body: "A legitimate exception should name an owner, scope, reason, expiry, and compensating control. An undocumented bypass becomes permanent behavior and weakens the guardrail." },
    ],
    example: "plan → policy test → deny public storage / unencrypted data / unapproved regions → approved exception workflow",
    exampleNote: "Audit mode reveals impact before the same rules become deployment blockers.",
    mistake: "Adding an unrestricted administrator bypass whenever a policy blocks a delivery.",
    mission: "Enable policy as code, deny public or unencrypted storage, restrict regions, test in audit mode, and require expiring exceptions.",
    starter: { policyAsCode: false, denyPublicStorage: false, denyUnencryptedStorage: false, allowedRegions: ["any"], auditBeforeDeny: false, expiringExceptions: false },
    solution: { policyAsCode: true, denyPublicStorage: true, denyUnencryptedStorage: true, allowedRegions: ["eu-west-1", "eu-central-1"], auditBeforeDeny: true, expiringExceptions: true },
    help: { policyAsCode: "Automated infrastructure rules.", denyPublicStorage: "Prevent anonymous data access.", denyUnencryptedStorage: "Require encryption.", allowedRegions: "Approved deployment locations.", auditBeforeDeny: "Observe impact before enforcement.", expiringExceptions: "Bypasses have owners and expiry." },
    checks: [
      check("Critical data rules are preventive", "Enable policy and deny public and unencrypted storage.", (p) => p.policyAsCode === true && p.denyPublicStorage === true && p.denyUnencryptedStorage === true),
      check("Location is governed", "Allow only eu-west-1 and eu-central-1.", (p) => exactSet(p.allowedRegions, ["eu-west-1", "eu-central-1"])),
      check("Rollout and exceptions are controlled", "Audit before deny and require expiring exceptions.", (p) => p.auditBeforeDeny === true && p.expiringExceptions === true),
    ], source: architectureSource,
  }),
  lesson({
    id: 5, title: "Project: Governed landing zone", minutes: 18,
    objective: "Combine account, network, evidence, and policy boundaries into a scalable cloud foundation.",
    story: "The Platform Nexus must onboard production without giving its team control over organizational evidence or guardrails.",
    concepts: [
      { title: "A landing zone is an operating system", body: "A useful foundation combines identity, accounts, logging, networking, and policies with an onboarding workflow. Creating accounts without these controls only distributes inconsistency." },
      { title: "Shared services need clear ownership", body: "Transit, DNS, artifact repositories, and identity can be centralized, but application teams need documented interfaces and escalation paths. Platform ownership does not erase workload responsibility." },
      { title: "Evidence verifies the foundation", body: "Continuously check that logs arrive, guardrails deny unsafe plans, routes follow inspection, and private endpoints resolve. A diagram without these assertions cannot prove the landing zone operates as intended." },
    ],
    example: "account vending → identity + logs + network attachment + policies → conformance checks",
    exampleNote: "The project models onboarding controls; it does not create accounts or networks.",
    mistake: "Calling the foundation complete after account creation while logging and policy attachment remain manual tickets.",
    mission: "Onboard an isolated production account with central identity, independent immutable logs, inspected transit, private services, and preventive guardrails.",
    starter: { productionAccount: false, centralIdentity: false, independentLogs: false, immutableLogs: false, inspectedTransit: false, privateServiceAccess: false, policyGuardrails: false, conformanceChecks: false },
    solution: { productionAccount: true, centralIdentity: true, independentLogs: true, immutableLogs: true, inspectedTransit: true, privateServiceAccess: true, policyGuardrails: true, conformanceChecks: true },
    help: { productionAccount: "Production has an isolated account.", centralIdentity: "Workforce access is federated.", independentLogs: "Audit evidence is administered elsewhere.", immutableLogs: "Archive resists alteration.", inspectedTransit: "Network paths cross shared inspection.", privateServiceAccess: "Managed services use private endpoints.", policyGuardrails: "Critical rules are enforced.", conformanceChecks: "Foundation controls are continuously verified." },
    checks: [
      check("Production has an identity boundary", "Use an isolated account and central identity.", (p) => p.productionAccount === true && p.centralIdentity === true),
      check("Audit evidence survives workload compromise", "Use independent immutable logs.", (p) => p.independentLogs === true && p.immutableLogs === true),
      check("Network paths are governed", "Use inspected transit and private service access.", (p) => p.inspectedTransit === true && p.privateServiceAccess === true),
      check("Foundation is continuously enforced", "Enable policy guardrails and conformance checks.", (p) => p.policyGuardrails === true && p.conformanceChecks === true),
    ], source: architectureSource,
  }),
  lesson({
    id: 6, title: "Federate workload identity", minutes: 12,
    objective: "Let an approved pipeline obtain a short-lived deployment identity without stored cloud keys.",
    story: "A deployment key has lived in repository secrets for two years. Byte replaces it with a verified workload identity.",
    concepts: [
      { title: "Federation verifies an external identity", body: "A cloud trust policy can validate a signed token from an approved workload platform. The pipeline exchanges that token for a short session rather than retrieving a permanent access key." },
      { title: "Claims narrow the trust", body: "Issuer, audience, repository, branch, environment, and workflow claims establish who may assume the role. Trusting every token from a provider is much broader than trusting one protected release job." },
      { title: "Sessions limit exposure", body: "Short duration and least-privilege permissions reduce the value of a stolen token. Record the assumed identity and deployment context so audit events point back to the exact workflow." },
    ],
    example: "protected release job → OIDC token with repo/environment claims → 15-minute deployment role",
    exampleNote: "No persistent cloud credential is stored in the repository or workflow platform.",
    mistake: "Using federation but accepting tokens from any repository and branch in the organization.",
    mission: "Use OIDC federation constrained to the release repository, production environment, and audience. Issue a session no longer than 30 minutes and remove long-lived keys.",
    starter: { oidcFederation: false, repositoryBound: false, environmentBound: false, audienceBound: false, sessionMinutes: 720, longLivedKeys: true },
    solution: { oidcFederation: true, repositoryBound: true, environmentBound: true, audienceBound: true, sessionMinutes: 15, longLivedKeys: false },
    help: { oidcFederation: "Exchange a verified workload token.", repositoryBound: "Trust is limited to the release repository.", environmentBound: "Production approval context is required.", audienceBound: "Token targets this cloud trust.", sessionMinutes: "Maximum assumed-role session.", longLivedKeys: "Persistent cloud credentials exist." },
    checks: [
      check("Pipeline uses federation", "Enable OIDC and remove long-lived keys.", (p) => p.oidcFederation === true && p.longLivedKeys === false),
      check("Trust checks workload context", "Bind repository, environment, and audience.", (p) => p.repositoryBound === true && p.environmentBound === true && p.audienceBound === true),
      check("Session expires quickly", "Use a whole session from 5 to 30 minutes.", (p) => between("sessionMinutes", 5, 30)(p)),
    ], source: nistSource,
  }),
  lesson({
    id: 7, title: "Govern encryption keys", minutes: 12,
    objective: "Separate key administration from data use and preserve a recoverable deletion process.",
    story: "The same application role can decrypt data, change the key policy, and delete the key. Byte separates those powers.",
    concepts: [
      { title: "Key use and administration differ", body: "Applications need narrowly scoped encrypt or decrypt permissions, while a smaller administrative group manages policy and lifecycle. Separation reduces the effect of one compromised role." },
      { title: "Rotation changes future protection", body: "Regular rotation creates new key material for future operations without automatically re-encrypting every stored object. Retain the material needed to decrypt existing ciphertext." },
      { title: "Deletion should be deliberate", body: "Key deletion can make data unrecoverable. Use a waiting period, independent approval, inventory of dependent data, and an audit trail before destructive lifecycle changes." },
    ],
    example: "application: encrypt/decrypt · key admins: policy/rotation · security approver: scheduled deletion",
    exampleNote: "The provider-managed key remains non-exportable and every administrative action is audited.",
    mistake: "Rotating a key and immediately deleting the old material while data still depends on it.",
    mission: "Use a managed non-exportable key, rotate within 90 days, separate administrators, audit use, and schedule deletion for at least 14 days.",
    starter: { managedKey: false, plaintextExport: true, rotationDays: 0, separateKeyAdmins: false, auditKeyUse: false, deletionWaitingDays: 0 },
    solution: { managedKey: true, plaintextExport: false, rotationDays: 90, separateKeyAdmins: true, auditKeyUse: true, deletionWaitingDays: 30 },
    help: { managedKey: "Key lifecycle is provider managed.", plaintextExport: "Raw key material can leave the service.", rotationDays: "Maximum new-material interval.", separateKeyAdmins: "Data users cannot administer the key.", auditKeyUse: "Key operations produce evidence.", deletionWaitingDays: "Recovery period before deletion." },
    checks: [
      check("Key material stays protected", "Use a managed key and disable plaintext export.", (p) => p.managedKey === true && p.plaintextExport === false),
      check("Lifecycle is maintained", "Rotate every 30–90 days and wait at least 14 days before deletion.", (p) => between("rotationDays", 30, 90)(p) && between("deletionWaitingDays", 14, 90)(p)),
      check("Power and evidence are separated", "Use separate key admins and audit key use.", (p) => p.separateKeyAdmins === true && p.auditKeyUse === true),
    ], source: architectureSource,
  }),
  lesson({
    id: 8, title: "Preserve detection evidence", minutes: 12,
    objective: "Collect organization-wide audit events into an independently controlled detection pipeline.",
    story: "A compromised workload deleted its local logs before the incident team arrived. Byte moves the evidence boundary.",
    concepts: [
      { title: "Collection must cover the organization", body: "Identity, control-plane, data-access, network, and security-service events need deliberate coverage. Gaps should be known because a local default rarely records every important action." },
      { title: "Archive and detection serve different speeds", body: "A durable immutable archive supports investigation and compliance, while a streaming path evaluates high-value events quickly. One store does not automatically satisfy both purposes." },
      { title: "A detection needs an owner", body: "Every alert rule should identify severity, accountable responder, context, and a runbook. Clock synchronization and consistent identities make events from different systems comparable." },
    ],
    example: "organization trail → immutable security archive + real-time detections → security on-call",
    exampleNote: "Workload administrators can view relevant events but cannot alter the independent archive.",
    mistake: "Collecting audit logs in the compromised workload account under the same administrator role.",
    mission: "Enable organization-wide events, immutable independent retention for at least 365 days, real-time detection, clock sync, and a security on-call owner.",
    starter: { organizationTrail: false, independentArchive: false, immutableArchive: false, retentionDays: 7, realtimeDetection: false, clockSync: false, alertOwner: "nobody" },
    solution: { organizationTrail: true, independentArchive: true, immutableArchive: true, retentionDays: 365, realtimeDetection: true, clockSync: true, alertOwner: "security-on-call" },
    help: { organizationTrail: "Audit collection spans every account.", independentArchive: "Security controls the evidence store.", immutableArchive: "Stored events resist alteration.", retentionDays: "Evidence retention.", realtimeDetection: "High-value events are evaluated promptly.", clockSync: "Event times are comparable.", alertOwner: "Named response team." },
    checks: [
      check("Organization activity is collected", "Enable the organization trail and synchronized clocks.", (p) => p.organizationTrail === true && p.clockSync === true),
      check("Evidence survives workload compromise", "Use an independent immutable archive for at least 365 days.", (p) => p.independentArchive === true && p.immutableArchive === true && typeof p.retentionDays === "number" && p.retentionDays >= 365),
      check("Detections reach a responder", "Enable real-time detection owned by security-on-call.", (p) => p.realtimeDetection === true && p.alertOwner === "security-on-call"),
    ], source: architectureSource,
  }),
  lesson({
    id: 9, title: "Verify software provenance", minutes: 13,
    objective: "Require verifiable build provenance and dependency evidence before deployment.",
    story: "A signed image arrived from an untrusted workstation. Byte verifies how the artifact was built, not just who uploaded it.",
    concepts: [
      { title: "Provenance describes the build", body: "Provenance links source inputs, builder identity, parameters, and output digest. A verifier can then reject artifacts that did not originate from the approved delivery path." },
      { title: "Isolation reduces hidden influence", body: "An isolated or hermetic build limits undeclared network and filesystem inputs. Pinned dependencies and reproducible steps make the resulting artifact easier to explain and rebuild." },
      { title: "Verification belongs at admission", body: "A signature or SBOM is useful only when deployment checks it. Admission policy should verify trusted identity, provenance, digest, and required attestations before the workload runs." },
    ],
    example: "pinned source → isolated builder → SBOM + provenance + signature → admission verification",
    exampleNote: "The simulation models controls from the build through deployment; it does not generate cryptographic attestations.",
    mistake: "Producing an SBOM and signature but never checking them when an artifact enters the cluster.",
    mission: "Use an isolated build with pinned dependencies, produce SLSA provenance and an SBOM, sign the digest, and verify all evidence before deployment.",
    starter: { isolatedBuild: false, dependenciesPinned: false, provenance: "none", sbom: false, digestSigned: false, verifyBeforeDeploy: false },
    solution: { isolatedBuild: true, dependenciesPinned: true, provenance: "slsa", sbom: true, digestSigned: true, verifyBeforeDeploy: true },
    help: { isolatedBuild: "Builder limits undeclared influence.", dependenciesPinned: "Inputs resolve to fixed versions.", provenance: "Attestation format for build origin.", sbom: "Artifact component inventory.", digestSigned: "Signature covers immutable output.", verifyBeforeDeploy: "Admission rejects missing or invalid evidence." },
    checks: [
      check("Build inputs are controlled", "Use an isolated build with pinned dependencies.", (p) => p.isolatedBuild === true && p.dependenciesPinned === true),
      check("Artifact carries evidence", "Produce SLSA provenance, an SBOM, and a digest signature.", (p) => p.provenance === "slsa" && p.sbom === true && p.digestSigned === true),
      check("Deployment enforces trust", "Enable verifyBeforeDeploy.", (p) => p.verifyBeforeDeploy === true),
    ], source: slsaSource,
  }),
  lesson({
    id: 10, title: "Project: Zero-trust delivery", minutes: 19,
    objective: "Connect workload identity, private networking, artifact provenance, and independent evidence.",
    story: "The Zero Trust Vault admits a release only when every request proves its identity, scope, origin, and audit path.",
    concepts: [
      { title: "Trust is evaluated per request", body: "Repository location, network placement, or an internal label should not grant broad access. The deployment identity, artifact, requested action, and target resource are each verified." },
      { title: "Controls reinforce one another", body: "A private route reduces exposure, federation removes stored keys, and admission verifies artifact origin. Independent audit evidence records the decision and supports later investigation." },
      { title: "Failure should be a denial", body: "When identity claims, provenance, policy, or evidence are unavailable, the safe outcome is to stop deployment. An emergency process remains narrow, time-bound, approved, and observable." },
    ],
    example: "verified workflow identity + signed provenance + private endpoint + least privilege → deploy + immutable audit",
    exampleNote: "Each check represents a separate trust decision; passing one does not skip the others.",
    mistake: "Treating a request from the private network as implicitly authorized.",
    mission: "Design a deployment with short OIDC identity, claim restrictions, private service access, signed provenance, least privilege, admission verification, and immutable evidence.",
    starter: { oidcFederation: false, sessionMinutes: 480, claimsRestricted: false, privateServiceAccess: false, signedProvenance: false, leastPrivilege: false, admissionVerification: false, immutableAudit: false },
    solution: { oidcFederation: true, sessionMinutes: 15, claimsRestricted: true, privateServiceAccess: true, signedProvenance: true, leastPrivilege: true, admissionVerification: true, immutableAudit: true },
    help: { oidcFederation: "Short workload identity exchange.", sessionMinutes: "Identity lifetime.", claimsRestricted: "Repository and environment are verified.", privateServiceAccess: "Provider APIs use private endpoints.", signedProvenance: "Artifact origin is attested.", leastPrivilege: "Deployment actions and resources are narrow.", admissionVerification: "Evidence is checked before run.", immutableAudit: "Decision evidence resists alteration." },
    checks: [
      check("Workload proves a short identity", "Use restricted OIDC claims and a 5–30 minute session.", (p) => p.oidcFederation === true && p.claimsRestricted === true && between("sessionMinutes", 5, 30)(p)),
      check("Request uses a bounded path and permission", "Use private service access and least privilege.", (p) => p.privateServiceAccess === true && p.leastPrivilege === true),
      check("Artifact origin is enforced", "Require signed provenance and admission verification.", (p) => p.signedProvenance === true && p.admissionVerification === true),
      check("Decision leaves durable evidence", "Enable immutable audit.", (p) => p.immutableAudit === true),
    ], source: nistSource,
  }),
  lesson({
    id: 11, title: "Architect regional failover", minutes: 14,
    objective: "Design a controlled regional recovery path with explicit traffic and data decisions.",
    story: "A regional failure stranded healthy backups behind an untested routing plan. Byte turns recovery into an executable design.",
    concepts: [
      { title: "Recovery is a dependency graph", body: "Compute, data, identity, secrets, DNS, observability, and external integrations must all work in the recovery region. A second cluster is not a regional strategy when a hidden dependency remains local to the failed region." },
      { title: "Data behavior drives topology", body: "Replication delay, conflict handling, and write ownership determine the achievable recovery point. An active-passive design can keep one writer and use a deliberate promotion step to avoid split-brain writes." },
      { title: "Traffic control needs evidence", body: "External health checks and a low DNS time-to-live can move clients, but only a full exercise proves permissions, runbooks, data promotion, and application health. Record measured recovery time and recovery point after each test." },
    ],
    example: "external health check → stop primary writes → promote replica → shift DNS → verify service",
    exampleNote: "Failover order protects data consistency before traffic reaches the recovery region.",
    mistake: "Calling a copied stack disaster recovery without replicating its data or testing the cutover.",
    mission: "Create an active-passive design across two regions with replicated data, one writer, external health checks, a 60-second DNS TTL, and a tested failover.",
    starter: { strategy: "single-region", primaryRegion: "eu-west-1", recoveryRegion: "none", externalHealthChecks: false, dnsTtlSeconds: 3600, replicatedData: false, singleWriter: false, failoverTested: false },
    solution: { strategy: "active-passive", primaryRegion: "eu-west-1", recoveryRegion: "eu-central-1", externalHealthChecks: true, dnsTtlSeconds: 60, replicatedData: true, singleWriter: true, failoverTested: true },
    help: { strategy: "How regions serve traffic.", primaryRegion: "Normal service location.", recoveryRegion: "Independent recovery location.", externalHealthChecks: "Health is observed outside either region.", dnsTtlSeconds: "Maximum cached routing interval.", replicatedData: "Service data reaches recovery.", singleWriter: "Only one region accepts writes.", failoverTested: "A full cutover was exercised." },
    checks: [
      check("Regions have distinct roles", "Use active-passive with eu-west-1 primary and eu-central-1 recovery.", (p) => p.strategy === "active-passive" && p.primaryRegion === "eu-west-1" && p.recoveryRegion === "eu-central-1"),
      check("Traffic can move promptly", "Use external health checks and a DNS TTL from 30 to 120 seconds.", (p) => p.externalHealthChecks === true && between("dnsTtlSeconds", 30, 120)(p)),
      check("Data avoids split brain", "Replicate data and keep one writer.", (p) => p.replicatedData === true && p.singleWriter === true),
      check("Recovery is proven", "Run a full failover test.", (p) => p.failoverTested === true),
    ], source: architectureSource,
  }),
  lesson({
    id: 12, title: "Run safe chaos experiments", minutes: 13,
    objective: "Test a reliability hypothesis while bounding customer and operational risk.",
    story: "A surprise node loss caused an outage even though the architecture diagram promised redundancy. Byte tests the promise safely.",
    concepts: [
      { title: "Start with a falsifiable hypothesis", body: "Define the steady-state signal and the expected behavior before injecting failure. A statement such as successful requests remain above the threshold can be measured; hoping the platform survives cannot." },
      { title: "Bound the blast radius", body: "Begin in a production-like non-production environment or a tiny production slice. Limit affected traffic, name an owner, prepare rollback, and stop automatically when an abort threshold is crossed." },
      { title: "Experiments improve systems", body: "Record what happened, repair the weakness, and repeat the experiment. The purpose is evidence about resilience, not dramatic failure or blame." },
    ],
    example: "measure steady state → remove one staging node → watch threshold → abort or learn → repair and repeat",
    exampleNote: "The abort threshold is tighter than the maximum experimental blast radius.",
    mistake: "Injecting failure in production without a baseline, stop condition, or accountable operator.",
    mission: "Define and measure a hypothesis in staging, limit the blast radius to 10%, abort at 5% impact, assign an owner, and prepare rollback.",
    starter: { hypothesisDefined: false, environment: "production", blastRadiusPercent: 100, abortThresholdPercent: 50, steadyStateMeasured: false, ownerAssigned: false, rollbackReady: false },
    solution: { hypothesisDefined: true, environment: "staging", blastRadiusPercent: 10, abortThresholdPercent: 5, steadyStateMeasured: true, ownerAssigned: true, rollbackReady: true },
    help: { hypothesisDefined: "Expected measurable behavior.", environment: "Initial experiment location.", blastRadiusPercent: "Maximum traffic or capacity exposed.", abortThresholdPercent: "Impact that stops the experiment.", steadyStateMeasured: "Baseline was recorded.", ownerAssigned: "Named operator controls the test.", rollbackReady: "Recovery action is prepared." },
    checks: [
      check("Experiment begins with evidence", "Define a hypothesis and measure steady state.", (p) => p.hypothesisDefined === true && p.steadyStateMeasured === true),
      check("First run is contained", "Use staging and a blast radius from 1% to 10%.", (p) => p.environment === "staging" && between("blastRadiusPercent", 1, 10)(p)),
      check("Abort condition is strict", "Set abort impact from 1% to 5%, no greater than the blast radius.", (p) => between("abortThresholdPercent", 1, 5)(p) && typeof p.blastRadiusPercent === "number" && typeof p.abortThresholdPercent === "number" && p.abortThresholdPercent <= p.blastRadiusPercent),
      check("A human can stop and recover", "Assign an owner and prepare rollback.", (p) => p.ownerAssigned === true && p.rollbackReady === true),
    ], source: sreSource,
  }),
  lesson({
    id: 13, title: "Lead a major incident", minutes: 13,
    objective: "Establish clear incident command, communication, evidence, and follow-through.",
    story: "During a widespread outage, five responders issued conflicting changes and customers heard nothing. Byte creates one operating rhythm.",
    concepts: [
      { title: "Command separates coordination from repair", body: "An incident commander owns priorities and decisions while an operations lead coordinates technical work and a communications lead publishes updates. Explicit roles reduce duplicated or contradictory actions." },
      { title: "A timeline preserves shared truth", body: "Record symptoms, decisions, changes, and outcomes as they occur. Regular internal and external updates communicate known facts, current impact, next actions, and the next update time." },
      { title: "Learning closes the incident", body: "A blameless review studies the conditions that allowed impact and assigns durable actions to owners with dates. Restoring traffic ends response, not the improvement work." },
    ],
    example: "declare SEV-1 → assign command/operations/comms → update every 30 minutes → review → owned actions",
    exampleNote: "Role names represent responsibilities; a small team may assign more than one role to a person.",
    mistake: "Letting every responder make production changes while no one owns priorities or customer communication.",
    mission: "Declare SEV-1, assign command, operations, and communications leads, update within 30 minutes, preserve a timeline, and produce owned blameless actions.",
    starter: { severity: "SEV-3", incidentCommander: "unassigned", operationsLead: "unassigned", communicationsLead: "unassigned", updateIntervalMinutes: 120, timelineRecorded: false, blamelessPostmortem: false, actionOwners: false },
    solution: { severity: "SEV-1", incidentCommander: "incident-commander", operationsLead: "operations-lead", communicationsLead: "communications-lead", updateIntervalMinutes: 30, timelineRecorded: true, blamelessPostmortem: true, actionOwners: true },
    help: { severity: "Declared impact class.", incidentCommander: "Owns priorities and coordination.", operationsLead: "Coordinates technical response.", communicationsLead: "Publishes stakeholder updates.", updateIntervalMinutes: "Maximum time between updates.", timelineRecorded: "Events and decisions are captured.", blamelessPostmortem: "Review focuses on system conditions.", actionOwners: "Improvements have accountable owners." },
    checks: [
      check("Major impact is declared", "Set severity to SEV-1.", (p) => p.severity === "SEV-1"),
      check("Response roles are explicit", "Assign incident-commander, operations-lead, and communications-lead.", (p) => p.incidentCommander === "incident-commander" && p.operationsLead === "operations-lead" && p.communicationsLead === "communications-lead"),
      check("Communication stays current", "Update every 15 to 30 minutes and record the timeline.", (p) => between("updateIntervalMinutes", 15, 30)(p) && p.timelineRecorded === true),
      check("Learning has accountability", "Use a blameless postmortem with owned actions.", (p) => p.blamelessPostmortem === true && p.actionOwners === true),
    ], source: sreSource,
  }),
  lesson({
    id: 14, title: "Govern cloud unit economics", minutes: 13,
    objective: "Connect cloud cost to service demand and add timely allocation and spending guardrails.",
    story: "The bill grew 40%, but raw account totals cannot show whether demand, waste, or price caused it. Byte creates a useful unit cost.",
    concepts: [
      { title: "Unit economics explains change", body: "Cost per request, tenant, build, or other value unit separates demand growth from efficiency loss. Choose a metric teams can measure consistently and connect it to both cost and service outcomes." },
      { title: "Allocation creates accountability", body: "Standard team, service, and environment metadata assigns spend to owners. Shared costs need a documented allocation rule rather than disappearing into an unowned platform bucket." },
      { title: "Optimize after measuring", body: "Budgets and anomaly detection reveal change quickly, while quotas limit accidental scale. Establish a representative usage baseline before buying long commitments or removing capacity that protects reliability." },
    ],
    example: "allocated monthly cost ÷ successful requests → trend unit cost → investigate anomaly → optimize safely",
    exampleNote: "The unit metric complements budgets; it does not replace absolute cost or reliability signals.",
    mistake: "Purchasing a long commitment from one week of traffic without checking seasonality or service plans.",
    mission: "Measure cost per request, allocate by team/service/environment, enable budgets and anomaly detection, observe 30 days before commitments, and add a quota guardrail.",
    starter: { unitMetric: "total-bill", allocationTags: ["owner"], budgetAlerts: false, anomalyDetection: false, measurementDays: 3, commitmentsAfterBaseline: false, quotaGuardrail: false },
    solution: { unitMetric: "requests-per-credit", allocationTags: ["team", "service", "environment"], budgetAlerts: true, anomalyDetection: true, measurementDays: 30, commitmentsAfterBaseline: true, quotaGuardrail: true },
    help: { unitMetric: "Demand-normalized cost measure.", allocationTags: "Metadata assigning spend to owners.", budgetAlerts: "Threshold notifications are active.", anomalyDetection: "Unexpected spending changes are detected.", measurementDays: "Representative baseline window.", commitmentsAfterBaseline: "Long discounts follow evidence.", quotaGuardrail: "Maximum accidental consumption is bounded." },
    checks: [
      check("Cost is tied to service demand", "Use requests-per-credit as the unit metric.", (p) => p.unitMetric === "requests-per-credit"),
      check("Spend has complete ownership", "Allocate with team, service, and environment.", (p) => exactSet(p.allocationTags, ["team", "service", "environment"])),
      check("Changes surface quickly", "Enable budget alerts and anomaly detection.", (p) => p.budgetAlerts === true && p.anomalyDetection === true),
      check("Optimization is evidence-led", "Measure at least 30 days, commit afterward, and enforce a quota.", (p) => typeof p.measurementDays === "number" && p.measurementDays >= 30 && p.commitmentsAfterBaseline === true && p.quotaGuardrail === true),
    ], source: finopsSource,
  }),
  lesson({
    id: 15, title: "Project: Self-service cloud platform", minutes: 28,
    objective: "Design a governed paved road that teams can use safely without waiting on platform tickets.",
    story: "The Resilience Command must let product teams launch reliable services quickly while keeping identity, evidence, recovery, and cost controls verifiable.",
    concepts: [
      { title: "A platform is a product", body: "A self-service portal and golden path package infrastructure, deployment, observability, and support into a coherent developer experience. Measure adoption and task success instead of counting platform components." },
      { title: "Guardrails make autonomy safe", body: "Account vending, workload federation, private networking, policy checks, and provenance verification create secure defaults. Teams receive useful freedom inside a clearly enforced operating envelope." },
      { title: "Escape hatches are designed", body: "Some workloads will not fit the paved road. A reviewed, time-bound exception with an owner and compensating controls protects delivery without silently weakening the platform." },
      { title: "Operations complete the contract", body: "Service objectives, regional recovery, tenant isolation, and cost allocation make the platform operable at scale. The platform itself needs an SLO so teams can rely on its workflows." },
    ],
    example: "service request → vend account → deploy golden path → enforce controls → expose SLO, recovery, and unit cost",
    exampleNote: "This world project validates a platform operating model; it does not provision external cloud resources.",
    mistake: "Calling a collection of templates self-service while every deployment still needs privileged manual approval.",
    mission: "Build a self-service golden path with automated account vending, identity and supply-chain guardrails, private networking, SLOs, recovery, tenant and cost controls, plus a reviewed escape hatch.",
    starter: { selfServicePortal: false, goldenPath: false, accountVending: false, policyGuardrails: false, workloadFederation: false, provenanceVerified: false, privateNetworking: false, serviceObjectives: false, regionalRecovery: false, costAllocation: false, tenantIsolation: false, reviewedEscapeHatch: false, platformSlo: "none" },
    solution: { selfServicePortal: true, goldenPath: true, accountVending: true, policyGuardrails: true, workloadFederation: true, provenanceVerified: true, privateNetworking: true, serviceObjectives: true, regionalRecovery: true, costAllocation: true, tenantIsolation: true, reviewedEscapeHatch: true, platformSlo: "99.9%" },
    help: { selfServicePortal: "Teams initiate standard workflows directly.", goldenPath: "Supported default service journey.", accountVending: "Governed environments are created automatically.", policyGuardrails: "Unsafe infrastructure is prevented.", workloadFederation: "Pipelines use short-lived identity.", provenanceVerified: "Artifact origin is enforced.", privateNetworking: "Managed-service traffic avoids public routes.", serviceObjectives: "Workloads define user-centered reliability.", regionalRecovery: "Regional cutover is designed and tested.", costAllocation: "Spend maps to owners and units.", tenantIsolation: "Workload boundaries are explicit.", reviewedEscapeHatch: "Exceptions are owned, scoped, and expiring.", platformSlo: "Reliability target for platform workflows." },
    checks: [
      check("Developer journey is self-service", "Enable the portal, golden path, and automated account vending.", (p) => p.selfServicePortal === true && p.goldenPath === true && p.accountVending === true),
      check("Default delivery verifies trust", "Use policy guardrails, workload federation, provenance verification, and private networking.", (p) => p.policyGuardrails === true && p.workloadFederation === true && p.provenanceVerified === true && p.privateNetworking === true),
      check("Operations scale deliberately", "Define service objectives, regional recovery, cost allocation, and tenant isolation.", (p) => p.serviceObjectives === true && p.regionalRecovery === true && p.costAllocation === true && p.tenantIsolation === true),
      check("Platform contract handles exceptions", "Use a reviewed escape hatch and a 99.9% platform SLO.", (p) => p.reviewedEscapeHatch === true && p.platformSlo === "99.9%"),
    ], source: architectureSource,
  }),
];

const INTERMEDIATE_DELIVERY_LESSONS: CloudLesson[] = [
  lesson({
    id: 9, title: "Roll out without an outage", minutes: 11,
    objective: "Set a rolling update policy that keeps healthy capacity during a release.",
    story: "The scheduler removed every old pod before the first new pod became ready. Byte rewrites the rollout budget.",
    concepts: [
      { title: "Availability is a rollout constraint", body: "maxUnavailable controls how many desired replicas may be unavailable during an update. Setting it to zero for this three-replica service keeps the existing capacity until replacements become ready." },
      { title: "Surge buys transition capacity", body: "maxSurge allows temporary extra pods while old and new versions overlap. That capacity must fit the cluster and quotas or the rollout can stall." },
      { title: "Deadlines turn stalls into signals", body: "A progress deadline detects a rollout that cannot produce ready replicas. Retained revisions support a quick rollback, while monitoring confirms whether rollback is actually required." },
    ],
    example: "3 old ready → start 1 new → new ready → remove 1 old → repeat",
    exampleNote: "The sequence uses maxUnavailable 0 and maxSurge 1.",
    mistake: "Calling a rollout zero-downtime without a readiness gate or enough cluster capacity for the surge.",
    mission: "Use a rolling update with zero unavailable, one surge pod, readiness gating, a 5–20 minute deadline, and retained revisions.",
    starter: { strategy: "recreate", maxUnavailable: 3, maxSurge: 0, readinessGate: false, progressDeadlineMinutes: 60, retainedRevisions: 0 },
    solution: { strategy: "rolling-update", maxUnavailable: 0, maxSurge: 1, readinessGate: true, progressDeadlineMinutes: 10, retainedRevisions: 3 },
    help: { strategy: "Deployment replacement strategy.", maxUnavailable: "Unavailable desired pods during update.", maxSurge: "Temporary extra pods.", readinessGate: "Wait for readiness before continuing.", progressDeadlineMinutes: "Time before declaring a stalled rollout.", retainedRevisions: "Releases available for rollback." },
    checks: [
      check("Healthy capacity is preserved", "Use rolling-update and maxUnavailable 0.", (p) => p.strategy === "rolling-update" && p.maxUnavailable === 0),
      check("Transition has bounded capacity", "Use maxSurge 1 and readiness gating.", (p) => p.maxSurge === 1 && p.readinessGate === true),
      check("Stalls and rollback are supported", "Use a 5–20 minute deadline and retain at least two revisions.", (p) => between("progressDeadlineMinutes", 5, 20)(p) && typeof p.retainedRevisions === "number" && p.retainedRevisions >= 2),
    ], source: kubernetesSource,
  }),
  lesson({
    id: 10, title: "Project: Continuous delivery", minutes: 17,
    objective: "Connect pipeline evidence, artifact promotion, and a safe Kubernetes rollout.",
    story: "The Delivery Foundry must prove that the tested image is the released image and that a failing replacement cannot drop healthy traffic.",
    concepts: [
      { title: "Evidence follows the artifact", body: "Tests, vulnerability results, an SBOM, and a signature describe a particular digest. Promotion preserves that digest so production receives the artifact the pipeline evaluated." },
      { title: "Deployment policy consumes evidence", body: "A protected production job verifies the artifact and applies a rollout policy. Readiness and availability constraints then decide when the new version may receive traffic." },
      { title: "Recovery belongs in the release design", body: "Retaining a known-good revision and detecting stalled progress shortens recovery. Teams should also define who can initiate rollback and how they verify restored service." },
    ],
    example: "lint → test → build once → scan + sign → stage digest → approve → rolling production update",
    exampleNote: "The project is a deterministic release simulation and creates no workflow or cluster.",
    mistake: "Using a safe rollout policy with an artifact that was rebuilt after its security checks.",
    mission: "Design an ordered pipeline that promotes one signed artifact into a three-replica, readiness-gated rolling deployment.",
    starter: { stages: ["build", "deploy"], sameDigest: false, signed: false, sbom: false, replicas: 1, resourceRequests: false, readinessPath: "/live", maxUnavailable: 2, productionApproval: false },
    solution: { stages: ["lint", "test", "build", "scan", "deploy"], sameDigest: true, signed: true, sbom: true, replicas: 3, resourceRequests: true, readinessPath: "/ready", maxUnavailable: 0, productionApproval: true },
    help: { stages: "Delivery jobs in required order.", sameDigest: "Staging and production use identical bytes.", signed: "Build identity signs the artifact.", sbom: "Component inventory is attached.", replicas: "Application pod copies.", resourceRequests: "Scheduler requests are set.", readinessPath: "Endpoint controlling traffic.", maxUnavailable: "Allowed unavailable replicas.", productionApproval: "Protected production gate." },
    checks: [
      check("Pipeline builds evidence before deploy", "Use lint, test, build, scan, deploy in order.", (p) => ordered(p.stages, ["lint", "test", "build", "scan", "deploy"])),
      check("Verified artifact is promoted", "Keep one signed digest with an SBOM.", (p) => p.sameDigest === true && p.signed === true && p.sbom === true),
      check("Workload has an operating contract", "Use three replicas, requests, and /ready.", (p) => p.replicas === 3 && p.resourceRequests === true && p.readinessPath === "/ready"),
      check("Production rollout protects availability", "Set maxUnavailable zero and require approval.", (p) => p.maxUnavailable === 0 && p.productionApproval === true),
    ], source: kubernetesSource,
  }),
];

export const INTERMEDIATE_CLOUD_LESSONS: CloudLesson[] = [
  ...INTERMEDIATE_CLOUD_LESSON_PARTS.slice(0, 8),
  ...INTERMEDIATE_DELIVERY_LESSONS,
  ...INTERMEDIATE_CLOUD_LESSON_PARTS.slice(8),
];
