import type { CloudLesson } from "./model";
import type { CloudPaceId } from "./track";

export type CloudCheckpoint = {
  question: string;
  options: [string, string, string];
  answer: number;
  explanation: string;
};

type Seed = Omit<CloudCheckpoint, "answer">;
const q = (question: string, correct: string, wrongA: string, wrongB: string, explanation: string): Seed => ({
  question,
  options: [correct, wrongA, wrongB],
  explanation,
});

const beginner: Seed[] = [
  q("For a managed-container service, which ownership split is correct?", "The provider patches physical hosts; the team controls application permissions and data access.", "The provider controls application permissions because it owns the hardware.", "The application team must repair the provider's physical network.", "Cloud responsibility is shared. Managed infrastructure removes some host work, but application identity and data access remain with the team."),
  q("What makes two application copies resilient to a single-zone outage?", "Place the copies in two distinct availability zones and ensure dependent services support the design.", "Place both copies on different machines inside one availability zone.", "Use two region labels while keeping both copies in one zone.", "Zones are separate failure domains. Replica count alone does not help when every copy shares the same zone-level dependency."),
  q("Why does managed-container compute fit the Relay API?", "It runs the supplied long-lived container without requiring the team to maintain a guest operating system.", "Functions always run any existing container continuously with no platform limits.", "A virtual machine removes all guest patching and capacity responsibilities.", "The workload already has a container and needs a continuously available service; managed containers match that packaging and operating requirement."),
  q("Which storage plan protects reports from anonymous reads and accidental overwrites?", "Disable public reads, enable encryption and versioning, and retain prior versions for the required window.", "Enable encryption but keep anonymous reads enabled for convenience.", "Disable versioning because encrypted objects can always be recovered.", "Confidentiality, encryption, and recovery are separate controls. The plan needs all three rather than relying on encryption alone."),
  q("What should a foundation recovery review prove?", "The complete request path and its dependencies still satisfy availability and data-protection requirements during failure.", "Every resource uses the same zone so troubleshooting is simpler.", "One passing availability check proves every access-control requirement.", "A system is only as resilient as its dependencies, and each security and recovery requirement needs independent evidence."),
  q("Which network path follows least exposure for a web API and PostgreSQL database?", "Users reach a public edge; the application and database stay private; only the app reaches PostgreSQL on 5432.", "Users connect directly to a public database so the application needs no network rule.", "The application is public and the database accepts traffic from anywhere on port 80.", "A narrow hop-by-hop route exposes only the edge and limits database access to the application on the intended service port."),
  q("What must be true in addition to a successful DNS lookup?", "The certificate must be valid for HTTPS and the edge must forward to the correct private origin port.", "DNS automatically encrypts the client connection and validates the certificate.", "A valid certificate repairs an incorrect DNS target without a record change.", "DNS, TLS, and the origin connection are independent layers; success at one layer cannot prove the others."),
  q("Which identity design best limits application access?", "Give the workload a short-lived identity with only the required actions on the required resource.", "Store a permanent administrator key inside the application image.", "Grant every workload the same wildcard role to simplify operations.", "Workload identity should be temporary and least-privileged so a compromised process has a narrow, short-lived capability."),
  q("How should an application obtain a database secret?", "Resolve an authorized secret reference at runtime, rotate it, and keep values out of source code and logs.", "Commit the value to the repository so every deployment receives it.", "Print the value during startup to prove that injection worked.", "Secret references and runtime identity let values rotate without source changes while avoiding durable copies in repositories or logs."),
  q("What makes the Network Bastion secure as a system?", "Private service placement, narrow network paths, workload identity, runtime secret retrieval, and encrypted edge traffic reinforce one another.", "A private subnet makes identity and secret controls unnecessary.", "HTTPS at the edge permits direct public database access.", "Layered controls cover different failure modes; network location does not replace identity, encryption, or secret handling."),
  q("Which container is ready to receive service traffic safely?", "A pinned image runs as non-root, listens on the service interface, and exposes the expected application port.", "An unpinned latest image runs as root and binds only to localhost.", "Any image is safe when the container scheduler reports that it started.", "Immutable image selection, reduced privilege, and a reachable listener are separate prerequisites for a predictable service."),
  q("What is the safest way to release a new API version?", "Test a pinned version, send a small canary share, retain the previous version, and roll back on harmful signals.", "Replace every instance immediately and delete the old version before observing metrics.", "Deploy the latest tag without tests because rollback can rebuild it later.", "A canary limits initial exposure, while immutable versions and a retained predecessor make the rollback target known."),
  q("When should an availability alert notify the on-call responder?", "When a user-centered signal breaches its threshold for a meaningful window and the alert has a named owner.", "For every single request error, regardless of duration or user impact.", "Only after users report the outage manually.", "Useful alerts connect sustained user impact to an actionable owner instead of paging on noise or waiting for complaints."),
  q("Which scaling policy balances demand and the lesson's budget?", "Use validated minimum and maximum replicas, scale from measured demand, and keep the maximum within the modeled budget.", "Set unlimited replicas so demand can never exceed capacity.", "Keep one fixed replica because fixed capacity always costs less safely.", "Autoscaling still needs lower and upper bounds; the simulator derives capacity and cost from demand within those guardrails."),
  q("What does the third Beginner world project need to demonstrate?", "A secure end-to-end request path, private data, safe identity and secrets, observable releases, recovery, and bounded capacity.", "Only that the JSON parses without syntax errors.", "Only that two application replicas start in the same zone.", "The project is an integrated architecture review: every control must work together and both allowed and denied paths need evidence."),
  q("Which response is safest to cache at the edge for many users?", "A versioned static asset with a deliberate TTL, while personalized API responses bypass the shared cache.", "An account response containing the current user's profile and permissions.", "Every GET response because the HTTP method alone guarantees it is public and current.", "Cache policy must consider whether content is reusable and how freshness is controlled; the request method alone cannot establish either property."),
  q("Why must a queued worker use an idempotency key?", "The same message may be delivered again, so repeated processing must preserve one intended outcome.", "The key guarantees that the queue will deliver every message exactly once.", "The key lets failed messages retry forever without a dead-letter queue.", "At-least-once delivery and worker crashes can produce repeats; stable operation identity lets the application recognize and safely handle them."),
  q("Why are both a multi-zone standby and backups required for the managed database?", "The standby reduces infrastructure interruption, while backups can recover from data corruption or accidental deletion.", "The standby is an offline historical copy that automatically reverses bad writes.", "Backups make private network access and application credentials unnecessary.", "Availability and data recovery address different failure modes: replicas can copy logical mistakes, while a recovery point preserves earlier state."),
  q("What makes a cloud budget actionable rather than decorative?", "Allocated owner/service/environment costs trigger an early alert and anomaly review assigned to a named team.", "The provider automatically stops all production resources when the monthly total reaches the limit.", "One unowned total is reviewed after the invoice closes and needs no service metadata.", "Allocation explains who can act, and early thresholds plus anomaly signals create time to investigate without turning a cost event into an outage."),
  q("What proves that stated RPO and RTO targets are credible?", "A full restore drill measures data age and end-to-end service recovery against both targets, including dependencies.", "A backup dashboard reports that yesterday's job completed successfully.", "The database storage restored within the RTO even though validation and traffic return were not measured.", "Recovery objectives describe service outcomes. Only exercised restoration, validation, dependency recovery, and traffic return can provide matching evidence."),
  q("What must the final Beginner operations capstone connect?", "Safe caching, duplicate-tolerant queued work, private managed data, cost ownership, and a tested recovery path.", "Only enough edge caching to minimize every origin request.", "Only a multi-zone database because managed services cover queues, costs, and recovery automatically.", "An operable service coordinates performance, asynchronous work, data protection, ownership, and recovery rather than optimizing one component alone."),
];

const intermediate: Seed[] = [
  q("Which Terraform state design supports safe team changes?", "Use an encrypted, versioned remote backend with locking and narrowly scoped access.", "Commit local state to Git so every engineer can edit the latest copy.", "Let multiple pipelines write state concurrently to reduce delivery time.", "Remote state gives collaborators one protected record, while locking prevents competing writers and versioning supports recovery."),
  q("What makes an infrastructure module reusable without hiding risk?", "Expose purposeful inputs and outputs, pin its version, validate inputs, and keep provider assumptions explicit.", "Copy the module source into every environment and edit each copy independently.", "Hard-code account IDs and regions so callers cannot make choices.", "A stable module contract captures a repeatable pattern while validation and version pinning keep changes reviewable."),
  q("What deserves special attention in an infrastructure change plan?", "Replacements, deletions, public exposure, privilege expansion, and unexpected resource count changes.", "Only the number of lines in the configuration file.", "Only whether the plan command exited successfully.", "A successful plan is not an approval; reviewers must interpret destructive, security-sensitive, and unexpectedly broad changes."),
  q("Which artifact should a deployment trust?", "An immutable digest built by the approved pipeline with a signature, scan result, and SBOM tied to that digest.", "A mutable latest tag uploaded from any developer workstation.", "An image whose repository name looks familiar even when its digest changed.", "Trust comes from immutable identity and verifiable build evidence, not from a mutable tag or familiar repository name."),
  q("What must a repeatable staging environment preserve?", "Isolated state and credentials, versioned modules, reviewed plans, policy checks, and the same deployment inputs used by automation.", "A shared production state file so both environments stay identical.", "Manual console changes that are documented after deployment.", "Repeatability requires declared inputs and isolated boundaries; sharing production state or relying on manual changes creates drift and risk."),
  q("How should a delivery workflow express job order?", "Use explicit dependencies so tests and security checks finish before build promotion and protected deployment.", "Run deployment first and execute tests afterward for faster feedback.", "Depend on job names sorting alphabetically into the intended sequence.", "Workflow dependencies make the required evidence chain executable and prevent deployment from racing ahead of validation."),
  q("What does 'build once, promote' guarantee?", "Staging and production receive the same immutable artifact digest that passed testing and security checks.", "Production rebuilds from the same branch and is assumed to produce identical bytes.", "Every environment uses the latest tag at the time it deploys.", "Promoting one digest preserves the identity of the tested artifact; rebuilding introduces new, unverified bytes."),
  q("Which Kubernetes workload contract is operationally safe?", "Set resource requests and limits, multiple replicas, readiness and liveness behavior, and a disruption budget appropriate to the service.", "Omit requests so every pod can reserve the entire cluster when needed.", "Use a liveness probe as the only signal that a pod may receive traffic.", "Scheduling, traffic readiness, process recovery, and voluntary disruption are different concerns and need explicit controls."),
  q("How can a rolling update preserve healthy capacity?", "Use readiness gating, maxUnavailable zero for this service, bounded surge capacity, a progress deadline, and retained revisions.", "Delete every old pod before starting a replacement.", "Route traffic to each new pod immediately after its process starts.", "A safe rollout waits for readiness and uses availability and surge budgets so a failed replacement cannot remove all healthy capacity."),
  q("What proves a continuous-delivery design is coherent?", "Ordered validation produces one signed digest that a protected, readiness-gated production rollout deploys with rollback support.", "A rolling strategy compensates for rebuilding the image after its scans.", "A production approval compensates for missing tests and provenance.", "Pipeline evidence, artifact identity, and runtime rollout controls form one chain; no single control substitutes for the others."),
  q("What is a useful service objective built from?", "A user-centered indicator, an explicit target and window, and an error budget that guides reliability decisions.", "A target of 100% for every internal metric with no measurement window.", "A dashboard of CPU usage without a statement about user success.", "An SLO turns measured user outcomes into a reliability target and leaves an error budget for managed risk."),
  q("How do logs, metrics, and traces become one troubleshooting system?", "Use consistent service metadata and correlation IDs so an alert can lead to traces and the relevant structured logs.", "Store each signal with unrelated names and clocks to avoid coupling.", "Collect only logs because every performance and dependency issue appears as text.", "Correlation and consistent context let responders move from a broad symptom to the specific request and dependency that caused it."),
  q("Which alert best detects fast and slow SLO threats?", "Use multi-window error-budget burn rates, require meaningful user impact, and route the alert to an actionable owner.", "Page whenever one request fails regardless of total traffic.", "Alert only after the entire monthly error budget is exhausted.", "Burn-rate windows catch severe incidents quickly while also detecting sustained slower consumption without paging on isolated noise."),
  q("What proves that a backup strategy can recover the service?", "A scheduled restore test verifies integrity and measures achieved recovery time and recovery point against the objectives.", "A dashboard showing that backup jobs reported success.", "A snapshot retained in the same failure boundary but never restored.", "Backup creation is only an input. Recovery confidence comes from restoring, validating data, and measuring the outcome."),
  q("What must the third Intermediate world project connect end to end?", "Protected infrastructure state, reviewed automation, one trusted artifact, safe Kubernetes rollout, SLO-based signals, and tested recovery.", "Only a complete CI workflow file, regardless of artifact or runtime behavior.", "Only a highly available cluster with no deployment evidence.", "Reliable delivery joins infrastructure, supply-chain, rollout, observability, and recovery evidence into one operating system."),
  q("How should automation handle detected infrastructure drift?", "Compare with reviewed Git intent, retain evidence, repair bounded low-risk differences, and review destructive reconciliation.", "Revert every difference immediately, including changes made to contain an active incident.", "Ignore drift until the next deployment because a successful plan cannot be affected by existing state.", "Drift handling needs an authoritative declaration and risk-based decisions; evidence and review prevent automation from amplifying an emergency or destructive change."),
  q("What is the core behavior of a pull-based GitOps deployment?", "A controller continuously reconciles runtime with a verified desired revision and reports health and convergence.", "A developer laptop pushes unreviewed commands directly to every production cluster.", "The repository stores plain secret values so the controller needs no external identity.", "GitOps makes reviewed desired state and continuous reconciliation observable, but still depends on policy, permissions, secret handling, and runtime health."),
  q("Which autoscaling signal best represents delayed background jobs?", "Queue depth or message age connected to measured worker throughput and bounded dependency capacity.", "Average cluster CPU even when workers spend most time waiting on an external database.", "An unlimited maximum worker count that expands until every queue is empty.", "The signal should describe unfinished user work, while load-tested bounds keep the scaler from overwhelming dependencies or producing uncontrolled cost."),
  q("What does mutual TLS not prove by itself for an internal request?", "Whether the authenticated caller is authorized to perform this action on the requested resource.", "Whether the channel is encrypted between the two authenticated peers.", "Whether the peer presented a certificate accepted by the configured trust policy.", "Authentication and channel protection establish who communicated securely; a separate default-deny policy must still decide what that caller may do."),
  q("Which game-day design produces useful evidence with bounded risk?", "A measurable hypothesis, limited blast radius, abort threshold, assigned commander, prepared rollback, and tracked findings.", "A surprise production failure with no stop condition so responders behave naturally.", "A tabletop discussion that records no result, owner, or change to the system.", "A controlled exercise needs a falsifiable prediction and containment, then must translate measured outcomes into owned improvements before the next incident."),
  q("What makes the final Intermediate production control loop complete?", "It detects drift, reconciles verified intent, gates health, scales on meaningful demand, verifies service calls, and exercises recovery.", "It deploys one signed artifact and assumes runtime state will remain correct afterward.", "It runs a game day but permits unverified revisions and unauthenticated internal requests.", "Production delivery is continuous: desired state, runtime health, capacity, trust decisions, and failure learning all feed an owned operating loop."),
];
const expert: Seed[] = [
  q("Which account structure limits organizational blast radius?", "Separate production and security evidence into governed accounts, federate workforce access, and constrain organization-wide privileges.", "Run production, development, and audit storage under one shared administrator.", "Create many accounts but reuse the same unrestricted root credentials across them.", "Accounts become useful boundaries only when identity, evidence ownership, and organization guardrails preserve their separation."),
  q("What makes a hub-and-spoke network governable at scale?", "Central transit and inspection connect isolated spokes through explicit routes while preventing unintended spoke-to-spoke access.", "A full mesh gives every workload a direct route to every other workload.", "One flat network avoids routing decisions and therefore reduces blast radius.", "A governed transit design centralizes shared controls while retaining workload segmentation and deliberate connectivity."),
  q("How should a private workload reach a managed service?", "Resolve the normal service name to a private endpoint, remove the public route, and restrict both endpoint policy and workload identity.", "Keep public DNS and unrestricted egress because the endpoint exists somewhere in the network.", "Treat private network location as authorization to every managed-service resource.", "Private routing reduces exposure, but DNS selection, endpoint policy, and identity authorization must all agree."),
  q("How should a critical policy-as-code guardrail be introduced?", "Evaluate it in audit mode, repair impact and false positives, then enforce denial with owned, expiring exceptions.", "Turn on organization-wide denial immediately and add permanent administrator bypasses when teams fail.", "Keep the policy advisory forever so it can never interrupt delivery.", "A measured rollout makes enforcement reliable, while scoped and expiring exceptions keep necessary deviations visible."),
  q("What proves a landing zone is ready for production onboarding?", "Account vending consistently attaches identity, immutable evidence, inspected networking, private access, guardrails, and conformance checks.", "An empty production account exists and teams can configure the rest manually.", "A reference architecture diagram lists controls that have not been exercised.", "A landing zone is an operating foundation, so onboarding automation and continuous evidence must verify every promised control."),
  q("Which workload federation policy is least privileged?", "Trust the approved issuer, audience, repository, and production environment, then issue a short session with no stored cloud key.", "Trust every token from the workflow provider for twelve hours.", "Keep a permanent deployment key as the primary credential and use OIDC only as fallback.", "Specific claims bind the external workload to the intended release context, and short sessions reduce token exposure."),
  q("How should encryption-key power be divided?", "Applications receive narrow cryptographic use, separate administrators manage policy and rotation, and deletion requires a recoverable waiting period.", "The application role can decrypt data, edit key policy, export key material, and delete the key immediately.", "Rotation deletes all prior key material whether or not stored data still depends on it.", "Separating use from administration and delaying deletion reduces both compromise impact and accidental data loss."),
  q("Which audit design preserves evidence after a workload compromise?", "Stream organization-wide events to a security-owned immutable archive and real-time detections with synchronized clocks and an alert owner.", "Store logs only inside each workload account under its administrator.", "Retain seven days of local logs and rely on responders to export them during an incident.", "Independent administration and immutability prevent a compromised workload operator from erasing the evidence needed for detection and investigation."),
  q("What should admission verify before running a software artifact?", "The immutable digest, trusted builder identity, signed provenance, required SBOM, and controlled build inputs.", "Only that the image has a human-readable tag.", "Only that someone with repository write access uploaded a signature file.", "Supply-chain trust connects declared source and an isolated builder to immutable output, then enforces that evidence at deployment."),
  q("What does zero-trust delivery require for each release?", "Verify short-lived workload identity, artifact provenance, requested permission, private service path, and immutable audit evidence.", "Treat every request from the private network as already authorized.", "Verify the artifact but allow any workload identity to deploy it anywhere.", "Zero trust makes separate decisions about identity, artifact, action, resource, and evidence instead of inheriting trust from location."),
  q("What is essential in an active-passive regional failover?", "Replicate every critical dependency, preserve one writer, use external health signals, control traffic change, and exercise the full cutover.", "Copy only compute resources and assume the primary region's data remains reachable.", "Allow both regions to accept writes without conflict handling during failover.", "Recovery depends on the whole dependency graph, and deliberate write promotion prevents split-brain data corruption."),
  q("What makes a chaos experiment safe and useful?", "Define a measurable hypothesis and baseline, bound the blast radius, set an abort threshold, assign an owner, and prepare rollback.", "Inject the largest possible production failure without telling responders.", "Choose the expected result after observing what happened.", "A controlled experiment tests a falsifiable resilience claim while explicit containment and recovery controls protect users."),
  q("How should a major incident be organized?", "Declare severity, assign command, operations, and communications roles, keep a decision timeline, publish regular updates, and own follow-up actions.", "Let every responder make independent production changes until the outage ends.", "Delay stakeholder communication until the root cause is completely proven.", "Clear roles and a shared operating rhythm reduce conflicting work, while the timeline and owned review turn response into learning."),
  q("Which FinOps signal explains whether cloud efficiency changed?", "Track allocated cost per meaningful service unit alongside budgets, anomalies, reliability, and a representative usage baseline.", "Compare only the total bill, regardless of demand growth.", "Buy long commitments immediately whenever one day of spend rises.", "Unit economics separates demand from efficiency, and allocation plus baseline evidence makes optimization accountable and safe."),
  q("What distinguishes a self-service cloud platform from a template collection?", "A supported golden path automates environments and delivery with guardrails, SLOs, recovery, tenant and cost controls, plus reviewed escape hatches.", "Teams copy templates and open privileged tickets for every deployment.", "The platform centralizes all decisions and offers no exception process.", "A platform is an operated product: it gives teams autonomy through reliable workflows and makes both default controls and exceptions explicit."),
  q("What is required before a shared namespace can be treated as a tenant boundary?", "Identity, network, secret, key, quota, and noisy-neighbor controls must independently contain the tenant's risk.", "The namespace name must include the tenant identifier, which isolates every control plane automatically.", "All tenants should share one wildcard workload identity so platform policy is consistent.", "A namespace is organizational context, not a complete isolation guarantee; layered controls and contention tests must support the claimed boundary."),
  q("Which data-residency design covers the complete lifecycle?", "Classification restricts primary data, replicas, backups, logs, exports, retention, and verified deletion to approved locations.", "Only the primary database is regional; every secondary copy may use global provider defaults.", "Deleting the user-facing record proves that caches, backups, and exports no longer retain it.", "Residency and lifecycle policies apply to every modeled copy, and preventive placement controls need inventory and deletion evidence."),
  q("What does N-minus-one regional capacity require in a two-region full-service design?", "Either surviving region and every critical dependency can serve peak demand plus planned headroom with quotas reserved.", "Each region carries half the normal load, so no additional capacity is needed after one fails.", "Only application compute is doubled because queues, databases, and address quotas scale automatically.", "Failover capacity is an end-to-end property: the surviving service path, dependencies, and provider limits must all support the promised demand."),
  q("How should a platform API handle a retried long-running create request?", "Use an idempotency key, return a durable asynchronous operation, and expose status through a versioned contract.", "Hold one connection open indefinitely and create a new environment after every client timeout.", "Return success immediately without an operation identifier or later error visibility.", "Retry-safe creation prevents duplicate infrastructure, while an operation resource lets clients observe work that outlives a single network connection."),
  q("Which evidence best shows that an internal platform works as a product?", "Successful self-service use, lead time, workflow reliability, satisfaction, support themes, and measured escape hatches inform an owned roadmap.", "The total number of templates published, regardless of whether teams can use them.", "A low ticket count without checking whether users abandoned the platform or built workarounds.", "Platform value combines completed user outcomes with speed, reliability, sentiment, and unsupported paths; no single activity count establishes success."),
  q("What must the final Expert platform capstone govern together?", "Tenant isolation, full data lifecycle, failover capacity, retry-safe APIs, and measured product ownership in one supported path.", "Only account structure and network segmentation because product and API behavior are separate concerns.", "Only developer adoption, even if residency, capacity, and tenant boundaries remain unverified.", "A governed platform connects technical controls to a usable service and continuously measures whether its reliability, policies, and user outcomes hold."),
];

const checkpointSeeds: Record<CloudPaceId, Seed[]> = { beginner, intermediate, expert };
const paceOffset: Record<CloudPaceId, number> = { beginner: 0, intermediate: 1, expert: 2 };

export function getCloudCheckpoint(paceId: CloudPaceId, lessonId: number): CloudCheckpoint {
  const seed = checkpointSeeds[paceId][lessonId - 1];
  if (!seed) throw new Error(`Missing Cloud checkpoint for ${paceId} lesson ${lessonId}.`);
  const shift = (lessonId + paceOffset[paceId]) % seed.options.length;
  const options = seed.options.map((_, index) => seed.options[(index + shift) % seed.options.length]) as [string, string, string];
  return { ...seed, options, answer: options.indexOf(seed.options[0]) };
}

function materializeScenario(seed: Seed, shift: number): CloudCheckpoint {
  const options = seed.options.map((_, index) => seed.options[(index + shift) % seed.options.length]) as [string, string, string];
  return { ...seed, options, answer: options.indexOf(seed.options[0]) };
}

function compact(value: string, maximum = 170) {
  const normalized = value.replace(/\s+/g, " ").trim();
  return normalized.length <= maximum ? normalized : normalized.slice(0, maximum - 1).trimEnd() + "…";
}

/** Three applied decisions per lesson: architecture, failure response, and evidence-led verification. */
export function getCloudCheckpoints(paceId: CloudPaceId, lesson: CloudLesson): [CloudCheckpoint, CloudCheckpoint, CloudCheckpoint] {
  const first = getCloudCheckpoint(paceId, lesson.id);
  const primary = lesson.checks[0];
  const secondary = lesson.checks[1] ?? primary;
  const starterEvidence = compact(lesson.observations(lesson.starter)[0] ?? "A required control does not match the intended architecture.", 150);
  const failure = q(
    `During “${lesson.title}”, a review uncovers this unsafe assumption: ${compact(lesson.mistake)} What should the team do next?`,
    `Pause approval and repair the bounded control: ${primary.hint}`,
    "Approve the change because the configuration is syntactically valid and revisit the concern after release.",
    "Change every available setting at once so the next run is more likely to pass.",
    `The failure conflicts with the lesson objective: ${compact(lesson.objective)} A narrow repair tied to “${primary.name}” is safer and produces clearer evidence than a broad or deferred change.`,
  );
  const evidence = q(
    `The “${lesson.title}” simulation reports: ${starterEvidence} Which verification plan produces the strongest evidence?`,
    `Test “${primary.name}” and “${secondary.name}” independently, change one relevant value, then compare the new trace.`,
    "Treat the first observation as root cause and close the review without rerunning the failed controls.",
    "Ignore the trace and add capacity, permissions, and retries together before measuring again.",
    `Observed evidence narrows a hypothesis but does not prove it. Independent checks for “${primary.name}” and “${secondary.name}” preserve causal clarity and reveal whether the repair created a regression.`,
  );
  const offset = lesson.id + paceOffset[paceId];
  return [first, materializeScenario(failure, (offset + 1) % 3), materializeScenario(evidence, (offset + 2) % 3)];
}
