import { architectureSource, between, check, containerSource, equals, exactSet, field, identitySource, pinnedImage, simulateCapacity, type CloudLesson } from "./model";

export const CLOUD_LESSONS: CloudLesson[] = [
  {
    id: 1, title: "Who owns the problem?", minutes: 7,
    objective: "Separate provider duties from the application team's duties.",
    story: "Byte found an incident ticket with no owner. Before rebuilding the Citadel, give every task a home.",
    concepts: [
      { title: "Renting changes responsibility", body: "Cloud computing lets you use infrastructure without owning the physical equipment. The provider manages some layers; your team still controls how its application and data are used. Moving to the cloud does not automatically secure an application." },
      { title: "The service model matters", body: "With a virtual machine you normally manage the guest operating system. A managed container platform takes care of more of the host infrastructure. Here we use managed containers: the provider maintains physical equipment and the host, while you set application permissions and data access." },
      { title: "Make ownership explicit", body: "A responsibility map is useful before an outage. Assign one accountable owner per task, then document how that owner detects and fixes problems. The exact boundary must be checked against the chosen service." },
    ],
    example: '{ "provider": ["physical-network"], "team": ["application-tests"] }',
    exampleNote: "This example assigns physical equipment to the provider and application behaviour to the team. The challenge uses different tasks.",
    mistake: "Assuming the provider manages application permissions because it runs the servers.",
    mission: "For our managed-container service, assign physical-security and host-patching to the provider; assign app-permissions and data-access to the team. Each task must appear exactly once.",
    fields: [field("provider", "strings", "Tasks owned by the provider."), field("team", "strings", "Tasks owned by the application team.")],
    starter: { provider: ["physical-security", "app-permissions"], team: ["host-patching", "data-access"] },
    solution: { provider: ["physical-security", "host-patching"], team: ["app-permissions", "data-access"] },
    checks: [check("Physical and host layers have an owner", "Move host-patching to provider; move app-permissions to team.", (p) => exactSet(p.provider, ["physical-security", "host-patching"])), check("Application and data access stay with the team", "The team owns both app-permissions and data-access, with no duplicate tasks.", (p) => exactSet(p.team, ["app-permissions", "data-access"]))],
    observations: (p) => [`Provider task count: ${(p.provider as string[]).length}. Team task count: ${(p.team as string[]).length}.`, "Drill: a permissions incident must go to the application team, even when the service is managed."],
    source: architectureSource,
  },
  {
    id: 2, title: "Regions and failure zones", minutes: 8,
    objective: "Place a service near its users without sharing a single failure zone.",
    story: "A power failure took out one tower. Byte needs a plan that survives losing that tower.",
    concepts: [
      { title: "A region is a geographic choice", body: "Regions help you choose where a workload runs. Consider data-location requirements, available services, latency, and cost together. A familiar region name is not a substitute for measuring the experience of your users." },
      { title: "Zones reduce shared failures", body: "Availability zones separate parts of a region into distinct failure domains. Two copies in the same zone can fail together. Copies across zones help only when traffic routing, storage, and recovery also support the design." },
      { title: "Choose for this workload", body: "Our fictional Relay contract requires region eu-west-1. This simulation provides two independent zones, eu-west-1a and eu-west-1b. These are labels in our model, not a claim about an actual account's physical placement." },
    ],
    example: '{ "region": "training-region", "zones": ["training-a", "training-b"] }',
    exampleNote: "Two different zones provide separate placements; two repetitions of training-a do not.",
    mistake: "Counting two replicas in one zone as protection against a zone outage.",
    mission: "Place the Relay in eu-west-1 across eu-west-1a and eu-west-1b. A single-zone failure must leave one placement available.",
    fields: [field("region", "string", "The scenario's permitted region is eu-west-1."), field("zones", "strings", "Choose the two independent zones provided by the scenario.")],
    starter: { region: "us-east-1", zones: ["eu-west-1a", "eu-west-1a"] },
    solution: { region: "eu-west-1", zones: ["eu-west-1a", "eu-west-1b"] },
    checks: [check("Data-location requirement met", "Set the scenario's required region, eu-west-1.", equals("region", "eu-west-1")), check("One zone can fail independently", "Use both eu-west-1a and eu-west-1b once each.", (p) => exactSet(p.zones, ["eu-west-1a", "eu-west-1b"]))],
    observations: (p) => [`Distinct placements: ${new Set(p.zones as string[]).size}.`, `After the first zone fails: ${Math.max(0, new Set(p.zones as string[]).size - 1)} independent placement(s) remain.`],
    source: architectureSource,
  },
  {
    id: 3, title: "Choose the compute", minutes: 8,
    objective: "Match the compute service to a Python application's needs.",
    story: "The Citadel's API needs a home. Byte wants application control without maintaining a guest operating system.",
    concepts: [
      { title: "Virtual machines", body: "A virtual machine gives you control over a guest operating system and installed software. That flexibility comes with work: patching the guest, configuring it, and planning capacity." },
      { title: "Managed containers", body: "A container image packages an application and its user-space dependencies. A managed container service can schedule and run those images while the provider operates the underlying hosts. Your team still owns its image, dependencies, permissions, and application." },
      { title: "Functions", body: "Functions are useful for event-driven work and short units of execution. Limits and pricing depend on the provider. Our training platform's functions cannot run this existing container image; its managed-container service can." },
    ],
    example: '{ "compute": "function", "runtime": "python", "replicas": 1 }',
    exampleNote: "An event handler could use a function. The challenge instead supplies an existing long-running API container and requires redundancy.",
    mistake: "Choosing a service by popularity without checking the workload's packaging and operational needs.",
    mission: "Run the existing Python API on managed-container compute. Keep two replicas ready, so losing one process still leaves a running copy.",
    fields: [field("compute", "string", "vm, managed-container, or function; only managed-container meets this scenario."), field("runtime", "string", "Language required by the application."), field("replicas", "number", "Whole number of copies to keep running; this mission budgets two.")],
    starter: { compute: "vm", runtime: "python", replicas: 1 },
    solution: { compute: "managed-container", runtime: "python", replicas: 2 },
    checks: [check("Packaging and host management fit", "Use managed-container for the supplied API image.", equals("compute", "managed-container")), check("Python application supported", "Keep the runtime as python.", equals("runtime", "python")), check("One process can fail", "Keep exactly two replicas for the mission budget.", equals("replicas", 2))],
    observations: (p) => [`Configured compute: ${p.compute}.`, `If one process exits, ${Math.max(0, Number(p.replicas) - 1)} replica(s) remain.`],
    source: architectureSource,
  },
  {
    id: 4, title: "Protect object storage", minutes: 8,
    objective: "Protect uploads and recover from an accidental overwrite.",
    story: "A report was overwritten, and the storage gate is open to everyone. Byte needs access controls and recovery.",
    concepts: [
      { title: "Objects are addressed by keys", body: "Object storage holds data such as uploads, images, and backups. Applications retrieve objects by key rather than treating the service as a relational database. A bucket is a container for those objects." },
      { title: "Three different protections", body: "Blocking public reads limits who can retrieve an object. Encryption at rest protects stored representations. Versioning retains prior versions so an overwrite may be recoverable. Encryption alone does not stop an authorized public download." },
      { title: "Retention has a cost", body: "Older versions consume storage. Lifecycle policies can expire old data according to retention requirements. In this simulation, retain prior versions for 30 days; real provider rules need more detailed configuration." },
    ],
    example: '{ "publicRead": false, "encryption": true, "versioning": true, "retentionDays": 7 }',
    exampleNote: "A seven-day retention window may fit a short-lived dataset. The Citadel's reports require a longer window.",
    mistake: "Turning on encryption while leaving sensitive uploads publicly readable.",
    mission: "Block anonymous reads, enable encryption and versioning, and retain previous report versions for exactly 30 days.",
    fields: [field("publicRead", "boolean", "Whether an anonymous visitor may retrieve reports."), field("encryption", "boolean", "Whether stored objects are encrypted."), field("versioning", "boolean", "Whether previous versions are retained."), field("retentionDays", "number", "Prior-version retention in this simplified model.")],
    starter: { publicRead: true, encryption: true, versioning: false, retentionDays: 0 },
    solution: { publicRead: false, encryption: true, versioning: true, retentionDays: 30 },
    checks: [check("Anonymous read denied", "Set publicRead to false.", equals("publicRead", false)), check("Objects encrypted at rest", "Keep encryption enabled.", equals("encryption", true)), check("Overwrite can be recovered", "Enable versioning and set retentionDays to 30.", (p) => p.versioning === true && p.retentionDays === 30)],
    observations: (p) => [`Anonymous GET: ${p.publicRead ? "allowed — report exposed" : "denied"}.`, `Yesterday's overwritten report: ${p.versioning && Number(p.retentionDays) >= 1 ? "recoverable within retention" : "no retained version"}.`],
    source: architectureSource,
  },
  {
    id: 5, title: "Restore the Foundation Spire", minutes: 12,
    objective: "Combine placement, compute, and data protection into one plan.",
    story: "The first tower is ready for a recovery drill. All its decisions now need to work together.",
    concepts: [
      { title: "A system is a set of dependencies", body: "A redundant application can still fail if all its copies depend on a single unavailable component. Read the complete plan and trace the request from the user to stored data." },
      { title: "Declare the intended state", body: "A declarative plan describes the state you want. A real infrastructure tool compares desired and existing resources before making changes. Our relay plan checks your intended state locally and never creates resources." },
      { title: "Validate more than the happy path", body: "A useful review asks what happens when a zone fails or someone requests a private object. Passing one availability check is not proof that access controls are correct; test each requirement separately." },
    ],
    example: "Review: placement → compute → protected storage → failure drill",
    exampleNote: "Use the same reasoning as lessons 2–4, but check every field in the combined plan.",
    mistake: "Declaring two zones but running only one application replica.",
    mission: "In eu-west-1, place two managed-container replicas across zones eu-west-1a and eu-west-1b. Keep uploads private and versioned. Each replica is placed in one of the two zones by this model.",
    fields: [field("region", "string", "Required region: eu-west-1."), field("zones", "strings", "The two independent zone labels from lesson 2."), field("compute", "string", "The service that runs the supplied container."), field("replicas", "number", "Two copies, distributed across the zones."), field("publicRead", "boolean", "Anonymous upload access."), field("versioning", "boolean", "Retain overwritten uploads.")],
    starter: { region: "eu-west-1", zones: ["eu-west-1a"], compute: "vm", replicas: 1, publicRead: true, versioning: false },
    solution: { region: "eu-west-1", zones: ["eu-west-1a", "eu-west-1b"], compute: "managed-container", replicas: 2, publicRead: false, versioning: true },
    checks: [check("Placement respects the contract", "Use eu-west-1 and both eu-west-1a / eu-west-1b.", (p) => p.region === "eu-west-1" && exactSet(p.zones, ["eu-west-1a", "eu-west-1b"])), check("API survives one lost replica", "Use managed-container with two replicas.", (p) => p.compute === "managed-container" && p.replicas === 2), check("Private data is recoverable", "Disable publicRead and enable versioning.", (p) => p.publicRead === false && p.versioning === true)],
    observations: (p) => [`Zone-loss drill: ${exactSet(p.zones, ["eu-west-1a", "eu-west-1b"]) && p.replicas === 2 ? "one replica remains" : "redundancy requirement not met"}.`, `Untrusted upload request: ${p.publicRead ? "allowed" : "denied"}.`],
    source: architectureSource,
  },
  {
    id: 6, title: "Trace a network request", minutes: 9,
    objective: "Connect the edge, application, and database with a narrow permitted path.",
    story: "The front door works, but database traffic can arrive from anywhere. Byte needs separate network boundaries.",
    concepts: [
      { title: "A public edge, private services", body: "A common web architecture exposes a load balancer or gateway while keeping application and database services private. Being in a private subnet does not by itself define all permissions: routes and firewall rules also matter." },
      { title: "Think in permitted connections", body: "Trace each hop: visitors reach the edge, the edge reaches the application, and the application reaches the database. Database access should be limited to the application identity or its network group, not every source on the internet." },
      { title: "A port identifies the service", body: "A destination port is part of a network connection. Our practice PostgreSQL database listens on 5432. The simulator models the three hops explicitly; actual networks also need correct routing, return traffic, and provider configuration." },
    ],
    example: "visitor → public edge → private application → private database",
    exampleNote: "An allowed path for application traffic must coexist with a denied direct path from an untrusted visitor to the database.",
    mistake: "Making the database public to fix a connectivity problem.",
    mission: "Expose the edge only. Keep application and database private, permit database connections from app only, and use PostgreSQL port 5432.",
    fields: [field("edgePublic", "boolean", "Whether visitors can reach the edge."), field("appPublic", "boolean", "Whether visitors can bypass the edge."), field("databasePublic", "boolean", "Whether visitors can directly reach PostgreSQL."), field("databaseAllowedFrom", "string", "app or internet."), field("databasePort", "number", "The database listener port.")],
    starter: { edgePublic: true, appPublic: true, databasePublic: true, databaseAllowedFrom: "internet", databasePort: 3306 },
    solution: { edgePublic: true, appPublic: false, databasePublic: false, databaseAllowedFrom: "app", databasePort: 5432 },
    checks: [check("Visitors use the edge", "Enable edgePublic; disable appPublic.", (p) => p.edgePublic === true && p.appPublic === false), check("Direct database traffic blocked", "Keep databasePublic false and restrict databaseAllowedFrom to app.", (p) => p.databasePublic === false && p.databaseAllowedFrom === "app"), check("Application reaches PostgreSQL", "Use the app source and the PostgreSQL listener port 5432.", (p) => p.databaseAllowedFrom === "app" && p.databasePort === 5432)],
    observations: (p) => [`Visitor → edge: ${p.edgePublic ? "reachable" : "blocked"}.`, `Application → PostgreSQL: ${p.databaseAllowedFrom === "app" && p.databasePort === 5432 ? "connected" : "connection failed"}.`, `Untrusted visitor → database: ${p.databasePublic && p.databaseAllowedFrom === "internet" ? "exposed" : "blocked"}.`],
    source: architectureSource,
  },
  {
    id: 7, title: "DNS and encrypted traffic", minutes: 8,
    objective: "Give clients a stable address and an encrypted path to the edge.",
    story: "Users remember the Relay's name, but it points to a retired gateway. Fix the name and the connection.",
    concepts: [
      { title: "DNS answers where", body: "DNS lets a name resolve to records clients use to locate a service. Changing a record does not instantly update every client: cached records may remain until their time to live expires." },
      { title: "TLS protects the connection", body: "HTTPS uses TLS to protect traffic and authenticate the server to clients. DNS resolution alone does not supply encryption. The certificate needs to be valid for the requested name and the server must support the connection." },
      { title: "Edge and origin are separate hops", body: "Our model terminates client TLS at relay-edge and forwards traffic to the private API on port 8080. Real deployments must decide how to protect the origin hop too. An incorrect origin port gives an upstream failure even if DNS and TLS succeed." },
    ],
    example: "name lookup → gateway certificate check → origin connection",
    exampleNote: "Check each layer in order: a successful lookup cannot repair an expired certificate or incorrect origin port.",
    mistake: "Treating a successful DNS lookup as proof that the application is reachable.",
    mission: "Point DNS to relay-edge, select https, set certificateValid to true, and forward to the API's port 8080. Certificate validity is a simulated input here.",
    fields: [field("dnsTarget", "string", "The active gateway is relay-edge."), field("protocol", "string", "http or https for visitors."), field("certificateValid", "boolean", "Simulated certificate validity for the requested name."), field("originPort", "number", "The private API listens on 8080.")],
    starter: { dnsTarget: "old-edge", protocol: "http", certificateValid: false, originPort: 80 },
    solution: { dnsTarget: "relay-edge", protocol: "https", certificateValid: true, originPort: 8080 },
    checks: [check("Name reaches the active gateway", "Point dnsTarget to relay-edge.", equals("dnsTarget", "relay-edge")), check("Client connection is protected", "Choose https and use a valid certificate.", (p) => p.protocol === "https" && p.certificateValid === true), check("Edge reaches the API", "Set originPort to 8080.", equals("originPort", 8080))],
    observations: (p) => [`Name lookup: ${p.dnsTarget}.`, `TLS handshake: ${p.protocol === "https" && p.certificateValid ? "accepted" : "not secure or rejected"}.`, `Origin connection: ${p.originPort === 8080 ? "connected" : "wrong listener port"}.`],
    source: architectureSource,
  },
  {
    id: 8, title: "Give a service an identity", minutes: 9,
    objective: "Grant one workload the exact permission it needs.",
    story: "The API only reads assets, but its current identity can delete the entire archive. Reduce its reach.",
    concepts: [
      { title: "Authentication and authorization", body: "Authentication establishes an identity. Authorization decides what that identity may do. A network connection alone should not grant permission to read or change protected data." },
      { title: "Least privilege", body: "Start from the task: which action, on which resource, under which conditions? An asset reader does not need permission to delete data or access unrelated buckets. Broad wildcards make accidental damage harder to contain." },
      { title: "Workload roles", body: "A workload role can provide temporary credentials instead of embedding a long-lived access key in code. The provider still needs a trust relationship that says which workload can assume that role. Our simple plan models only the resulting permission, not a complete provider policy." },
    ],
    example: '{ "credentialMode": "role", "actions": ["object:write"], "resource": "bucket:exports" }',
    exampleNote: "An export writer gets one write permission on its bucket. The Relay asset reader needs a different action and resource.",
    mistake: "Using actions: [\"*\"] because the first request failed.",
    mission: "Use a role. Allow only object:read on bucket:relay-assets. Reads of bucket:private-ledger and object:delete must both be denied.",
    fields: [field("credentialMode", "string", "role or static-key."), field("actions", "strings", "Use the simulation action object:read; no wildcard or delete permission."), field("resource", "string", "Scope the permission to bucket:relay-assets.")],
    starter: { credentialMode: "static-key", actions: ["*"], resource: "*" },
    solution: { credentialMode: "role", actions: ["object:read"], resource: "bucket:relay-assets" },
    checks: [check("Workload uses temporary identity", "Select credentialMode role.", equals("credentialMode", "role")), check("Required read permitted; deletion denied", "Grant object:read only, without duplicates or wildcards.", (p) => exactSet(p.actions, ["object:read"])), check("Unrelated data stays out of reach", "Limit resource to bucket:relay-assets.", equals("resource", "bucket:relay-assets"))],
    observations: (p) => { const actions = p.actions as string[]; return [`Asset read: ${(actions.includes("object:read") || actions.includes("*")) && (p.resource === "bucket:relay-assets" || p.resource === "*") ? "allowed" : "denied"}.`, `Delete request: ${actions.includes("*") || actions.includes("object:delete") ? "allowed — excessive privilege" : "denied"}.`, `Unrelated bucket: ${p.resource === "*" ? "within permission scope" : "outside permission scope"}.`]; },
    source: identitySource,
  },
  {
    id: 9, title: "Handle application secrets", minutes: 8,
    objective: "Reference a credential without placing its value in code or logs.",
    story: "A debug log printed the database password. Byte wants the service to retrieve a secret without exposing it.",
    concepts: [
      { title: "Configuration is not all equally sensitive", body: "A port number is ordinary configuration; a database password is a credential. Treating both as plain text in a repository can spread a secret to clones, build output, and logs." },
      { title: "Reference instead of embedding", body: "A secret manager stores credentials behind access controls and can support rotation. Applications retrieve an authorized value at runtime. A reference names a secret; it is not itself the password. Our secret:// reference is a training convention and retrieves nothing." },
      { title: "A leak needs a response", body: "Removing a secret from the latest source file does not invalidate copies already exposed. A real leak calls for revocation or rotation, review of use, and cleanup of affected systems. Preventing secret logging reduces one common exposure path." },
    ],
    example: '{ "secretRef": "secret://mailer/token", "logSecrets": false }',
    exampleNote: "The reference identifies an entry; no actual credential is included. Use a database reference in the challenge.",
    mistake: "Assuming a secret is safe because its value is hidden in the interface but still printed to logs.",
    mission: "Set source to secret-store and databaseUrlRef to secret://relay/database-url. Disable logSecrets and committedSecrets. Use only the fictional reference, never a real password.",
    fields: [field("source", "string", "secret-store or repository."), field("databaseUrlRef", "string", "Training reference: secret://relay/database-url."), field("logSecrets", "boolean", "Whether the app logs retrieved values."), field("committedSecrets", "boolean", "Whether secret values are stored in source control.")],
    starter: { source: "repository", databaseUrlRef: "inline-demo-password", logSecrets: true, committedSecrets: true },
    solution: { source: "secret-store", databaseUrlRef: "secret://relay/database-url", logSecrets: false, committedSecrets: false },
    checks: [check("Credential referenced, not embedded", "Use secret-store with secret://relay/database-url.", (p) => p.source === "secret-store" && p.databaseUrlRef === "secret://relay/database-url"), check("Secret excluded from logs", "Set logSecrets to false.", equals("logSecrets", false)), check("Secret excluded from the repository", "Set committedSecrets to false.", equals("committedSecrets", false))],
    observations: (p) => [`Configuration source: ${p.source}.`, `Log inspection: ${p.logSecrets ? "secret value would be exposed" : "secret values redacted"}.`, "No credentials are retrieved or transmitted by this simulation."],
    source: identitySource,
  },
  {
    id: 10, title: "Secure the Network Bastion", minutes: 12,
    objective: "Allow a legitimate request while denying two unsafe paths.",
    story: "The security gate opens only when the API works and the untrusted probes fail.",
    concepts: [
      { title: "Use several boundaries", body: "An HTTPS gateway, private database, scoped identity, and secret reference solve different problems. Losing one protection should not silently remove all the others." },
      { title: "Test allowed and denied actions", body: "A completely disconnected system might deny every attack while also denying every user. Verify that the expected application request succeeds, then test direct database access and access to unrelated data." },
      { title: "Read the trace", body: "When a request fails, locate the failing hop before broadening access. A wrong port, missing action, or bad reference needs a precise repair. Opening an entire network or granting a wildcard can hide the original cause." },
    ],
    example: "Expected: client HTTPS allowed; app database access allowed; direct database probe denied.",
    exampleNote: "A healthy service needs both positive and negative test cases.",
    mistake: "Passing the availability test by disabling security boundaries.",
    mission: "Use https at the edge. Keep the database private and allow app traffic only. Give the workload a role with just object:read on bucket:relay-assets, and use secret://relay/database-url for its database credential.",
    fields: [field("protocol", "string", "https protects client traffic in this model."), field("databasePublic", "boolean", "Direct public database access."), field("databaseAllowedFrom", "string", "Only app should reach the database."), field("credentialMode", "string", "role provides temporary identity."), field("actions", "strings", "The asset reader's single required action."), field("resource", "string", "The asset reader's exact bucket."), field("databaseUrlRef", "string", "The database secret reference from lesson 9.")],
    starter: { protocol: "http", databasePublic: true, databaseAllowedFrom: "internet", credentialMode: "static-key", actions: ["object:read", "object:delete"], resource: "*", databaseUrlRef: "missing" },
    solution: { protocol: "https", databasePublic: false, databaseAllowedFrom: "app", credentialMode: "role", actions: ["object:read"], resource: "bucket:relay-assets", databaseUrlRef: "secret://relay/database-url" },
    checks: [check("Client traffic protected", "Set protocol to https.", equals("protocol", "https")), check("Database allows only the application path", "Set databasePublic false and databaseAllowedFrom app.", (p) => p.databasePublic === false && p.databaseAllowedFrom === "app"), check("Asset reader cannot delete or cross buckets", "Use a role, object:read only, and bucket:relay-assets.", (p) => p.credentialMode === "role" && exactSet(p.actions, ["object:read"]) && p.resource === "bucket:relay-assets"), check("Database credential is a reference", "Use secret://relay/database-url.", equals("databaseUrlRef", "secret://relay/database-url"))],
    observations: (p) => [`Client transport: ${p.protocol}.`, `Direct database probe: ${p.databasePublic ? "public endpoint exposed" : "blocked"}.`, `Asset deletion: ${(p.actions as string[]).some((action) => action === "*" || action === "object:delete") ? "permitted" : "denied"}.`],
    source: identitySource,
  },
  {
    id: 11, title: "A container that can serve traffic", minutes: 9,
    objective: "Make a versioned Python container reachable and health-checkable.",
    story: "The process runs, but the gateway cannot connect. Byte sees a mismatch between the listener and service ports.",
    concepts: [
      { title: "Build an identifiable release", body: "A container image packages the application and its dependencies. A mutable label such as latest can refer to different content tomorrow. This exercise uses an explicit version tag; production systems can pin an image digest for immutable content." },
      { title: "Listen where traffic arrives", body: "A process bound only to 127.0.0.1 accepts connections from its own network namespace. Our service expects a listener on 0.0.0.0:8080. The service's target port must match that listener." },
      { title: "Health and privilege", body: "A health endpoint gives the platform a signal for routing or restarting a workload. A successful process start is not the same as a healthy application. Running without root privileges also reduces the authority of the process." },
    ],
    example: "FROM python:3.12-slim\nWORKDIR /app\n# Install dependencies and copy the application here.\nUSER 10001\n# The application must listen on the configured service port.",
    exampleNote: "This is an illustrative Dockerfile fragment, not a runnable image. The challenge evaluates a simplified release plan; it does not build a container.",
    mistake: "Changing the service port while the process still listens on a different port.",
    mission: "Use a relay-api version tag such as relay-api:1.4.2, run without root, bind to 0.0.0.0:8080, set servicePort to 8080, and probe /health. The supplied demo API implements that endpoint.",
    fields: [field("image", "string", "A relay-api:X.Y.Z release tag; latest is not accepted."), field("runAsRoot", "boolean", "Whether the application process uses root."), field("listenHost", "string", "Interface the process binds to."), field("listenPort", "number", "Port used by the process."), field("servicePort", "number", "Port the gateway forwards to."), field("healthPath", "string", "The demo API's health endpoint is /health.")],
    starter: { image: "relay-api:latest", runAsRoot: true, listenHost: "127.0.0.1", listenPort: 8080, servicePort: 80, healthPath: "/status" },
    solution: { image: "relay-api:1.4.2", runAsRoot: false, listenHost: "0.0.0.0", listenPort: 8080, servicePort: 8080, healthPath: "/health" },
    checks: [check("Release is explicitly versioned", "Use a tag such as relay-api:1.4.2.", (p) => pinnedImage(p.image)), check("Process runs without root", "Set runAsRoot to false.", equals("runAsRoot", false)), check("Gateway reaches the listener", "Bind to 0.0.0.0, with both ports set to 8080.", (p) => p.listenHost === "0.0.0.0" && p.listenPort === 8080 && p.servicePort === 8080), check("Health probe reaches the demo endpoint", "Use /health.", equals("healthPath", "/health"))],
    observations: (p) => [`Gateway connection: ${p.listenHost === "0.0.0.0" && p.listenPort === 8080 && p.servicePort === 8080 ? "accepted" : "refused or misrouted"}.`, `Health probe: ${p.healthPath === "/health" ? "known endpoint" : "404 in the demo API"}.`],
    source: containerSource,
  },
  {
    id: 12, title: "Release and roll back", minutes: 9,
    objective: "Limit a bad release's impact and preserve a recovery path.",
    story: "Version 1.4.3 introduces an error. Byte needs to catch it before all visitors are affected.",
    concepts: [
      { title: "Tests before release", body: "A deployment pipeline should check the artifact before exposing it to users. Automated tests catch known failure cases, but they cannot guarantee every production behaviour." },
      { title: "Canaries limit exposure", body: "A canary release sends a small fraction of traffic to a new version. Compare useful signals with the existing version before increasing exposure. A canary without monitoring can still spread a failure." },
      { title: "Plan recovery before deployment", body: "Keep a previous working version and define when to roll back. Application rollback does not automatically undo incompatible database changes, so schema compatibility needs a separate plan. This lesson models only a compatible application release." },
    ],
    example: "test artifact → expose 5% → compare error rate → promote or roll back",
    exampleNote: "For our scenario, any initial canary from 1% through 10% is acceptable.",
    mistake: "Deleting the old version before the new version has passed its live checks.",
    mission: "Run tests, select canary, expose 1–10% initially, retain the previous version, and enable rollbackOnError. The simulator injects a bad release into 1,000 requests.",
    fields: [field("runTests", "boolean", "Validate the artifact before deployment."), field("strategy", "string", "canary or all-at-once."), field("canaryPercent", "number", "Initial traffic share, a whole percentage from 1 to 10."), field("retainPrevious", "boolean", "Keep the known-good release available."), field("rollbackOnError", "boolean", "Restore the previous release when the injected error is detected.")],
    starter: { runTests: false, strategy: "all-at-once", canaryPercent: 100, retainPrevious: false, rollbackOnError: false },
    solution: { runTests: true, strategy: "canary", canaryPercent: 5, retainPrevious: true, rollbackOnError: true },
    checks: [check("Artifact tested first", "Enable runTests.", equals("runTests", true)), check("New release exposure is bounded", "Choose canary and a whole canaryPercent between 1 and 10.", (p) => p.strategy === "canary" && between("canaryPercent", 1, 10)(p)), check("Bad release has a recovery path", "Retain the previous release and enable rollbackOnError.", (p) => p.retainPrevious === true && p.rollbackOnError === true)],
    observations: (p) => [`Initial requests sent to the new release: ${p.strategy === "canary" ? Math.round(Math.max(0, Math.min(100, Number(p.canaryPercent))) * 10) : 1000} / 1,000.`, `After the injected error: ${p.retainPrevious && p.rollbackOnError ? "traffic returns to the previous version" : "automatic recovery unavailable"}.`],
    source: architectureSource,
  },
  {
    id: 13, title: "Detect the incident", minutes: 9,
    objective: "Alert on a customer-visible failure without alerting on the baseline.",
    story: "CPU looks quiet, yet visitors are receiving errors. Byte needs a signal that reflects the user experience.",
    concepts: [
      { title: "Logs and metrics answer different questions", body: "Logs describe individual events; metrics summarize measurements across time. Use metrics to detect a change, then inspect relevant logs to investigate it. Neither should include sensitive values unnecessarily." },
      { title: "Choose a meaningful threshold", body: "An error-rate alert measures failed requests as a percentage. Too low a threshold can alert constantly; too high a threshold misses meaningful incidents. The observation window determines how quickly sustained changes appear." },
      { title: "An alert needs an owner", body: "A dashboard does not notify anyone by itself. Route actionable alerts to a responsible person or rotation, with enough context to begin a diagnosis. In this exercise the normal error rate is 2% and the injected incident is 12%, sustained for five minutes." },
    ],
    example: "baseline: 1% errors → threshold: 4% → sustained incident: 9% → notify owner",
    exampleNote: "The challenge uses a different baseline and incident. Choose a threshold strictly between them.",
    mistake: "Monitoring CPU alone when the user-facing problem is failed requests.",
    mission: "Enable logs, monitor error-rate, choose an integer threshold above 2 and below 12, use a 1–5 minute window, and notify on-call. The alarm fires when the measured error rate exceeds the threshold.",
    fields: [field("logsEnabled", "boolean", "Keep diagnostic events available."), field("metric", "string", "error-rate or cpu."), field("thresholdPercent", "number", "Whole percentage; baseline 2%, incident 12%."), field("windowMinutes", "number", "Whole minutes; detect within five."), field("notify", "string", "on-call or nobody.")],
    starter: { logsEnabled: false, metric: "cpu", thresholdPercent: 95, windowMinutes: 60, notify: "nobody" },
    solution: { logsEnabled: true, metric: "error-rate", thresholdPercent: 5, windowMinutes: 3, notify: "on-call" },
    checks: [check("Signal reflects failed requests", "Enable logs and monitor error-rate.", (p) => p.logsEnabled === true && p.metric === "error-rate"), check("Baseline quiet; incident detected", "Set thresholdPercent to an integer from 3 through 11.", between("thresholdPercent", 3, 11)), check("Detection arrives within five minutes", "Choose an integer windowMinutes from 1 through 5.", between("windowMinutes", 1, 5)), check("Someone receives the alert", "Set notify to on-call.", equals("notify", "on-call"))],
    observations: (p) => [`At 2% baseline: ${p.metric === "error-rate" && 2 > Number(p.thresholdPercent) ? "alarm fires" : "no error-rate alarm"}.`, `At 12% incident: ${p.metric === "error-rate" && 12 > Number(p.thresholdPercent) && Number(p.windowMinutes) <= 5 ? "alarm fires within the drill" : "incident not detected within five minutes"}.`, `Notification destination: ${p.notify}.`],
    source: architectureSource,
  },
  {
    id: 14, title: "Scale within a budget", minutes: 10,
    objective: "Serve the peak load while respecting a fictional capacity budget.",
    story: "Traffic triples during a festival. Byte has enough resources, but only if the scaling limits make sense.",
    concepts: [
      { title: "Capacity is a model", body: "Our simulation assumes one replica serves 100 requests per second. Real capacity depends on code, database work, memory, latency targets, and load tests. You cannot make an actual server faster by changing a number in a planning document." },
      { title: "Minimum and maximum have jobs", body: "The minimum keeps enough replicas ready; the maximum limits growth and potential spending. Here the target is two ready replicas and enough capacity for 300 requests per second. A real autoscaler also needs signals, timing, and startup behaviour." },
      { title: "Budget for the ceiling", body: "This model charges 40 fixed credits plus 25 per replica per simulated billing period. The maximum permitted total is 150 credits. These are fictional units, not provider prices. Actual cloud bills include additional dimensions such as data transfer and storage." },
    ],
    example: "Needed replicas = ceil(requests per second / 100)\nCost = 40 + 25 × active replicas\nAt 200 requests/s: 2 replicas, 90 credits",
    exampleNote: "The simulator clamps demand between your minimum and maximum. Capacity changes instantly in this simplified model.",
    mistake: "Setting an affordable minimum while leaving an unaffordable maximum.",
    mission: "Keep exactly two replicas ready, serve all 300 requests/s at peak, and keep the configured maximum cost within 150 credits. Adjust only minReplicas and maxReplicas; capacity and prices are fixed scenario inputs.",
    fields: [field("minReplicas", "number", "Ready replicas; this mission requires two."), field("maxReplicas", "number", "Scaling ceiling; enough for 300 requests/s and within 150 credits.")],
    starter: { minReplicas: 1, maxReplicas: 2 },
    solution: { minReplicas: 2, maxReplicas: 4 },
    checks: [check("Two replicas remain ready", "Set minReplicas to 2.", equals("minReplicas", 2)), check("Peak traffic is served", "Allow at least three replicas; use whole numbers with maxReplicas >= minReplicas.", (p) => { const s = simulateCapacity(p.minReplicas, p.maxReplicas, 300); return s.valid && s.dropped === 0; }), check("Maximum configured spend is affordable", "40 + 25 × maxReplicas must be <= 150 credits.", (p) => between("maxReplicas", 1, 20)(p) && 40 + 25 * Number(p.maxReplicas) <= 150)],
    observations: (p) => [60, 300].map((demand) => { const s = simulateCapacity(p.minReplicas, p.maxReplicas, demand); return s.valid ? `${demand} requests/s → ${s.replicas} replicas, ${s.served} served, ${s.dropped} dropped, ${s.credits} fictional credits.` : "Scaling bounds are invalid. Use positive whole numbers and maxReplicas >= minReplicas."; }),
    source: architectureSource,
  },
  {
    id: 15, title: "Bring the Cloud Citadel online", minutes: 20,
    objective: "Design a Python API with private PostgreSQL, controlled releases, monitoring, and bounded capacity.",
    story: "The Citadel is ready. Byte will inject a zone outage, traffic spike, and broken release before accepting your final plan.",
    concepts: [
      { title: "Connect the existing tracks", body: "The demo application is a Python API backed by PostgreSQL. Python implements request handling and SQL stores records. Your cloud plan gives that application a reachable, observable, and recoverable operating environment." },
      { title: "Meet a concrete service contract", body: "The scenario requires eu-west-1, two independent zones, a private database, and HTTPS. Baseline load is 100 requests/s; peak is 300. One zone may fail during baseline load. The scheduler places replicas evenly across the configured zones; the drill deliberately does not combine the peak and zone failure." },
      { title: "Know what passing means", body: "Passing establishes that this simplified design satisfies the scenario checks. It does not deploy a Python process, execute SQL, provision infrastructure, verify a real certificate, or certify production readiness. A real deployment needs provider-specific plans, measured load tests, account permissions, and recovery exercises." },
    ],
    example: "Python API sample:\nGET /health → 200\nGET /relays → query PostgreSQL → JSON response\n\nNetwork intent:\nclient → HTTPS edge → API replicas → private PostgreSQL",
    exampleNote: "These are the supplied application's behaviours. Your task is its operating plan, not rewriting its Python or SQL.",
    mistake: "Optimizing for the peak while forgetting recovery, access controls, or the maximum bill.",
    mission: "Combine the earlier repairs. Use a versioned managed Python container on port 8080 with /health, eu-west-1a and eu-west-1b, two ready replicas, and enough peak capacity within 150 fictional credits. Protect the private database with app-only access and the database secret reference. Scope the workload role to asset reads. Enable error alerts and a tested canary release with rollback.",
    fields: [field("region", "string", "Required: eu-west-1."), field("zones", "strings", "eu-west-1a and eu-west-1b, with replicas spread evenly."), field("compute", "string", "managed-container for the supplied Python API."), field("runtime", "string", "python."), field("image", "string", "A relay-api:X.Y.Z release tag."), field("runAsRoot", "boolean", "Application privilege."), field("servicePort", "number", "The supplied API listens on 8080."), field("healthPath", "string", "The supplied endpoint is /health."), field("protocol", "string", "Client transport: https."), field("databasePublic", "boolean", "Direct internet access to PostgreSQL."), field("databaseAllowedFrom", "string", "Only app should reach PostgreSQL."), field("databaseUrlRef", "string", "secret://relay/database-url."), field("credentialMode", "string", "Use role for the asset reader."), field("actions", "strings", "Only object:read."), field("resource", "string", "Only bucket:relay-assets."), field("minReplicas", "number", "Two ready replicas."), field("maxReplicas", "number", "Serve 300 requests/s at 100 per replica; 40 fixed + 25 per replica <= 150 credits."), field("logsEnabled", "boolean", "Diagnostic logging."), field("thresholdPercent", "number", "Error alarm threshold: above 2%, below 12%."), field("notify", "string", "on-call."), field("runTests", "boolean", "Pre-release artifact checks."), field("strategy", "string", "canary."), field("canaryPercent", "number", "Initial traffic percentage: 1–10."), field("retainPrevious", "boolean", "Keep the previous version."), field("rollbackOnError", "boolean", "Restore the previous version on failure.")],
    starter: { region: "eu-west-1", zones: ["eu-west-1a"], compute: "managed-container", runtime: "python", image: "relay-api:latest", runAsRoot: true, servicePort: 80, healthPath: "/status", protocol: "http", databasePublic: true, databaseAllowedFrom: "internet", databaseUrlRef: "missing", credentialMode: "static-key", actions: ["*"], resource: "*", minReplicas: 1, maxReplicas: 2, logsEnabled: false, thresholdPercent: 95, notify: "nobody", runTests: false, strategy: "all-at-once", canaryPercent: 100, retainPrevious: false, rollbackOnError: false },
    solution: { region: "eu-west-1", zones: ["eu-west-1a", "eu-west-1b"], compute: "managed-container", runtime: "python", image: "relay-api:1.4.2", runAsRoot: false, servicePort: 8080, healthPath: "/health", protocol: "https", databasePublic: false, databaseAllowedFrom: "app", databaseUrlRef: "secret://relay/database-url", credentialMode: "role", actions: ["object:read"], resource: "bucket:relay-assets", minReplicas: 2, maxReplicas: 4, logsEnabled: true, thresholdPercent: 5, notify: "on-call", runTests: true, strategy: "canary", canaryPercent: 5, retainPrevious: true, rollbackOnError: true },
    checks: [
      check("Region and zone-outage contract met", "Choose eu-west-1, both independent zones, and two ready replicas.", (p) => p.region === "eu-west-1" && exactSet(p.zones, ["eu-west-1a", "eu-west-1b"]) && p.minReplicas === 2),
      check("Python release is identifiable and unprivileged", "Use managed-container, python, a relay-api:X.Y.Z tag, and runAsRoot false.", (p) => p.compute === "managed-container" && p.runtime === "python" && pinnedImage(p.image) && p.runAsRoot === false),
      check("User request reaches a healthy API", "Use https, servicePort 8080, and healthPath /health.", (p) => p.protocol === "https" && p.servicePort === 8080 && p.healthPath === "/health"),
      check("Application data path is private", "Keep databasePublic false, permit app only, and use the database secret reference.", (p) => p.databasePublic === false && p.databaseAllowedFrom === "app" && p.databaseUrlRef === "secret://relay/database-url"),
      check("Untrusted asset actions denied", "Use role with only object:read on bucket:relay-assets.", (p) => p.credentialMode === "role" && exactSet(p.actions, ["object:read"]) && p.resource === "bucket:relay-assets"),
      check("Traffic spike fits capacity and budget", "Use two minimum replicas and a maximum of three or four. Fixed cost is 40 + 25 per replica.", (p) => { const s = simulateCapacity(p.minReplicas, p.maxReplicas, 300); return p.minReplicas === 2 && s.valid && s.dropped === 0 && 40 + Number(p.maxReplicas) * 25 <= 150; }),
      check("Customer errors reach an owner", "Enable logs, choose a whole threshold from 3 to 11, and notify on-call. This project uses a fixed five-minute error-rate window.", (p) => p.logsEnabled === true && between("thresholdPercent", 3, 11)(p) && p.notify === "on-call"),
      check("Broken release can be rolled back", "Run tests, use a 1–10% canary, retain the previous version, and enable rollbackOnError.", (p) => p.runTests === true && p.strategy === "canary" && between("canaryPercent", 1, 10)(p) && p.retainPrevious === true && p.rollbackOnError === true),
    ],
    observations: (p) => {
      const peak = simulateCapacity(p.minReplicas, p.maxReplicas, 300);
      return [
        `Zone-loss drill at 100 requests/s: ${p.minReplicas === 2 && exactSet(p.zones, ["eu-west-1a", "eu-west-1b"]) ? "one surviving replica serves baseline load" : "baseline resilience unproven"}.`,
        peak.valid ? `Peak drill: ${peak.served}/300 requests/s served by ${peak.replicas} replicas; ${peak.credits} fictional credits.` : "Peak drill: invalid scaling limits.",
        `Bad-release drill: ${p.strategy === "canary" && p.retainPrevious && p.rollbackOnError ? "previous version restored after detection" : "recovery path incomplete"}.`,
        `Untrusted database probe: ${p.databasePublic ? "public database exposed" : "direct public access blocked"}.`,
        "These drills model separate incidents, with instant scaling and a fixed five-minute alert window. No real infrastructure was created.",
      ];
    },
    source: architectureSource,
  },
];

export const getCloudLesson = (id: number) => CLOUD_LESSONS.find((lesson) => lesson.id === id);
