import { between, check, exactSet, field, type CloudCheck, type CloudLesson, type CloudPlan } from "./model";

const architectureSource = { label: "AWS Well-Architected Framework", url: "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html" };
const kubernetesSource = { label: "Kubernetes: Deployments", url: "https://kubernetes.io/docs/concepts/workloads/controllers/deployment/" };
const sreSource = { label: "Google SRE Workbook", url: "https://sre.google/workbook/table-of-contents/" };
const nistSource = { label: "NIST SP 800-207: Zero Trust Architecture", url: "https://csrc.nist.gov/pubs/sp/800/207/final" };
const finopsSource = { label: "FinOps Framework", url: "https://www.finops.org/framework/" };

type LessonSeed = {
  id: number; title: string; minutes: number; objective: string; story: string;
  concepts: CloudLesson["concepts"]; example: string; exampleNote: string; mistake: string; mission: string;
  starter: CloudPlan; solution: CloudPlan; help: Record<string, string>; checks: CloudCheck[];
  source: CloudLesson["source"];
};

const lesson = (seed: LessonSeed): CloudLesson => ({
  ...seed,
  fields: Object.entries(seed.solution).map(([key, value]) => field(key, Array.isArray(value) ? "strings" : typeof value as "string" | "number" | "boolean", seed.help[key] ?? "Required scenario value.")),
  observations: (plan) => seed.checks.map((item) => item.name + ": " + (item.test(plan) ? "ready" : "needs repair") + "."),
});

const ordered = (value: unknown, expected: string[]) => Array.isArray(value) && value.length === expected.length && value.every((item, index) => item === expected[index]);

export const BEGINNER_CLOUD_EXTENSION: CloudLesson[] = [
  lesson({
    id: 16, title: "Cache static content at the edge", minutes: 9,
    objective: "Reduce origin load without caching personalized API responses.",
    story: "The Citadel map loads slowly for distant learners. Byte can move safe files closer to users, but account data must still reach the application.",
    concepts: [
      { title: "Cache only reusable responses", body: "Static images, styles, and versioned scripts can usually be shared across users, while personalized or rapidly changing API responses may expose stale or private data when cached with the same policy." },
      { title: "Freshness is an explicit tradeoff", body: "A cache lifetime reduces repeated origin work but delays visibility of changed content. Versioned asset names and deliberate invalidation provide a predictable way to publish urgent corrections." },
      { title: "Protect the origin", body: "An edge cache should be the public entry point rather than an optional shortcut around a public origin. Restrict direct origin access so clients cannot bypass filtering, encryption, or request controls." },
    ],
    example: "browser → edge cache → static asset\ncache miss → private origin → store response for 3,600 seconds",
    exampleNote: "The lesson models cache intent only. Real cacheability also depends on response headers, query strings, cookies, and provider-specific rules.",
    mistake: "Caching every GET response, including user-specific account data, because it improves the hit ratio.",
    mission: "Cache static assets for one hour, never cache the account API, invalidate changed assets during release, and keep the origin private.",
    starter: { cacheStatic: false, cacheAccountApi: true, ttlSeconds: 30, invalidateOnDeploy: false, originPrivate: false },
    solution: { cacheStatic: true, cacheAccountApi: false, ttlSeconds: 3600, invalidateOnDeploy: true, originPrivate: true },
    help: { cacheStatic: "Cache reusable static assets.", cacheAccountApi: "Whether personalized account responses are cached.", ttlSeconds: "Static response lifetime in seconds.", invalidateOnDeploy: "Remove changed cached assets during release.", originPrivate: "Only the edge can reach the origin." },
    checks: [
      check("Only reusable content is cached", "Enable static caching and disable account API caching.", (p) => p.cacheStatic === true && p.cacheAccountApi === false),
      check("Freshness is controlled", "Use a TTL from 300 to 86,400 seconds and invalidate on deploy.", (p) => between("ttlSeconds", 300, 86_400)(p) && p.invalidateOnDeploy === true),
      check("Clients cannot bypass the edge", "Keep the origin private.", (p) => p.originPrivate === true),
    ], source: architectureSource,
  }),
  lesson({
    id: 17, title: "Queue slow work", minutes: 10,
    objective: "Move slow background work off the request path and contain repeated failures.",
    story: "Image processing now keeps web requests open until they time out. Byte introduces a queue so the API can respond while workers finish the job safely.",
    concepts: [
      { title: "Queues decouple different speeds", body: "The API can validate a request, enqueue a durable message, and return quickly while independently scaled workers process the backlog. Queue depth then becomes a visible measure of pending work." },
      { title: "Delivery can repeat", body: "Many managed queues use at-least-once delivery, so a worker may receive the same message again after a timeout or crash. An idempotency key lets repeated processing preserve one intended outcome." },
      { title: "Poison messages need a boundary", body: "A message that always fails should not retry forever and consume worker capacity. A dead-letter queue and bounded receive count isolate it for investigation without blocking healthy jobs." },
    ],
    example: "POST /images → enqueue job + return 202\nworker → claim message → write result once → acknowledge",
    exampleNote: "The visibility timeout must exceed normal processing time or be extended safely while a worker remains healthy.",
    mistake: "Assuming a queued message is delivered exactly once and performing an irreversible action on every receive.",
    mission: "Enqueue background work, run two workers, allow 120 seconds for processing, deduplicate jobs, and move a message to a dead-letter queue after five receives.",
    starter: { requestMode: "synchronous", workerCount: 1, visibilityTimeoutSeconds: 15, idempotencyKey: false, deadLetterQueue: false, maxReceiveCount: 100 },
    solution: { requestMode: "enqueue", workerCount: 2, visibilityTimeoutSeconds: 120, idempotencyKey: true, deadLetterQueue: true, maxReceiveCount: 5 },
    help: { requestMode: "How the API hands off slow work.", workerCount: "Independent consumers.", visibilityTimeoutSeconds: "Time a claimed message remains hidden.", idempotencyKey: "Stable key for duplicate-safe processing.", deadLetterQueue: "Isolation queue for repeated failures.", maxReceiveCount: "Receives allowed before isolation." },
    checks: [
      check("The request path stays responsive", "Use enqueue mode with at least two workers.", (p) => p.requestMode === "enqueue" && between("workerCount", 2, 10)(p)),
      check("Duplicate delivery is safe", "Enable an idempotency key and allow 60–300 seconds for processing.", (p) => p.idempotencyKey === true && between("visibilityTimeoutSeconds", 60, 300)(p)),
      check("Repeated failures are isolated", "Enable the dead-letter queue after 3–5 receives.", (p) => p.deadLetterQueue === true && between("maxReceiveCount", 3, 5)(p)),
    ], source: architectureSource,
  }),
  lesson({
    id: 18, title: "Choose a managed database shape", minutes: 10,
    objective: "Configure a managed relational database for private, recoverable application data.",
    story: "The Relay records have outgrown a single machine. Byte needs a database plan that survives routine failures without exposing its listener to the internet.",
    concepts: [
      { title: "Managed does not mean automatic safety", body: "A provider may operate database hosts and replacement processes, while the application team still chooses access, availability, retention, encryption, credentials, and tested recovery behavior." },
      { title: "Availability and backup solve different failures", body: "A standby can reduce interruption after infrastructure failure, but it may faithfully replicate an accidental deletion. Point-in-time backups address a separate recovery need and require restore tests." },
      { title: "Applications need narrow database access", body: "Keep the listener on a private route, use an application workload identity or rotated secret, encrypt stored data, and grant only the database privileges required by the service." },
    ],
    example: "private app → managed PostgreSQL primary + standby\nbackup log → point-in-time restore environment",
    exampleNote: "Multi-zone service improves availability but does not remove the need to define and verify a data recovery objective.",
    mistake: "Treating a standby replica as a backup that can undo accidental writes or deletions.",
    mission: "Use private managed PostgreSQL with a multi-zone standby, encryption, application identity, and fourteen days of tested backups.",
    starter: { engine: "local-file", publicAccess: true, multiZone: false, backupsEnabled: false, retentionDays: 1, encryption: false, applicationIdentity: false },
    solution: { engine: "postgresql", publicAccess: false, multiZone: true, backupsEnabled: true, retentionDays: 14, encryption: true, applicationIdentity: true },
    help: { engine: "Managed relational engine.", publicAccess: "Whether the database accepts an internet route.", multiZone: "Standby in another failure zone.", backupsEnabled: "Point-in-time backup stream.", retentionDays: "Recoverable history.", encryption: "Encrypt stored data.", applicationIdentity: "Narrow application credential or identity." },
    checks: [
      check("The database matches the application", "Choose PostgreSQL and keep public access disabled.", (p) => p.engine === "postgresql" && p.publicAccess === false),
      check("Infrastructure failure has a standby", "Enable multi-zone operation and encryption.", (p) => p.multiZone === true && p.encryption === true),
      check("Data recovery is retained", "Enable backups for 7–35 days and use application identity.", (p) => p.backupsEnabled === true && between("retentionDays", 7, 35)(p) && p.applicationIdentity === true),
    ], source: architectureSource,
  }),
  lesson({
    id: 19, title: "Tag and budget a service", minutes: 9,
    objective: "Assign cloud spend to an owner and detect budget risk before the invoice closes.",
    story: "Citadel credits are rising, but nobody can tell which service or environment caused the change. Byte adds ownership metadata and early warning signals.",
    concepts: [
      { title: "Allocation creates accountability", body: "Consistent owner, service, and environment tags connect shared billing records to the teams and systems that can explain or change them. Missing allocation should be visible rather than silently grouped." },
      { title: "Budgets are signals, not switches", body: "A budget alert gives an owner time to investigate demand, waste, or a configuration mistake. Automatically stopping a production service at a spending threshold can turn a cost issue into an outage." },
      { title: "Anomalies complement thresholds", body: "A fixed monthly limit catches expected overspend, while anomaly detection can identify an unusual change early even when total cost remains below the final budget." },
    ],
    example: "cost record + owner/service/environment tags → service view → 80% alert + anomaly review",
    exampleNote: "The lesson uses fictional credits. Provider bills contain service-specific meters, discounts, taxes, commitments, and transfer charges.",
    mistake: "Setting a budget without an alert recipient, allocation tags, or an investigation playbook.",
    mission: "Allocate the service by owner, service, and environment; set a 500-credit monthly budget; alert at 80%; detect anomalies; and assign the platform team.",
    starter: { allocationTags: ["name"], monthlyBudgetCredits: 0, alertAtPercent: 100, anomalyDetection: false, reviewOwner: "nobody" },
    solution: { allocationTags: ["owner", "service", "environment"], monthlyBudgetCredits: 500, alertAtPercent: 80, anomalyDetection: true, reviewOwner: "platform-team" },
    help: { allocationTags: "Required cost dimensions.", monthlyBudgetCredits: "Fictional monthly service limit.", alertAtPercent: "Early warning percentage.", anomalyDetection: "Detect unusual spending changes.", reviewOwner: "Team responsible for investigation." },
    checks: [
      check("Spend has accountable dimensions", "Use owner, service, and environment exactly once.", (p) => exactSet(p.allocationTags, ["owner", "service", "environment"])),
      check("The budget warns early", "Use a positive budget and alert from 50% through 90%.", (p) => typeof p.monthlyBudgetCredits === "number" && p.monthlyBudgetCredits > 0 && between("alertAtPercent", 50, 90)(p)),
      check("Unexpected spend reaches an owner", "Enable anomalies and assign platform-team.", (p) => p.anomalyDetection === true && p.reviewOwner === "platform-team"),
    ], source: finopsSource,
  }),
  lesson({
    id: 20, title: "Set recovery objectives", minutes: 10,
    objective: "Translate service needs into measurable recovery-time and data-loss targets.",
    story: "A backup exists, but the team cannot say how much data could be lost or how quickly the Relay must return. Byte turns those expectations into a drill.",
    concepts: [
      { title: "RPO limits acceptable data loss", body: "The recovery point objective describes how far back restored data may be. A fifteen-minute RPO requires backup or replication behavior capable of producing a usable point no older than fifteen minutes." },
      { title: "RTO limits acceptable interruption", body: "The recovery time objective covers detection, decisions, infrastructure, restoration, validation, and traffic return. It is an end-to-end business target rather than only a database restore duration." },
      { title: "A restore test creates evidence", body: "Backup-success messages do not prove that data is complete or the service can use it. Scheduled drills should restore into isolation, validate records, measure results, and update an owned runbook." },
    ],
    example: "incident declared → select recovery point ≤15 min old → restore + validate → serve traffic within 60 min",
    exampleNote: "Targets should come from business impact and dependency limits; choosing aggressive numbers without funding the design creates false confidence.",
    mistake: "Claiming a one-hour RTO after measuring only the storage restore and excluding detection, validation, and traffic switching.",
    mission: "Set a fifteen-minute RPO and sixty-minute RTO, map dependencies, assign on-call ownership, and verify a restore every thirty days.",
    starter: { rpoMinutes: 1440, rtoMinutes: 480, dependencyMap: false, runbookOwner: "unassigned", restoreTested: false, restoreFrequencyDays: 365 },
    solution: { rpoMinutes: 15, rtoMinutes: 60, dependencyMap: true, runbookOwner: "on-call", restoreTested: true, restoreFrequencyDays: 30 },
    help: { rpoMinutes: "Maximum recoverable data gap.", rtoMinutes: "Maximum end-to-end interruption.", dependencyMap: "Critical dependencies are included.", runbookOwner: "Recovery decision owner.", restoreTested: "A restore was validated.", restoreFrequencyDays: "Days between recovery drills." },
    checks: [
      check("Data loss meets the service target", "Use a positive RPO no greater than 15 minutes.", (p) => typeof p.rpoMinutes === "number" && p.rpoMinutes > 0 && p.rpoMinutes <= 15),
      check("End-to-end recovery is bounded", "Use a positive RTO no greater than 60 minutes and map dependencies.", (p) => typeof p.rtoMinutes === "number" && p.rtoMinutes > 0 && p.rtoMinutes <= 60 && p.dependencyMap === true),
      check("Recovery is exercised and owned", "Test at least every 30 days and assign on-call.", (p) => p.restoreTested === true && between("restoreFrequencyDays", 1, 30)(p) && p.runbookOwner === "on-call"),
    ], source: sreSource,
  }),
  lesson({
    id: 21, title: "Capstone: Operate the Cloud Citadel", minutes: 24,
    objective: "Combine performance, asynchronous work, managed data, cost ownership, and tested recovery into an operable service.",
    story: "The Citadel is online, but the final operations review injects distant traffic, a poisoned job, a database host failure, a spending anomaly, and accidental data loss.",
    concepts: [
      { title: "Production paths have different jobs", body: "Static delivery, interactive API requests, background jobs, and durable data should not share one undifferentiated path. Each path needs a clear boundary, capacity signal, and failure response." },
      { title: "Operability joins technical and ownership controls", body: "A service is easier to operate when alarms, queues, backups, and cost records lead to named owners and explicit decisions. Unowned evidence rarely produces timely recovery or improvement." },
      { title: "Resilience must be demonstrated", body: "Multi-zone placement and backups describe intent, but scenario evidence must show private access, duplicate-safe job handling, cost visibility, and a restore that meets declared recovery objectives." },
    ],
    example: "edge cache → private API → durable queue → idempotent workers → private PostgreSQL\ntelemetry + cost allocation + restore drills → on-call evidence",
    exampleNote: "This capstone validates a fictional operating model. It does not benchmark, provision, bill, or fail over any real provider resources.",
    mistake: "Adding redundant services without defining the request boundaries, owner, recovery targets, or evidence that proves the design works.",
    mission: "Design the final operating plan: safe edge caching, duplicate-safe queued work, private multi-zone PostgreSQL, accountable cost controls, and a tested 15-minute RPO/60-minute RTO.",
    starter: { cacheStatic: false, cacheAccountApi: true, originPrivate: false, requestMode: "synchronous", idempotencyKey: false, deadLetterQueue: false, databasePublic: true, databaseMultiZone: false, backupsEnabled: false, allocationTags: ["name"], budgetAlertPercent: 100, anomalyDetection: false, rpoMinutes: 1440, rtoMinutes: 480, restoreTested: false, operationsOwner: "unassigned" },
    solution: { cacheStatic: true, cacheAccountApi: false, originPrivate: true, requestMode: "enqueue", idempotencyKey: true, deadLetterQueue: true, databasePublic: false, databaseMultiZone: true, backupsEnabled: true, allocationTags: ["owner", "service", "environment"], budgetAlertPercent: 80, anomalyDetection: true, rpoMinutes: 15, rtoMinutes: 60, restoreTested: true, operationsOwner: "on-call" },
    help: { cacheStatic: "Cache reusable assets.", cacheAccountApi: "Cache personalized API responses.", originPrivate: "Restrict direct origin access.", requestMode: "Background-work handoff.", idempotencyKey: "Duplicate-safe job key.", deadLetterQueue: "Repeated-failure isolation.", databasePublic: "Internet database route.", databaseMultiZone: "Standby failure zone.", backupsEnabled: "Point-in-time recovery.", allocationTags: "Cost ownership dimensions.", budgetAlertPercent: "Early budget warning.", anomalyDetection: "Unexpected-spend signal.", rpoMinutes: "Maximum data gap.", rtoMinutes: "Maximum interruption.", restoreTested: "Recovery evidence exists.", operationsOwner: "Named service owner." },
    checks: [
      check("Edge delivery protects dynamic data and origin", "Cache static content only and keep the origin private.", (p) => p.cacheStatic === true && p.cacheAccountApi === false && p.originPrivate === true),
      check("Background jobs tolerate failure", "Enqueue work with idempotency and a dead-letter queue.", (p) => p.requestMode === "enqueue" && p.idempotencyKey === true && p.deadLetterQueue === true),
      check("Managed data stays available and recoverable", "Keep the database private, multi-zone, and backed up.", (p) => p.databasePublic === false && p.databaseMultiZone === true && p.backupsEnabled === true),
      check("Cost risk is visible and accountable", "Use all allocation tags, an early alert, anomaly detection, and on-call ownership.", (p) => exactSet(p.allocationTags, ["owner", "service", "environment"]) && between("budgetAlertPercent", 50, 90)(p) && p.anomalyDetection === true && p.operationsOwner === "on-call"),
      check("Recovery objectives are proven", "Use RPO ≤15, RTO ≤60, and a tested restore.", (p) => typeof p.rpoMinutes === "number" && p.rpoMinutes > 0 && p.rpoMinutes <= 15 && typeof p.rtoMinutes === "number" && p.rtoMinutes > 0 && p.rtoMinutes <= 60 && p.restoreTested === true),
    ], source: architectureSource,
  }),
];

export const INTERMEDIATE_CLOUD_EXTENSION: CloudLesson[] = [
  lesson({
    id: 16, title: "Detect configuration drift", minutes: 11,
    objective: "Find and repair differences between reviewed infrastructure intent and deployed resources.",
    story: "An emergency console edit fixed yesterday’s outage but never reached the repository. Byte must expose the hidden change before the next deployment reverses it.",
    concepts: [
      { title: "Drift is a difference in authority", body: "Configuration drift appears when the deployed system no longer matches its reviewed declaration. The difference may come from manual edits, failed automation, provider defaults, or an out-of-band incident repair." },
      { title: "Detection should be routine", body: "Scheduled read-only plans can compare declared and observed state before a release. Retained results give owners evidence to classify the change instead of discovering it during an unrelated deployment." },
      { title: "Repair follows risk", body: "Low-risk drift can be reconciled automatically when the desired declaration is trusted, while destructive or security-sensitive changes need review, ownership, and an executable recovery path." },
    ],
    example: "reviewed Git revision → scheduled plan → classify drift → reconcile safe change or request approval",
    exampleNote: "A clean drift scan proves agreement at one moment; continuous controls are still needed because deployed state can change afterward.",
    mistake: "Automatically reverting every manual change without first checking whether responders made it to contain an active incident.",
    mission: "Make Git authoritative, scan at least daily, block routine console changes, auto-repair only low-risk drift, and require approval for destructive reconciliation with retained evidence.",
    starter: { desiredSource: "console", driftScanHours: 168, consoleChangesBlocked: false, autoRepairLowRisk: false, destructiveApproval: false, evidenceRetained: false },
    solution: { desiredSource: "git", driftScanHours: 24, consoleChangesBlocked: true, autoRepairLowRisk: true, destructiveApproval: true, evidenceRetained: true },
    help: { desiredSource: "Authoritative infrastructure declaration.", driftScanHours: "Maximum time between comparisons.", consoleChangesBlocked: "Routine manual mutation control.", autoRepairLowRisk: "Reconcile bounded safe differences.", destructiveApproval: "Review disruptive repairs.", evidenceRetained: "Store scan and decision records." },
    checks: [
      check("Reviewed intent is authoritative", "Use Git and block routine console changes.", (p) => p.desiredSource === "git" && p.consoleChangesBlocked === true),
      check("Drift is found promptly", "Scan every 1–24 hours and retain evidence.", (p) => between("driftScanHours", 1, 24)(p) && p.evidenceRetained === true),
      check("Repair matches the blast radius", "Auto-repair low risk but require approval for destructive changes.", (p) => p.autoRepairLowRisk === true && p.destructiveApproval === true),
    ], source: architectureSource,
  }),
  lesson({
    id: 17, title: "Reconcile deployments with GitOps", minutes: 11,
    objective: "Use a pull-based reconciler to converge runtime state on a verified repository revision.",
    story: "Different release scripts leave clusters in different states. Byte gives each environment one declared revision and a controller that reports whether reality converged.",
    concepts: [
      { title: "Desired state is versioned", body: "A deployment declaration in version control provides a reviewable history and stable revision for each environment. Signing or otherwise verifying the revision strengthens the link between approval and runtime state." },
      { title: "Reconciliation is continuous", body: "A pull-based controller compares the desired revision with the cluster, applies allowed changes, and reports health. This turns deployment from an unobserved command into an ongoing convergence loop." },
      { title: "Deletion and secrets stay deliberate", body: "Pruning prevents abandoned resources from accumulating, but it needs review and rollback protection. Secret values should remain outside plain Git while encrypted references preserve declarative intent." },
    ],
    example: "signed commit → environment branch → pull reconciler → health gate → converged revision",
    exampleNote: "GitOps does not make an unsafe declaration safe; policy, review, permissions, and runtime verification still guard what the controller may apply.",
    mistake: "Giving the reconciler cluster-wide privileges and treating any repository commit as automatically trustworthy.",
    mission: "Reconcile from a signed commit in pull mode, gate on health, prune orphaned resources, retain a rollback revision, and keep secrets as encrypted references.",
    starter: { reconciliationMode: "push-script", sourceRevision: "latest", healthGated: false, pruneOrphans: false, rollbackRevision: false, secretMode: "plain-git" },
    solution: { reconciliationMode: "pull", sourceRevision: "signed-commit", healthGated: true, pruneOrphans: true, rollbackRevision: true, secretMode: "encrypted-reference" },
    help: { reconciliationMode: "How runtime receives desired state.", sourceRevision: "Verified release declaration.", healthGated: "Convergence includes service health.", pruneOrphans: "Remove resources no longer declared.", rollbackRevision: "Known previous desired state.", secretMode: "How declarations refer to secret values." },
    checks: [
      check("Runtime pulls verified intent", "Use pull mode and a signed commit.", (p) => p.reconciliationMode === "pull" && p.sourceRevision === "signed-commit"),
      check("Convergence includes health and cleanup", "Enable health gating and orphan pruning.", (p) => p.healthGated === true && p.pruneOrphans === true),
      check("Recovery and secrets remain controlled", "Retain a rollback revision and use encrypted-reference.", (p) => p.rollbackRevision === true && p.secretMode === "encrypted-reference"),
    ], source: kubernetesSource,
  }),
  lesson({
    id: 18, title: "Autoscale from service demand", minutes: 12,
    objective: "Scale workers from backlog while preventing unstable capacity changes.",
    story: "CPU stays low while the Relay queue grows for twenty minutes. Byte replaces the misleading signal with demand that reflects unfinished customer work.",
    concepts: [
      { title: "Choose a signal tied to work", body: "Worker CPU can be low while tasks wait on dependencies, so queue depth or message age may represent user delay better. The scaling target should connect backlog to measured worker throughput." },
      { title: "Bounds protect reliability and cost", body: "Minimum capacity absorbs ordinary demand and keeps the service warm, while a tested maximum prevents an uncontrolled bill or downstream overload. Quotas and dependency limits belong in the model." },
      { title: "Asymmetric timing reduces oscillation", body: "Fast scale-up can address growing demand, but scale-down should wait long enough to observe drained work and avoid repeatedly adding and removing capacity around one threshold." },
    ],
    example: "desired workers = ceil(queue depth ÷ 20) → clamp between 2 and 12 → scale up fast, scale down slowly",
    exampleNote: "The target is valid only after a load test measures throughput and confirms that databases or APIs can support the resulting concurrency.",
    mistake: "Raising worker limits until the queue disappears without checking whether the database becomes the new bottleneck.",
    mission: "Scale on queue depth at twenty messages per worker, keep two to twelve workers, scale up within sixty seconds, delay scale-down five minutes, and require a load test.",
    starter: { scalingSignal: "cpu", targetPerWorker: 100, minWorkers: 1, maxWorkers: 50, scaleUpSeconds: 600, scaleDownSeconds: 10, loadTested: false },
    solution: { scalingSignal: "queue-depth", targetPerWorker: 20, minWorkers: 2, maxWorkers: 12, scaleUpSeconds: 60, scaleDownSeconds: 300, loadTested: true },
    help: { scalingSignal: "Demand measure for background work.", targetPerWorker: "Queued messages assigned per worker.", minWorkers: "Warm lower bound.", maxWorkers: "Tested upper bound.", scaleUpSeconds: "Maximum response delay to growth.", scaleDownSeconds: "Stabilization before removal.", loadTested: "Capacity and dependencies were measured." },
    checks: [
      check("Scaling follows unfinished work", "Use queue-depth with a target from 10–30 messages.", (p) => p.scalingSignal === "queue-depth" && between("targetPerWorker", 10, 30)(p)),
      check("Capacity stays inside tested bounds", "Use at least two and at most twelve workers with max above min.", (p) => between("minWorkers", 2, 4)(p) && between("maxWorkers", 6, 12)(p) && Number(p.maxWorkers) > Number(p.minWorkers) && p.loadTested === true),
      check("Timing favors recovery over oscillation", "Scale up within 60 seconds and down after 300–900 seconds.", (p) => between("scaleUpSeconds", 1, 60)(p) && between("scaleDownSeconds", 300, 900)(p)),
    ], source: sreSource,
  }),
  lesson({
    id: 19, title: "Protect service-to-service calls", minutes: 12,
    objective: "Authenticate, authorize, encrypt, and observe communication between workloads.",
    story: "A process inside the cluster can call every internal service because network location is treated as identity. Byte replaces inherited trust with verified workload requests.",
    concepts: [
      { title: "Workloads need identities", body: "A service identity lets the receiver decide which caller is making a request without relying on an IP address or shared credential. Short-lived credentials reduce the value of captured material." },
      { title: "Encryption is not authorization", body: "Mutual TLS can protect the channel and authenticate peers, but the receiver still needs an explicit policy for the action and resource. A valid identity should not imply permission to every service." },
      { title: "Rotation and evidence are operational controls", body: "Automatically rotated certificates limit long-lived exposure, while telemetry records decisions and failures without logging secret material. Default denial makes missing policy fail closed." },
    ],
    example: "orders workload identity + mTLS → policy: orders may call inventory/read → allow + trace decision",
    exampleNote: "A service mesh can supply parts of this path, but application-level authorization may still be required for user and data-specific decisions.",
    mistake: "Enabling mutual TLS and concluding that every authenticated workload should be allowed to call every internal endpoint.",
    mission: "Use workload identity, mutual TLS, default-deny service policy, certificate rotation within thirty days, and decision telemetry.",
    starter: { callerIdentity: "network-location", mutualTls: false, authorization: "allow-all", defaultDeny: false, certificateRotationDays: 365, decisionTelemetry: false },
    solution: { callerIdentity: "workload", mutualTls: true, authorization: "service-policy", defaultDeny: true, certificateRotationDays: 30, decisionTelemetry: true },
    help: { callerIdentity: "How the receiving service identifies its caller.", mutualTls: "Authenticate and encrypt both peers.", authorization: "Action-level access policy.", defaultDeny: "Behavior when no rule matches.", certificateRotationDays: "Maximum credential lifetime.", decisionTelemetry: "Record allowed and denied calls." },
    checks: [
      check("Peers have protected identities", "Use workload identity and mutual TLS.", (p) => p.callerIdentity === "workload" && p.mutualTls === true),
      check("Access is explicitly authorized", "Use service-policy with default deny.", (p) => p.authorization === "service-policy" && p.defaultDeny === true),
      check("Trust rotates and leaves evidence", "Rotate within 1–30 days and record decisions.", (p) => between("certificateRotationDays", 1, 30)(p) && p.decisionTelemetry === true),
    ], source: nistSource,
  }),
  lesson({
    id: 20, title: "Run an incident game day", minutes: 13,
    objective: "Exercise a reliability hypothesis with bounded risk and owned follow-up work.",
    story: "The recovery runbook looks complete, but nobody has used it while alerts and dependencies are active. Byte schedules a controlled database failover exercise.",
    concepts: [
      { title: "Begin with a falsifiable hypothesis", body: "A useful game day predicts an observable service outcome, such as recovery within the SLO while a database host fails. A vague goal to test resilience cannot produce a clear result." },
      { title: "Contain the experiment", body: "A known environment, limited traffic, explicit abort threshold, assigned commander, and ready rollback bound customer and operational risk while preserving a realistic path through the system." },
      { title: "Learning must change the system", body: "A timeline, measured result, and owned follow-up turn the exercise into durable improvement. Untracked observations disappear before the next incident and leave the same weakness in place." },
    ],
    example: "baseline → declare hypothesis → inject staging database failover → watch SLO → abort or recover → track findings",
    exampleNote: "Staging reduces blast radius but may differ from production; record those differences and schedule progressively stronger evidence when the service risk allows it.",
    mistake: "Injecting a failure before naming the expected signal, abort condition, incident commander, or rollback action.",
    mission: "Test a database failover hypothesis in staging, assign an incident commander, abort at five percent user errors, prepare rollback, and track every finding.",
    starter: { hypothesisDefined: false, scenario: "random-outage", blastRadius: "production", commander: "unassigned", abortThresholdPercent: 50, rollbackReady: false, findingsTracked: false },
    solution: { hypothesisDefined: true, scenario: "database-failover", blastRadius: "staging", commander: "incident-commander", abortThresholdPercent: 5, rollbackReady: true, findingsTracked: true },
    help: { hypothesisDefined: "Predicted measurable outcome.", scenario: "Failure injected by the exercise.", blastRadius: "Environment or traffic exposed.", commander: "Decision owner.", abortThresholdPercent: "User-error stop condition.", rollbackReady: "Recovery action is prepared.", findingsTracked: "Lessons have owners and status." },
    checks: [
      check("The exercise has a specific claim", "Define the database-failover hypothesis.", (p) => p.hypothesisDefined === true && p.scenario === "database-failover"),
      check("Customer risk is bounded", "Use staging, an assigned commander, and an abort threshold of 1–5%.", (p) => p.blastRadius === "staging" && p.commander === "incident-commander" && between("abortThresholdPercent", 1, 5)(p)),
      check("Recovery creates durable learning", "Prepare rollback and track findings.", (p) => p.rollbackReady === true && p.findingsTracked === true),
    ], source: sreSource,
  }),
  lesson({
    id: 21, title: "Capstone: Production control loop", minutes: 26,
    objective: "Connect declared intent, reconciliation, demand scaling, workload trust, and game-day evidence.",
    story: "The Delivery Foundry can ship a service, but the final review asks whether production remains aligned, responsive, authorized, and recoverable after that release.",
    concepts: [
      { title: "Delivery continues after deployment", body: "A production system needs a control loop that detects drift, reconciles verified intent, checks health, scales from meaningful demand, and exposes deviations throughout the release lifetime." },
      { title: "Runtime trust is independently verified", body: "A reviewed artifact and declaration do not authorize every internal request. Workload identity, encrypted channels, default-deny policy, and recorded decisions constrain the service after it starts." },
      { title: "Exercises close the evidence gap", body: "Dashboards and runbooks describe expected behavior, while a bounded game day shows whether alerts, decision roles, rollback, dependencies, and service objectives work together under failure." },
    ],
    example: "review → reconcile signed revision → verify health + identity → scale from backlog → exercise recovery → feed findings into Git",
    exampleNote: "The plan models a production feedback loop; real controllers require carefully scoped permissions, provider integrations, and measured service-specific thresholds.",
    mistake: "Treating a successful deployment as the end state and allowing production to drift until the next planned release.",
    mission: "Build the final production control loop with a reviewed sequence, daily drift detection, pull reconciliation, backlog scaling, zero-trust service calls, and a bounded game day.",
    starter: { controlStages: ["deploy"], driftScanHours: 168, reconciliationMode: "push-script", signedRevision: false, healthGated: false, scalingSignal: "cpu", maxWorkers: 50, loadTested: false, workloadIdentity: false, mutualTls: false, defaultDeny: false, gameDayEnvironment: "production", abortThresholdPercent: 50, rollbackReady: false, findingsTracked: false },
    solution: { controlStages: ["review", "reconcile", "verify", "operate"], driftScanHours: 24, reconciliationMode: "pull", signedRevision: true, healthGated: true, scalingSignal: "queue-depth", maxWorkers: 12, loadTested: true, workloadIdentity: true, mutualTls: true, defaultDeny: true, gameDayEnvironment: "staging", abortThresholdPercent: 5, rollbackReady: true, findingsTracked: true },
    help: { controlStages: "Ordered production lifecycle.", driftScanHours: "Desired-versus-observed comparison interval.", reconciliationMode: "How desired state reaches runtime.", signedRevision: "Verified declaration identity.", healthGated: "Convergence includes service health.", scalingSignal: "Demand measure.", maxWorkers: "Tested capacity ceiling.", loadTested: "Dependencies tolerate the ceiling.", workloadIdentity: "Service caller identity.", mutualTls: "Authenticated encrypted channel.", defaultDeny: "Missing authorization fails closed.", gameDayEnvironment: "Initial exercise boundary.", abortThresholdPercent: "User-error stop condition.", rollbackReady: "Recovery action prepared.", findingsTracked: "Exercise improvements owned." },
    checks: [
      check("Production follows an owned control sequence", "Use review, reconcile, verify, and operate in order with daily drift scans.", (p) => ordered(p.controlStages, ["review", "reconcile", "verify", "operate"]) && between("driftScanHours", 1, 24)(p)),
      check("Runtime converges on verified intent", "Use pull reconciliation, a signed revision, and health gating.", (p) => p.reconciliationMode === "pull" && p.signedRevision === true && p.healthGated === true),
      check("Capacity follows tested demand", "Use queue-depth, load testing, and a maximum from 6–12 workers.", (p) => p.scalingSignal === "queue-depth" && p.loadTested === true && between("maxWorkers", 6, 12)(p)),
      check("Internal requests follow zero trust", "Enable workload identity, mutual TLS, and default denial.", (p) => p.workloadIdentity === true && p.mutualTls === true && p.defaultDeny === true),
      check("Failure learning is safe and durable", "Exercise staging with an abort threshold up to 5%, prepared rollback, and tracked findings.", (p) => p.gameDayEnvironment === "staging" && between("abortThresholdPercent", 1, 5)(p) && p.rollbackReady === true && p.findingsTracked === true),
    ], source: sreSource,
  }),
];

export const EXPERT_CLOUD_EXTENSION: CloudLesson[] = [
  lesson({
    id: 16, title: "Isolate platform tenants", minutes: 13,
    objective: "Contain identity, network, data, quota, and noisy-neighbor risk between platform tenants.",
    story: "Teams share a platform cluster, but one compromised workload can scan another namespace and consume the common capacity pool. Byte establishes explicit tenant boundaries.",
    concepts: [
      { title: "Tenant boundaries are layered", body: "A namespace organizes resources but does not alone isolate every control plane, identity, network, secret, node, or data path. Stronger-risk tenants may require dedicated accounts, clusters, or data stores." },
      { title: "Identity and network policy must agree", body: "Per-tenant workload identities constrain cloud API permissions, while default-deny network policy restricts service paths. Reusing a broad identity can bypass the value of otherwise separate runtime spaces." },
      { title: "Capacity is part of isolation", body: "Requests, limits, quotas, priority, and load tests contain a noisy tenant before it exhausts shared compute or dependency capacity. Isolation claims need evidence under contention, not only configuration review." },
    ],
    example: "tenant account + namespace → dedicated workload identity + default-deny network + quota + key boundary",
    exampleNote: "The right isolation unit depends on threat, compliance, scale, and operational cost; not every tenant requires a separate physical cluster.",
    mistake: "Calling a namespace a complete security boundary while tenants share wildcard identities, unrestricted network paths, keys, and quotas.",
    mission: "Use account-and-namespace tenant boundaries, unique workload identity, default-deny networking, per-tenant quotas and keys, and a noisy-neighbor test.",
    starter: { tenantBoundary: "labels-only", workloadIdentityPerTenant: false, networkDefaultDeny: false, quotaPerTenant: false, keyBoundaryPerTenant: false, noisyNeighborTested: false },
    solution: { tenantBoundary: "account-and-namespace", workloadIdentityPerTenant: true, networkDefaultDeny: true, quotaPerTenant: true, keyBoundaryPerTenant: true, noisyNeighborTested: true },
    help: { tenantBoundary: "Primary administrative and runtime isolation units.", workloadIdentityPerTenant: "Unique cloud identity scope.", networkDefaultDeny: "Unapproved east-west paths fail closed.", quotaPerTenant: "Shared capacity ceiling.", keyBoundaryPerTenant: "Separate cryptographic authorization.", noisyNeighborTested: "Contention isolation was measured." },
    checks: [
      check("Tenants have explicit administrative boundaries", "Use account-and-namespace with unique workload identities.", (p) => p.tenantBoundary === "account-and-namespace" && p.workloadIdentityPerTenant === true),
      check("Network and data trust fail closed", "Enable default deny and a key boundary per tenant.", (p) => p.networkDefaultDeny === true && p.keyBoundaryPerTenant === true),
      check("Shared capacity is contained", "Apply per-tenant quotas and run the noisy-neighbor test.", (p) => p.quotaPerTenant === true && p.noisyNeighborTested === true),
    ], source: nistSource,
  }),
  lesson({
    id: 17, title: "Govern data residency and lifecycle", minutes: 13,
    objective: "Enforce where restricted data may live, how long it remains, and how deletion is proven.",
    story: "A global replication default copied restricted Relay records outside their approved geography. Byte turns classification and residency promises into enforceable placement controls.",
    concepts: [
      { title: "Classification drives placement", body: "A data classification should map to allowed storage, processing, backup, logging, and replication regions. Service defaults and hidden dependencies must be checked against the same residency boundary." },
      { title: "Lifecycle includes every copy", body: "Retention and deletion rules apply to primary records, replicas, caches, search indexes, exports, and backups. A user-facing delete that leaves uncontrolled secondary copies does not complete the lifecycle." },
      { title: "Evidence makes policy operable", body: "Preventive controls should deny disallowed placement, while inventories and deletion tests provide detective evidence. A named data owner handles exceptions and changes in legal or product requirements." },
    ],
    example: "restricted classification → approved EU regions → constrained replicas/backups → 365-day retention → verified deletion report",
    exampleNote: "This simulation teaches technical enforcement and evidence; legal counsel and organizational policy determine the actual residency and retention obligations.",
    mistake: "Restricting the primary database region while logs, backups, analytics exports, or disaster-recovery copies move elsewhere by default.",
    mission: "Classify the data as restricted, allow only eu-west-1 and eu-central-1, enforce residency across replicas, retain for 365 days, verify deletion, and assign the data-governance owner.",
    starter: { dataClassification: "public", allowedRegions: ["global"], residencyEnforced: false, replicasRestricted: false, retentionDays: 0, deletionVerified: false, evidenceOwner: "unassigned" },
    solution: { dataClassification: "restricted", allowedRegions: ["eu-west-1", "eu-central-1"], residencyEnforced: true, replicasRestricted: true, retentionDays: 365, deletionVerified: true, evidenceOwner: "data-governance" },
    help: { dataClassification: "Policy category for the records.", allowedRegions: "Approved storage and processing locations.", residencyEnforced: "Deny unapproved placement.", replicasRestricted: "Apply policy to backups and secondary copies.", retentionDays: "Maximum retained lifetime.", deletionVerified: "All modeled copies were tested.", evidenceOwner: "Policy and exception owner." },
    checks: [
      check("Restricted data has an explicit geography", "Use restricted with exactly the two approved EU regions.", (p) => p.dataClassification === "restricted" && exactSet(p.allowedRegions, ["eu-west-1", "eu-central-1"])),
      check("Every modeled copy follows residency", "Enforce residency and restrict replicas.", (p) => p.residencyEnforced === true && p.replicasRestricted === true),
      check("Lifecycle evidence is owned", "Retain for 365 days, verify deletion, and assign data-governance.", (p) => p.retentionDays === 365 && p.deletionVerified === true && p.evidenceOwner === "data-governance"),
    ], source: architectureSource,
  }),
  lesson({
    id: 18, title: "Plan regional capacity", minutes: 14,
    objective: "Reserve enough regional and dependency capacity to meet demand after a region fails.",
    story: "Traffic can move to the standby region, but its quotas and database connections support only half the required load. Byte plans the entire failover capacity envelope.",
    concepts: [
      { title: "Headroom belongs in the requirement", body: "Capacity planning starts with measured peak demand and adds explicit growth or uncertainty headroom. A system sized to yesterday’s exact peak has no room for failover variance or demand growth." },
      { title: "N-minus-one changes regional sizing", body: "When one of two regions may fail, the surviving region must support the required load if the recovery design promises full service. Splitting normal demand evenly is not sufficient failover capacity." },
      { title: "Dependencies and quotas are part of capacity", body: "Compute replicas cannot serve more traffic than databases, queues, external APIs, connection pools, or provider quotas allow. Reservations and exercises must cover the full request path." },
    ],
    example: "6,000 peak requests/s × 1.30 headroom = 7,800 required in the surviving region and every critical dependency",
    exampleNote: "The exercise assumes full active-passive recovery. A degraded-mode service could use a lower documented target if product owners explicitly accept it.",
    mistake: "Doubling application replicas while leaving database connections, queue throughput, IP addresses, or regional quotas at normal-load limits.",
    mission: "Plan for 6,000 requests/s plus thirty percent headroom, reserve 7,800 requests/s in each of two regions and dependencies, and prove the failover.",
    starter: { peakDemandRps: 6000, headroomPercent: 0, activeRegions: 2, capacityPerRegionRps: 3000, dependencyCapacityRps: 3000, quotaReserved: false, failoverTested: false },
    solution: { peakDemandRps: 6000, headroomPercent: 30, activeRegions: 2, capacityPerRegionRps: 7800, dependencyCapacityRps: 7800, quotaReserved: true, failoverTested: true },
    help: { peakDemandRps: "Measured peak service demand.", headroomPercent: "Growth and uncertainty margin.", activeRegions: "Provisioned recovery locations.", capacityPerRegionRps: "Single-region service ceiling.", dependencyCapacityRps: "Single-region downstream ceiling.", quotaReserved: "Provider limits are available.", failoverTested: "Traffic and dependencies were exercised." },
    checks: [
      check("Demand includes the planned margin", "Use 6,000 peak and at least 30% headroom.", (p) => p.peakDemandRps === 6000 && typeof p.headroomPercent === "number" && p.headroomPercent >= 30 && p.headroomPercent <= 50),
      check("One surviving region serves the target", "Use two regions with at least 7,800 requests/s each.", (p) => p.activeRegions === 2 && typeof p.capacityPerRegionRps === "number" && p.capacityPerRegionRps >= 7800),
      check("Dependencies and quotas survive too", "Provide at least 7,800 dependency capacity, reserve quotas, and test failover.", (p) => typeof p.dependencyCapacityRps === "number" && p.dependencyCapacityRps >= 7800 && p.quotaReserved === true && p.failoverTested === true),
    ], source: sreSource,
  }),
  lesson({
    id: 19, title: "Design a versioned platform API", minutes: 13,
    objective: "Expose self-service infrastructure through a stable, observable, and retry-safe contract.",
    story: "Teams automate against an internal portal’s private implementation details. Byte introduces a supported API contract that can evolve without breaking every client.",
    concepts: [
      { title: "A platform API is a product boundary", body: "Versioned request and response schemas separate consumer intent from provider-specific orchestration. Compatibility rules let the platform change internals while preserving supported client behavior." },
      { title: "Long operations need durable status", body: "Environment creation may take minutes, so an asynchronous operation identifier and status endpoint survive client disconnects. Idempotency prevents a retry from creating duplicate environments." },
      { title: "Evolution needs evidence and notice", body: "Audit events record who requested each action and its outcome, while usage telemetry identifies affected clients. A published deprecation window gives teams time to migrate before removal." },
    ],
    example: "POST /v1/environments + idempotency key → 202 operation ID → GET status → ready or actionable failure",
    exampleNote: "Versioning does not permit indefinite compatibility; it makes intentional breaking changes and migration support visible to consumers.",
    mistake: "Holding one HTTP connection open for a twenty-minute provisioning job and creating a second environment whenever the client retries.",
    mission: "Publish v1 with idempotent creation, asynchronous operations, a status endpoint, backward compatibility, ninety days of deprecation notice, and audit events.",
    starter: { apiVersion: "unstable", idempotentCreate: false, asynchronousOperations: false, statusEndpoint: false, backwardCompatible: false, deprecationDays: 0, auditEvents: false },
    solution: { apiVersion: "v1", idempotentCreate: true, asynchronousOperations: true, statusEndpoint: true, backwardCompatible: true, deprecationDays: 90, auditEvents: true },
    help: { apiVersion: "Supported contract version.", idempotentCreate: "Duplicate retries preserve one result.", asynchronousOperations: "Long work returns an operation resource.", statusEndpoint: "Clients can inspect progress.", backwardCompatible: "Existing v1 consumers keep working.", deprecationDays: "Minimum migration notice.", auditEvents: "Record request identity and result." },
    checks: [
      check("Consumers receive a stable contract", "Publish v1 and keep it backward compatible.", (p) => p.apiVersion === "v1" && p.backwardCompatible === true),
      check("Provisioning is retry-safe and observable", "Enable idempotency, asynchronous operations, and status.", (p) => p.idempotentCreate === true && p.asynchronousOperations === true && p.statusEndpoint === true),
      check("Change has notice and evidence", "Give at least 90 days and emit audit events.", (p) => typeof p.deprecationDays === "number" && p.deprecationDays >= 90 && p.deprecationDays <= 365 && p.auditEvents === true),
    ], source: architectureSource,
  }),
  lesson({
    id: 20, title: "Measure the platform as a product", minutes: 13,
    objective: "Use adoption, delivery, reliability, satisfaction, and support evidence to improve the platform.",
    story: "The platform has many features, yet teams still open manual tickets and build parallel pipelines. Byte measures whether the paved road actually helps its users succeed.",
    concepts: [
      { title: "Adoption needs a meaningful denominator", body: "Counting registered teams can hide abandoned use. Successful self-service deployments, repeat usage, eligible-service coverage, and escape-hatch frequency show whether the platform handles real work." },
      { title: "Speed cannot replace reliability", body: "Lead time and deployment frequency describe flow, while a platform SLO captures whether the workflows are available and correct. Optimizing only one dimension can make the developer experience worse." },
      { title: "Feedback needs ownership", body: "Satisfaction surveys, support themes, telemetry, and user interviews should feed a visible roadmap. A named platform team closes the loop and explains why recurring exceptions remain necessary." },
    ],
    example: "successful self-service deployments + lead time + 99.9% workflow SLO + satisfaction + escape-hatch review → quarterly roadmap",
    exampleNote: "Metrics support product decisions but need qualitative context; a low escape-hatch count can also mean teams gave up rather than accepted the paved road.",
    mistake: "Declaring success from the number of templates published without measuring completed workflows, reliability, user effort, or unsupported workarounds.",
    mission: "Measure successful self-service deployments, lead time, a 99.9% platform SLO, satisfaction, and escape hatches; assign the platform team and review a quarterly roadmap.",
    starter: { adoptionMetric: "registered-users", leadTimeMeasured: false, platformSlo: 100, satisfactionSurvey: false, escapeHatchesMeasured: false, supportOwner: "unassigned", quarterlyRoadmap: false },
    solution: { adoptionMetric: "successful-self-service-deployments", leadTimeMeasured: true, platformSlo: 99.9, satisfactionSurvey: true, escapeHatchesMeasured: true, supportOwner: "platform-team", quarterlyRoadmap: true },
    help: { adoptionMetric: "Evidence of completed platform value.", leadTimeMeasured: "Time from request to usable environment.", platformSlo: "Reliability objective for platform workflows.", satisfactionSurvey: "Direct user experience signal.", escapeHatchesMeasured: "Unsupported paths and reasons are visible.", supportOwner: "Team accountable for service and feedback.", quarterlyRoadmap: "Regular prioritized improvement plan." },
    checks: [
      check("Adoption reflects completed work", "Measure successful-self-service-deployments and lead time.", (p) => p.adoptionMetric === "successful-self-service-deployments" && p.leadTimeMeasured === true),
      check("Quality includes reliability and sentiment", "Use a 99–99.99 SLO and a satisfaction survey.", (p) => typeof p.platformSlo === "number" && p.platformSlo >= 99 && p.platformSlo <= 99.99 && p.satisfactionSurvey === true),
      check("Feedback reaches an accountable roadmap", "Measure escape hatches, assign platform-team, and maintain a quarterly roadmap.", (p) => p.escapeHatchesMeasured === true && p.supportOwner === "platform-team" && p.quarterlyRoadmap === true),
    ], source: finopsSource,
  }),
  lesson({
    id: 21, title: "Capstone: Governed platform commons", minutes: 30,
    objective: "Design an operable multi-tenant platform with governed data, regional capacity, stable APIs, and measurable product outcomes.",
    story: "The final Platform Commons review onboards regulated teams, removes one region, retries an environment request, overloads a tenant, and asks whether the paved road creates measurable value.",
    concepts: [
      { title: "A platform joins control planes and user journeys", body: "Tenant boundaries, data policy, capacity, and APIs must form one supported path from an engineer’s request to a governed runtime. Disconnected controls push users toward manual exceptions." },
      { title: "Resilience includes organizational load", body: "Regional failover and tenant quotas protect runtime capacity, while stable asynchronous APIs prevent automation retries from multiplying work. Support ownership contains operational demand on the platform team." },
      { title: "Governance improves through feedback", body: "Residency and isolation controls need continuous evidence, and the platform product needs adoption, reliability, satisfaction, and escape-hatch signals. A roadmap connects those findings to owned change." },
    ],
    example: "versioned request → tenant boundary + residency policy → capacity-resilient runtime → audit evidence → product metrics → roadmap",
    exampleNote: "The capstone evaluates a compact governance model; a real platform must adapt controls to its providers, tenants, regulations, service tiers, and operating organization.",
    mistake: "Offering self-service APIs without tenant containment, data policy, failover capacity, operational ownership, or evidence that users can complete their work.",
    mission: "Complete the governed platform: layered tenant isolation, enforced EU residency, N-minus-one regional capacity, retry-safe v1 self-service, and measurable product ownership.",
    starter: { platformStages: ["provision"], tenantBoundary: "labels-only", workloadIdentityPerTenant: false, quotaPerTenant: false, dataClassification: "public", allowedRegions: ["global"], residencyEnforced: false, deletionVerified: false, regionalCapacityRps: 3000, dependencyCapacityRps: 3000, failoverTested: false, apiVersion: "unstable", idempotentCreate: false, statusEndpoint: false, platformSlo: 100, adoptionMeasured: false, satisfactionMeasured: false, supportOwner: "unassigned" },
    solution: { platformStages: ["request", "govern", "provision", "verify", "operate"], tenantBoundary: "account-and-namespace", workloadIdentityPerTenant: true, quotaPerTenant: true, dataClassification: "restricted", allowedRegions: ["eu-west-1", "eu-central-1"], residencyEnforced: true, deletionVerified: true, regionalCapacityRps: 7800, dependencyCapacityRps: 7800, failoverTested: true, apiVersion: "v1", idempotentCreate: true, statusEndpoint: true, platformSlo: 99.9, adoptionMeasured: true, satisfactionMeasured: true, supportOwner: "platform-team" },
    help: { platformStages: "Ordered platform lifecycle.", tenantBoundary: "Administrative and runtime isolation.", workloadIdentityPerTenant: "Unique tenant cloud identity.", quotaPerTenant: "Shared-capacity containment.", dataClassification: "Policy category.", allowedRegions: "Approved processing locations.", residencyEnforced: "Deny disallowed placement.", deletionVerified: "Lifecycle evidence.", regionalCapacityRps: "Surviving-region service ceiling.", dependencyCapacityRps: "Surviving-region downstream ceiling.", failoverTested: "Regional exercise evidence.", apiVersion: "Supported self-service contract.", idempotentCreate: "Retry-safe request behavior.", statusEndpoint: "Durable operation visibility.", platformSlo: "Workflow reliability objective.", adoptionMeasured: "Completed usage is tracked.", satisfactionMeasured: "User experience is sampled.", supportOwner: "Accountable product team." },
    checks: [
      check("The platform follows an operated lifecycle", "Use request, govern, provision, verify, and operate in order.", (p) => ordered(p.platformStages, ["request", "govern", "provision", "verify", "operate"])),
      check("Tenant risk is contained", "Use account-and-namespace, unique identities, and quotas.", (p) => p.tenantBoundary === "account-and-namespace" && p.workloadIdentityPerTenant === true && p.quotaPerTenant === true),
      check("Restricted data stays governed", "Use restricted data, both approved EU regions, enforcement, and verified deletion.", (p) => p.dataClassification === "restricted" && exactSet(p.allowedRegions, ["eu-west-1", "eu-central-1"]) && p.residencyEnforced === true && p.deletionVerified === true),
      check("Regional recovery includes dependencies", "Reserve at least 7,800 requests/s across the service and dependencies, then test it.", (p) => typeof p.regionalCapacityRps === "number" && p.regionalCapacityRps >= 7800 && typeof p.dependencyCapacityRps === "number" && p.dependencyCapacityRps >= 7800 && p.failoverTested === true),
      check("Self-service is stable and measured", "Use retry-safe v1 with status, a 99–99.99 SLO, adoption and satisfaction evidence, and platform-team ownership.", (p) => p.apiVersion === "v1" && p.idempotentCreate === true && p.statusEndpoint === true && typeof p.platformSlo === "number" && p.platformSlo >= 99 && p.platformSlo <= 99.99 && p.adoptionMeasured === true && p.satisfactionMeasured === true && p.supportOwner === "platform-team"),
    ], source: architectureSource,
  }),
];
