export type PythonPaceId = "beginner" | "intermediate" | "expert";

export type PythonTopic = {
  title: string;
  summary: string;
  learningGoal: string;
  example: string;
  keyIdeas: Array<{ title: string; body: string }>;
  commonMistake: string;
  mentalModel: string;
};

export type PythonPace = {
  id: PythonPaceId;
  label: string;
  tagline: string;
  description: string;
  recommendedFor: string;
  estimatedLevel: string;
  topics: PythonTopic[];
};

const makeTopic = (
  title: string,
  summary: string,
  learningGoal: string,
  example: string,
  ideas: Array<[title: string, body: string]>,
  commonMistake: string,
  mentalModel: string,
): PythonTopic => ({
  title,
  summary,
  learningGoal,
  example,
  keyIdeas: ideas.map(([ideaTitle, body]) => ({ title: ideaTitle, body })),
  commonMistake,
  mentalModel,
});

export const PYTHON_PACES: PythonPace[] = [
  {
    id: "beginner",
    label: "Beginner",
    tagline: "Build rock-solid Python foundations.",
    description:
      "Learn how Python works, express ideas with its core building blocks, and develop the habits needed to write small programs confidently.",
    recommendedFor:
      "First-time programmers and self-taught learners who want a guided path with no assumed knowledge.",
    estimatedLevel: "No prior Python experience",
    topics: [
      makeTopic(
        "Environment",
        "Your Python environment is the interpreter and workspace that turn source code into a running program.",
        "Identify the active Python interpreter, use the REPL, and run a saved script from a terminal.",
        "$ python --version\n$ python hello.py",
        [
          ["Interpreter", "The interpreter reads Python instructions and executes them on your computer."],
          ["REPL and scripts", "The REPL is ideal for quick experiments; scripts preserve reusable programs."],
          ["Working directory", "Relative paths are resolved from the directory where the command is run."],
        ],
        "Installing several Python versions and unknowingly running a different interpreter than the one used to install packages.",
        "Treat the environment as a workshop: the interpreter is the craftsperson, the terminal is the workbench, and the project folder holds the materials.",
      ),
      makeTopic(
        "Variables",
        "Variables give readable names to values so a program can remember and update information.",
        "Create descriptive names, rebind them as state changes, and follow Python naming conventions.",
        "energy_cells = 12\nexplorer_name = \"Nova\"\nenergy_cells += 3",
        [
          ["Assignment", "The equals sign binds the name on the left to the value produced on the right."],
          ["Rebinding", "A name can later point to a new value, even one with a different type."],
          ["Readable names", "snake_case names communicate purpose better than unexplained abbreviations."],
        ],
        "Reading assignment as a mathematical equality instead of an instruction to bind a name.",
        "A variable is a movable label attached to a value, not a permanent box with a fixed type.",
      ),
      makeTopic(
        "Data types",
        "Data types describe what a value represents and which operations Python can perform on it.",
        "Recognize core scalar types, inspect values with type(), and convert compatible values deliberately.",
        "items = 8\nprice = 2.5\nis_open = True\nsector = None",
        [
          ["Core types", "int, float, str, bool, and NoneType cover many everyday values."],
          ["Behavior matters", "A value's type determines valid operations, such as addition or text methods."],
          ["Conversion", "Constructors like int() and str() create a value of another compatible type."],
        ],
        "Assuming text that contains digits behaves like a number without explicitly converting it.",
        "Think of a type as a rulebook attached to a value: it defines the moves that value understands.",
      ),
      makeTopic(
        "Operators",
        "Operators combine, compare, or transform values to produce new results.",
        "Use arithmetic, comparison, logical, membership, and assignment operators with correct precedence.",
        "score = 7 * 3\nqualified = score >= 20 and score != 25\nfound = \"relay\" in \"relay station\"",
        [
          ["Arithmetic", "+, -, *, /, //, %, and ** express numerical calculations."],
          ["Comparison", "Comparison operators return booleans and can be chained in Python."],
          ["Boolean logic", "and, or, and not combine conditions, using short-circuit evaluation."],
        ],
        "Relying on memory for a long expression's precedence instead of adding clarifying parentheses.",
        "Operators are verbs between values: they tell Python which relationship or transformation to evaluate.",
      ),
      makeTopic(
        "Strings",
        "Strings are immutable sequences of Unicode characters used to represent and format text.",
        "Create, index, slice, search, clean, and format strings with f-strings.",
        "name = \"Nova\"\nmessage = f\"Welcome, {name}!\"\nfirst_word = message.split()[0]",
        [
          ["Sequence behavior", "Characters have positions, so indexing and slicing work on strings."],
          ["Immutability", "String methods return new strings rather than changing the original value."],
          ["Formatting", "f-strings embed expressions in readable text with optional format specifications."],
        ],
        "Calling a string method without storing its returned value and expecting the original string to change.",
        "Picture a string as a sealed row of letter tiles: you can read or copy sections, but edits create a new row.",
      ),
      makeTopic(
        "Lists",
        "Lists are ordered, mutable collections that can hold any number of Python values.",
        "Build lists, access and update items, slice ranges, and choose appropriate list methods.",
        "toolkit = [\"field scanner\", \"energy cell\"]\ntoolkit.append(\"sector map\")\nfirst_two = toolkit[:2]",
        [
          ["Ordered positions", "Every item has a zero-based index, including negative indexes from the end."],
          ["Mutability", "Methods such as append(), extend(), and pop() change the same list object."],
          ["Slicing", "A slice selects a range and normally produces a shallow new list."],
        ],
        "Modifying a list while iterating over it and accidentally skipping or repeating items.",
        "A list is an expandable numbered shelf: positions matter, and items can be replaced or rearranged.",
      ),
      makeTopic(
        "Tuples",
        "Tuples are ordered, immutable sequences suited to fixed groups of related values.",
        "Create tuples, unpack their elements, and decide when immutability better communicates intent.",
        "beacon = (120, 64, -30)\nx, y, z = beacon\norigin = (0,) ",
        [
          ["Fixed sequence", "Tuple items retain order but cannot be added, removed, or replaced in place."],
          ["Packing and unpacking", "Python can group values into a tuple and distribute them into names."],
          ["Semantic records", "A small tuple can represent a stable coordinate, range, or return value."],
        ],
        "Forgetting the comma in a one-item tuple; parentheses alone do not create a tuple.",
        "A tuple is a sealed coordinate card: its positions can be read and unpacked, but the card stays fixed.",
      ),
      makeTopic(
        "Sets",
        "Sets are unordered collections that keep only unique, hashable values.",
        "Remove duplicates and use union, intersection, difference, and fast membership checks.",
        "found = {\"cyan\", \"amber\", \"cyan\"}\nneeded = {\"amber\", \"violet\"}\nmissing = needed - found",
        [
          ["Uniqueness", "Adding a duplicate leaves a set unchanged, making deduplication natural."],
          ["Set algebra", "Operators such as |, &, -, and ^ express relationships between groups."],
          ["Fast membership", "Hashing usually makes value-in-set checks efficient even for large sets."],
        ],
        "Expecting set iteration order to carry meaning or trying to access a set by index.",
        "A set is a bag of unique badges: possession matters, but position does not.",
      ),
      makeTopic(
        "Dictionaries",
        "Dictionaries map unique, hashable keys to values for direct lookup by meaning instead of position.",
        "Create mappings, safely read and update entries, iterate over pairs, and choose useful keys.",
        "explorer = {\"name\": \"Nova\", \"shield\": 10}\nexplorer[\"shield\"] -= 1\nlevel = explorer.get(\"level\", 1)",
        [
          ["Key-value mapping", "Each key identifies one value and must be unique within the dictionary."],
          ["Safe access", "get() can supply a default when a key may be absent."],
          ["Views", "keys(), values(), and items() provide dynamic views for iteration."],
        ],
        "Using bracket access for an optional key and being surprised by a KeyError.",
        "A dictionary is a labeled storage wall: a key is the label that leads directly to its stored value.",
      ),
      makeTopic(
        "Conditions",
        "Conditional statements select which block runs according to boolean expressions.",
        "Write clear if, elif, and else branches and combine comparisons without overlapping logic.",
        "if shield <= 0:\n    state = \"offline\"\nelif shield < 4:\n    state = \"unstable\"\nelse:\n    state = \"stable\"",
        [
          ["Branch order", "Python tests branches top to bottom and runs the first condition that is true."],
          ["Truthiness", "Empty collections, zero, None, and False are falsy; many other values are truthy."],
          ["Indentation", "Whitespace defines the statements belonging to each branch."],
        ],
        "Writing broad conditions before specific ones, which makes later branches unreachable.",
        "A conditional is a fork in a trail: each sign is checked in order, and one route is chosen.",
      ),
      makeTopic(
        "Loops",
        "Loops repeat a block for each item or while a condition remains true.",
        "Choose between for and while, use range(), and control execution with break and continue.",
        "for sector in range(1, 4):\n    print(f\"Scanning sector {sector}\")\n\nwhile energy > 0:\n    energy -= 1",
        [
          ["For loops", "A for loop consumes values from an iterable one at a time."],
          ["While loops", "A while loop repeats until its condition becomes false."],
          ["Loop control", "break exits, continue skips to the next iteration, and else can mark normal completion."],
        ],
        "Creating a while loop whose condition can never change, causing an unintended infinite loop.",
        "A loop is a conveyor belt: the same station handles each arriving item until the belt ends or is stopped.",
      ),
      makeTopic(
        "Functions",
        "Functions package a named operation so it can be called, tested, and reused.",
        "Define parameters and defaults, return useful results, and separate a task into focused functions.",
        "def assemble(circuits: int, connectors: int = 2) -> int:\n    return min(circuits // 3, connectors // 2)\n\nrelays = assemble(12, 8)",
        [
          ["Inputs", "Parameters name the inputs; arguments supply actual values at the call site."],
          ["Return values", "return sends a result to the caller and immediately ends the function."],
          ["Single purpose", "A focused function is easier to name, understand, reuse, and test."],
        ],
        "Printing a result inside a function when callers need a returned value to continue computing.",
        "A function is a small machine: arguments enter, a defined job happens, and a result may come out.",
      ),
      makeTopic(
        "Scope",
        "Scope determines where a name is visible and which binding Python selects.",
        "Distinguish local and global names, understand basic LEGB lookup, and avoid unnecessary global state.",
        "rate = 2\n\ndef reward(repairs):\n    bonus = 5\n    return repairs * rate + bonus",
        [
          ["Local scope", "Names assigned inside a function normally belong only to that call."],
          ["Name lookup", "Python searches Local, Enclosing, Global, then Built-in scopes."],
          ["State boundaries", "Passing values and returning results makes dependencies visible."],
        ],
        "Assigning to a global name inside a function and expecting Python to update it without an explicit global declaration.",
        "Scopes are nested rooms: look in the current room first, then walk outward through enclosing rooms.",
      ),
      makeTopic(
        "Exceptions",
        "Exceptions represent failures or unusual conditions that interrupt normal control flow.",
        "Catch specific exceptions, preserve useful error information, and raise errors when an input violates a contract.",
        "try:\n    amount = int(raw_amount)\nexcept ValueError as error:\n    print(f\"Invalid amount: {error}\")\nelse:\n    print(amount)",
        [
          ["Specific handling", "Catch only exceptions you can meaningfully recover from or explain."],
          ["Structured blocks", "else runs after success; finally runs whether an exception occurred or not."],
          ["Raising", "raise signals that a function cannot satisfy its promised behavior."],
        ],
        "Using a bare except that hides programming errors and makes failures difficult to diagnose.",
        "An exception is an emergency signal: it travels upward until a prepared handler responds.",
      ),
      makeTopic(
        "Files",
        "File operations let programs persist text and bytes beyond a single run.",
        "Open files with a context manager, select modes and encodings, and read or write safely.",
        "from pathlib import Path\n\npath = Path(\"notes.txt\")\npath.write_text(\"Log lumen crystals\\n\", encoding=\"utf-8\")\nnotes = path.read_text(encoding=\"utf-8\")",
        [
          ["Paths", "pathlib represents locations cleanly and works across operating systems."],
          ["Modes and encoding", "Text, binary, read, write, and append modes express the intended operation."],
          ["Resource safety", "A with block closes an opened file even when an error occurs."],
        ],
        "Opening a file in write mode when existing contents must be preserved, which truncates the file.",
        "A file is a durable archive vault: choose its location and opening mode before reading or changing what is inside.",
      ),
      makeTopic(
        "Modules",
        "Modules organize Python definitions into importable files and packages.",
        "Import names clearly, create a reusable module, and protect script-only work with a main guard.",
        "from math import sqrt\n\ndef distance(x, y):\n    return sqrt(x**2 + y**2)\n\nif __name__ == \"__main__\":\n    print(distance(3, 4))",
        [
          ["Namespaces", "A module gives related names their own organized namespace."],
          ["Import styles", "Module imports preserve context; selective imports can shorten frequent access."],
          ["Main guard", "The __name__ check separates behavior on direct execution from behavior on import."],
        ],
        "Naming a local file after a standard-library module and accidentally shadowing the real module.",
        "A module is a labeled toolbox: importing it makes its tools available without dumping them loose into the room.",
      ),
      makeTopic(
        "Git basics",
        "Git records meaningful snapshots of a project so changes can be inspected, shared, and reversed.",
        "Initialize a repository, inspect status, stage focused changes, and create a descriptive commit.",
        "$ git init\n$ git status\n$ git add app.py\n$ git commit -m \"Add toolkit counter\"",
        [
          ["Working tree", "Edited files live in the working tree until selected for the next snapshot."],
          ["Staging area", "git add builds the exact set of changes intended for one commit."],
          ["Commits", "A commit is a named project snapshot with history and authorship."],
        ],
        "Running git add on everything without reviewing the diff, which can commit secrets or unrelated files.",
        "Git is a trail of save points: stage the supplies for one checkpoint, then record why that checkpoint matters.",
      ),
      makeTopic(
        "Virtual environments",
        "A virtual environment gives one project an isolated Python interpreter and package directory.",
        "Create, activate, verify, and deactivate a project-specific environment.",
        "$ python -m venv .venv\n$ .venv\\Scripts\\activate\n$ python -c \"import sys; print(sys.executable)\"",
        [
          ["Isolation", "Each environment can hold package versions without changing other projects."],
          ["Activation", "Activation adjusts the shell so python and pip resolve to the environment."],
          ["Recreation", "The environment folder is disposable when dependencies are documented elsewhere."],
        ],
        "Installing dependencies before activation and later wondering why the project cannot import them.",
        "A virtual environment is a private backpack for one project: only that journey's tools go inside.",
      ),
      makeTopic(
        "Dependency basics",
        "Dependencies are external packages a project relies on, together with compatible version constraints.",
        "Install packages through the active interpreter and record enough version information to reproduce the project.",
        "$ python -m pip install requests\n$ python -m pip freeze > requirements.txt\n$ python -m pip install -r requirements.txt",
        [
          ["Package index", "pip usually retrieves published distributions from the Python Package Index."],
          ["Version constraints", "Constraints balance reproducibility with access to compatible fixes."],
          ["Direct dependencies", "Document packages the project intentionally uses, not just imports by accident."],
        ],
        "Using pip tied to a different interpreter; python -m pip makes the relationship explicit.",
        "Dependencies are borrowed tools: record the exact toolbox recipe so another workshop can be set up.",
      ),
      makeTopic(
        "JSON",
        "JSON is a language-neutral text format for nested objects, arrays, strings, numbers, booleans, and null.",
        "Convert between JSON text and Python values and validate assumptions about received data.",
        "import json\n\npayload = json.dumps({\"name\": \"Nova\", \"level\": 4})\ndata = json.loads(payload)\nprint(data[\"level\"])",
        [
          ["Serialization", "dumps() encodes Python values as text; loads() decodes JSON text."],
          ["Type mapping", "JSON objects become dicts, arrays become lists, and null becomes None."],
          ["Data contract", "Valid JSON syntax does not guarantee required fields or suitable values."],
        ],
        "Treating a JSON string as though it were already a dictionary instead of decoding it first.",
        "JSON is a shipping crate format: encode values for transport, then unpack them into native Python objects.",
      ),
      makeTopic(
        "Debugging basics",
        "Debugging is the disciplined process of observing a program, locating the first wrong assumption, and correcting it.",
        "Read tracebacks, reproduce failures, inspect state, and use breakpoints rather than random edits.",
        "def ratio(found, searched):\n    breakpoint()\n    return found / searched\n\nprint(ratio(3, 10))",
        [
          ["Reproduction", "A small, repeatable failing case creates a stable target for investigation."],
          ["Tracebacks", "Read from the final exception upward to find the failing line and call path."],
          ["State inspection", "A debugger reveals current values and control flow one step at a time."],
        ],
        "Changing several things at once, which hides which assumption was actually responsible.",
        "Debugging is detective work: preserve the scene, follow evidence backward, and test one hypothesis at a time.",
      ),
      makeTopic(
        "Basic DSA",
        "Data structures organize values, while algorithms define the steps used to process them.",
        "Choose basic list, stack, queue, set, and dictionary structures according to needed operations.",
        "from collections import deque\n\ntasks = deque([\"scan\", \"calibrate\"])\ntasks.append(\"deploy\")\nnext_task = tasks.popleft()",
        [
          ["Operation-first choice", "Choose a structure by the reads, writes, ordering, and membership checks required."],
          ["Stack and queue", "Stacks are last-in-first-out; queues are first-in-first-out."],
          ["Tradeoffs", "No structure is universally best; convenient operations carry different costs."],
        ],
        "Choosing a familiar list for every problem without considering whether another structure expresses the behavior better.",
        "A data structure is a storage layout, and an algorithm is the route taken through that layout.",
      ),
      makeTopic(
        "Big-O basics",
        "Big-O notation describes how an algorithm's resource use grows as its input becomes larger.",
        "Recognize constant, logarithmic, linear, and quadratic growth and compare common collection operations.",
        "def contains(items, target):  # O(n) time\n    for item in items:\n        if item == target:\n            return True\n    return False",
        [
          ["Growth, not stopwatch time", "Big-O focuses on scaling shape while ignoring hardware-specific constants."],
          ["Dominant work", "For large inputs, the fastest-growing term determines the complexity class."],
          ["Time and space", "An optimization may reduce runtime by using more memory, or the reverse."],
        ],
        "Assuming Big-O predicts exact runtime or that every operation inside a loop has constant cost.",
        "Big-O is a zoomed-out map: it shows how the road length changes as the world expands.",
      ),
      makeTopic(
        "Basic recursion",
        "Recursion solves a problem by having a function call itself on a smaller version of that problem.",
        "Define a base case, guarantee progress toward it, and trace the call stack for a small input.",
        "def countdown(number):\n    if number <= 0:\n        return []\n    return [number] + countdown(number - 1)\n\nprint(countdown(3))",
        [
          ["Base case", "A direct answer stops further recursive calls."],
          ["Recursive step", "Each call must reduce or simplify the remaining problem."],
          ["Call stack", "Every unfinished call keeps its local state until deeper calls return."],
        ],
        "Writing a recursive step that does not reliably move toward the base case.",
        "Recursion is a stack of matching boxes: open smaller boxes until the simplest one, then close them in reverse order.",
      ),
    ],
  },
  {
    id: "intermediate",
    label: "Intermediate",
    tagline: "Turn Python knowledge into professional fluency.",
    description:
      "Master Python's expressive features, build maintainable applications, work with data and APIs, and apply core computer-science techniques.",
    recommendedFor:
      "Learners who can already write small Python programs with functions, collections, files, and exceptions.",
    estimatedLevel: "Comfortable with Python fundamentals",
    topics: [
      makeTopic(
        "OOP",
        "Object-oriented programming models behavior and state together through classes and their instances.",
        "Design a focused class, distinguish instance from class state, and prefer composition when objects collaborate.",
        "class Toolkit:\n    def __init__(self):\n        self.items = []\n\n    def add(self, item):\n        self.items.append(item)\n\nkit = Toolkit()\nkit.add(\"sector map\")",
        [
          ["Classes and instances", "A class defines shared behavior; each instance owns its particular state."],
          ["Encapsulation", "Methods protect invariants by controlling how an object's state changes."],
          ["Composition", "Small objects can collaborate by containing or receiving other objects."],
        ],
        "Creating classes that only group unrelated helper functions and have no meaningful state or invariant.",
        "A class is a blueprint for responsible actors: each actor carries state and knows which actions it can perform.",
      ),
      makeTopic(
        "Comprehensions",
        "Comprehensions construct collections by expressing a transformation and optional filter in one readable form.",
        "Write list, set, and dictionary comprehensions and choose a regular loop when logic becomes complex.",
        "signals = [\"amber\", \"cyan\", \"violet\"]\nlabels = [signal.upper() for signal in signals if signal != \"amber\"]\nlengths = {signal: len(signal) for signal in signals}",
        [
          ["Expression first", "The leading expression describes the value placed in the new collection."],
          ["Iteration and filter", "for supplies candidates and an optional if retains only matching ones."],
          ["Collection forms", "Brackets create lists, braces create sets or dictionaries, and parentheses create generators."],
        ],
        "Nesting several loops and conditions into a compressed expression that is harder to understand than a normal loop.",
        "A comprehension is a collection factory line: transform each incoming item and optionally reject it at the gate.",
      ),
      makeTopic(
        "Lambda",
        "A lambda creates a small anonymous function containing one expression.",
        "Use lambdas as short callback or key functions without hiding complex business logic inside them.",
        "explorers = [{\"name\": \"Nova\", \"xp\": 80}, {\"name\": \"Kiro\", \"xp\": 120}]\nranked = sorted(explorers, key=lambda explorer: explorer[\"xp\"], reverse=True)",
        [
          ["Expression function", "A lambda evaluates one expression and implicitly returns its result."],
          ["Callback use", "APIs such as sorted() often need a tiny function supplied at the call site."],
          ["Naming threshold", "If the behavior needs explanation, statements, or reuse, define a named function."],
        ],
        "Using a long lambda to save lines even though a named function would make intent and testing clearer.",
        "A lambda is a disposable pocket tool: excellent for one small local job, awkward for a full repair.",
      ),
      makeTopic(
        "Iterators",
        "An iterator produces one value at a time through Python's iteration protocol.",
        "Use iter() and next(), recognize iterable versus iterator, and design code that consumes streams once.",
        "items = iter([\"signal beacon\", \"sector map\"])\nfirst = next(items)\nsecond = next(items, \"empty\")\nthird = next(items, \"empty\")",
        [
          ["Iterable protocol", "iterable.__iter__() returns an iterator that can supply values."],
          ["Iterator protocol", "next() calls __next__(), which returns a value or raises StopIteration."],
          ["One-way consumption", "Many iterators cannot rewind; consumed values are gone unless stored."],
        ],
        "Trying to iterate over the same exhausted iterator twice and expecting the original values again.",
        "An iterator is a ticket dispenser: each request yields the next ticket until none remain.",
      ),
      makeTopic(
        "Generators",
        "Generators are lazy iterators whose functions pause at yield and resume with preserved local state.",
        "Write a generator, consume it incrementally, and use lazy pipelines for large or unbounded data.",
        "def countdown(start):\n    while start > 0:\n        yield start\n        start -= 1\n\nfor number in countdown(3):\n    print(number)",
        [
          ["Yield and resume", "yield emits a value without discarding the function's execution state."],
          ["Lazy evaluation", "Values are computed only when requested, reducing up-front work and memory."],
          ["Pipeline design", "Generator expressions can filter and transform streams stage by stage."],
        ],
        "Converting a generator to a list immediately when streaming behavior was the reason to use it.",
        "A generator is a trail guide who reveals one step only when the traveler is ready to move.",
      ),
      makeTopic(
        "Decorators",
        "Decorators wrap a callable to add behavior while preserving the callable's main responsibility.",
        "Implement a function decorator with *args, **kwargs, and functools.wraps, then apply it selectively.",
        "from functools import wraps\n\ndef announce(func):\n    @wraps(func)\n    def wrapper(*args, **kwargs):\n        print(f\"Calling {func.__name__}\")\n        return func(*args, **kwargs)\n    return wrapper",
        [
          ["Callable transformation", "@decorate replaces the original binding with the decorator's returned callable."],
          ["Transparent forwarding", "Generic wrappers forward positional and keyword arguments and return the result."],
          ["Metadata preservation", "functools.wraps retains the wrapped function's name, documentation, and introspection links."],
        ],
        "Forgetting to return either the wrapper from the decorator or the result from the wrapper.",
        "A decorator is a checkpoint built around a road: travelers still reach the destination, with an added action on the way.",
      ),
      makeTopic(
        "Closures",
        "A closure is a function that remembers names from the enclosing scope where it was created.",
        "Build a function factory, understand captured state, and use nonlocal only for intentional updates.",
        "def multiplier(factor):\n    def scale(value):\n        return value * factor\n    return scale\n\ndouble = multiplier(2)\nprint(double(7))",
        [
          ["Lexical capture", "The inner function retains access to enclosing bindings after the outer call ends."],
          ["Function factories", "One factory can create specialized callables configured by captured values."],
          ["Nonlocal state", "nonlocal permits rebinding a captured name but should not conceal complex mutable state."],
        ],
        "Creating closures in a loop that all capture the same final loop variable instead of binding each intended value.",
        "A closure is a function carrying a small sealed backpack of values from the place it was created.",
      ),
      makeTopic(
        "Context managers",
        "Context managers guarantee setup and cleanup around a block, including when the block raises an exception.",
        "Use with, understand __enter__ and __exit__, and create a concise manager with contextlib.contextmanager.",
        "from contextlib import contextmanager\n\n@contextmanager\ndef opened(path):\n    handle = open(path, encoding=\"utf-8\")\n    try:\n        yield handle\n    finally:\n        handle.close()",
        [
          ["Resource lifetime", "The with statement makes acquisition and release share one visible boundary."],
          ["Protocol hooks", "__enter__ supplies the block value and __exit__ performs cleanup."],
          ["Exception safety", "Cleanup runs as control leaves the block, whether normally or through failure."],
        ],
        "Performing setup before the try/finally boundary so a partial failure can leak an acquired resource.",
        "A context manager is an airlock: it prepares entry, watches the enclosed visit, and restores safety on exit.",
      ),
      makeTopic(
        "Type hints",
        "Type hints document expected values and let static tools detect incompatible operations before runtime.",
        "Annotate parameters, returns, collections, unions, and optional values without treating hints as runtime enforcement.",
        "def find_level(explorers: dict[str, int], name: str) -> int | None:\n    return explorers.get(name)\n\nlevel: int | None = find_level({\"Nova\": 7}, \"Nova\")",
        [
          ["Function contracts", "Parameter and return annotations communicate how callers should use a function."],
          ["Static analysis", "Type checkers follow possible values across code paths and flag inconsistencies."],
          ["Gradual typing", "Annotations can be added incrementally at important boundaries."],
        ],
        "Assuming an annotation automatically validates or converts values when the program runs.",
        "Type hints are route annotations on a map: they guide travelers and inspectors but do not build physical barriers.",
      ),
      makeTopic(
        "Dataclasses",
        "Dataclasses generate routine data-model methods from annotated fields while leaving domain behavior explicit.",
        "Define defaults safely, choose frozen or ordered behavior, and attach validation when a model has invariants.",
        "from dataclasses import dataclass, field\n\n@dataclass(frozen=True)\nclass Player:\n    name: str\n    badges: tuple[str, ...] = field(default_factory=tuple)",
        [
          ["Generated methods", "@dataclass can create __init__, __repr__, and equality from declared fields."],
          ["Safe defaults", "default_factory creates a fresh mutable value for each instance."],
          ["Value semantics", "frozen records communicate that instances are values rather than mutable services."],
        ],
        "Using a mutable object as a direct default, which would otherwise be shared by instances.",
        "A dataclass is a preprinted record card: declare the fields and Python fills in the standard paperwork.",
      ),
      makeTopic(
        "Collections",
        "The collections module provides specialized containers for counting, grouping, queues, and named records.",
        "Select Counter, defaultdict, deque, or ChainMap when their semantics match the problem.",
        "from collections import Counter, deque\n\ncounts = Counter([\"amber\", \"cyan\", \"amber\"])\nqueue = deque([\"scan\", \"repair\"])\nnext_task = queue.popleft()",
        [
          ["Counter", "Counter is a dictionary specialized for tallying hashable values."],
          ["defaultdict", "A factory automatically creates the first value for a missing key."],
          ["deque", "A deque supports efficient additions and removals at both ends."],
        ],
        "Using defaultdict when silently creating missing entries would conceal invalid input.",
        "Specialized collections are purpose-built storage blocks: choose the shape that makes the intended operation natural.",
      ),
      makeTopic(
        "Itertools",
        "itertools supplies fast, composable building blocks for finite and infinite iterator pipelines.",
        "Combine, slice, group, and create products lazily without writing manual loop machinery.",
        "from itertools import chain, islice, product\n\nsignals = chain([\"amber\"], [\"cyan\", \"violet\"])\nfirst_two = list(islice(signals, 2))\ncoords = list(product(range(2), repeat=2))",
        [
          ["Lazy composition", "Most itertools functions return iterators and avoid materializing intermediate lists."],
          ["Finite boundaries", "islice and takewhile safely bound streams, including potentially infinite ones."],
          ["Combinatorics", "product, permutations, and combinations express structured choices precisely."],
        ],
        "Passing an infinite iterator into an eager consumer such as list() without a stopping condition.",
        "itertools is a box of conveyor-belt adapters: connect them to reshape a stream without unloading it.",
      ),
      makeTopic(
        "Functools",
        "functools provides higher-order tools for caching, adaptation, ordering, and callable composition.",
        "Apply cache, partial, reduce, singledispatch, or total_ordering where each simplifies a clear abstraction.",
        "from functools import cache, partial\n\n@cache\ndef paths(steps):\n    return 1 if steps < 2 else paths(steps - 1) + paths(steps - 2)\n\ndef power(base, exponent):\n    return base**exponent\n\nsquare = partial(power, exponent=2)",
        [
          ["Caching", "cache and lru_cache reuse results for repeated calls with hashable arguments."],
          ["Partial application", "partial pre-fills selected arguments to create a specialized callable."],
          ["Generic dispatch", "singledispatch selects implementations according to the first argument's type."],
        ],
        "Caching a function whose result depends on hidden mutable state, producing stale answers.",
        "functools is a callable workshop: it modifies how functions are stored, supplied, reused, or selected.",
      ),
      makeTopic(
        "Pythonic coding",
        "Pythonic code uses the language's idioms to communicate intent directly and readably.",
        "Replace index-heavy or ceremonial code with iteration, unpacking, truthiness, and standard helpers.",
        "names = [\"Nova\", \"Kiro\"]\nscores = [80, 95]\nfor rank, (name, score) in enumerate(zip(names, scores), start=1):\n    print(rank, name, score)",
        [
          ["Direct iteration", "Iterate over values or pairs instead of manually managing indexes."],
          ["EAFP", "When appropriate, attempt the operation and handle the specific expected exception."],
          ["Clarity over cleverness", "Idioms should reduce mental load, not demonstrate obscure language tricks."],
        ],
        "Compressing code until it is technically idiomatic but no longer obvious to the team maintaining it.",
        "Pythonic style is taking the well-marked trail: the route fits the landscape and other Python travelers recognize it.",
      ),
      makeTopic(
        "Testing",
        "Automated tests turn expected behavior into executable checks that make change safer.",
        "Arrange inputs, act once, assert outcomes, and cover boundaries and failures with isolated tests.",
        "def add_xp(current, earned):\n    return max(0, current + earned)\n\ndef test_xp_cannot_be_negative():\n    assert add_xp(5, -10) == 0",
        [
          ["Behavior contracts", "A test states what observers should see, not the implementation steps used."],
          ["Test isolation", "Each test controls its inputs and leaves no state that changes another test."],
          ["Test pyramid", "Many fast unit tests support fewer integration and end-to-end tests."],
        ],
        "Mocking every collaborator so heavily that the test proves the mocks agree but not that real pieces integrate.",
        "A test suite is a safety net woven from examples of promises the program must keep.",
      ),
      makeTopic(
        "Logging",
        "Logging emits structured operational records with severity and context for later diagnosis.",
        "Configure a module logger, choose useful levels, and include identifiers without exposing secrets.",
        "import logging\n\nlogger = logging.getLogger(__name__)\nlogger.info(\"quest_completed\", extra={\"quest_id\": 7, \"player_id\": \"p42\"})",
        [
          ["Severity levels", "DEBUG through CRITICAL distinguish diagnostic detail from urgent failure."],
          ["Context", "Stable fields such as request or player IDs connect events across a workflow."],
          ["Configuration boundary", "Applications configure handlers and formats; libraries simply obtain loggers."],
        ],
        "Using print statements for production diagnosis or logging credentials and personal information.",
        "Logs are a ship's journal: timestamped facts make a past journey reconstructable.",
      ),
      makeTopic(
        "HTTP",
        "HTTP is a request-response protocol where methods, URLs, headers, status codes, and bodies carry meaning.",
        "Construct a request, interpret status categories, and handle timeouts and transport failures.",
        "from urllib.request import urlopen\n\nwith urlopen(\"https://example.com\", timeout=5) as response:\n    status = response.status\n    body = response.read().decode(\"utf-8\")",
        [
          ["Request anatomy", "A method and URL identify the action and resource; headers and body add context."],
          ["Response semantics", "Status codes communicate outcome separately from the returned representation."],
          ["Network uncertainty", "Timeouts, retries, and partial failures are normal concerns rather than edge cases."],
        ],
        "Making a network request without a timeout, allowing a stalled service to block work indefinitely.",
        "HTTP is a formal courier exchange: the envelope describes the request and the reply carries both status and contents.",
      ),
      makeTopic(
        "APIs",
        "An API defines a stable contract through which software requests capabilities or data from another system.",
        "Consume a JSON API with authentication, validation, pagination, and explicit error handling.",
        "import requests\n\nresponse = requests.get(\"https://api.example.com/quests\", timeout=5)\nresponse.raise_for_status()\nquests = response.json().get(\"items\", [])",
        [
          ["Contract", "Endpoints specify inputs, outputs, errors, and compatibility expectations."],
          ["Authentication", "Tokens or credentials identify and authorize a caller and must remain secret."],
          ["Pagination and limits", "Large collections arrive in pages and services may restrict request rates."],
        ],
        "Trusting every successful JSON response to contain the expected fields and types without validation.",
        "An API is a service counter: request from the published menu and verify the labeled package you receive.",
      ),
      makeTopic(
        "FastAPI",
        "FastAPI builds typed ASGI web APIs from route functions and data models.",
        "Define request and response schemas, inject dependencies, and return intentional HTTP errors.",
        "from fastapi import FastAPI\nfrom pydantic import BaseModel\n\napp = FastAPI()\n\nclass Quest(BaseModel):\n    title: str\n\n@app.post(\"/quests\", response_model=Quest)\nasync def create_quest(quest: Quest) -> Quest:\n    return quest",
        [
          ["Schema validation", "Pydantic models parse and validate boundary data before route logic uses it."],
          ["Dependency injection", "Depends makes shared authentication, database, and configuration needs explicit."],
          ["ASGI execution", "async routes can efficiently await non-blocking I/O when dependencies support it."],
        ],
        "Marking a route async while calling blocking database or network libraries inside it.",
        "FastAPI is a guarded gateway: schemas inspect arrivals, dependencies prepare services, and routes coordinate the visit.",
      ),
      makeTopic(
        "SQL",
        "SQL declares how relational rows should be selected, combined, aggregated, and changed.",
        "Write parameterized queries, joins, grouping, transactions, and constraints from Python.",
        "import sqlite3\n\nconnection = sqlite3.connect(\"quests.db\")\nrows = connection.execute(\n    \"SELECT title FROM quests WHERE xp >= ? ORDER BY xp DESC\",\n    (100,),\n).fetchall()",
        [
          ["Relational shape", "Tables contain rows governed by columns, keys, and constraints."],
          ["Declarative queries", "Describe the desired result and let the database plan how to obtain it."],
          ["Parameters", "Bound parameters keep data separate from SQL syntax and prevent injection."],
        ],
        "Building SQL by concatenating user input, which creates correctness and security vulnerabilities.",
        "SQL is a request to a librarian: describe the records and relationships needed, not every shelf-walking step.",
      ),
      makeTopic(
        "ORM",
        "An object-relational mapper connects application models and relationships to relational tables and queries.",
        "Map a model, manage a session and transaction, and know when to inspect or write direct SQL.",
        "from sqlalchemy import String, select\nfrom sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column\n\nclass Base(DeclarativeBase):\n    pass\n\nclass Quest(Base):\n    __tablename__ = \"quest\"\n    id: Mapped[int] = mapped_column(primary_key=True)\n    title: Mapped[str] = mapped_column(String(120))\n\nstatement = select(Quest).where(Quest.title == \"Functions\")",
        [
          ["Identity mapping", "A session coordinates database rows with in-memory model instances."],
          ["Relationships", "ORM metadata can express foreign-key associations and loading strategies."],
          ["Unit of work", "Changes are collected and committed together within an explicit transaction boundary."],
        ],
        "Accessing relationships in a loop without noticing an extra query per row, known as the N+1 problem.",
        "An ORM is a bilingual map: models describe the application landscape while mappings connect them to relational terrain.",
      ),
      makeTopic(
        "DSA",
        "Intermediate data structures and algorithms support priority, connectivity, efficient lookup, and ordered processing.",
        "Implement and analyze stacks, queues, heaps, linked structures, and graph representations.",
        "import heapq\n\nmissions = []\nheapq.heappush(missions, (2, \"build shelter\"))\nheapq.heappush(missions, (1, \"find food\"))\npriority, mission = heapq.heappop(missions)",
        [
          ["Invariants", "Each structure maintains rules that make selected operations efficient."],
          ["Abstract interface", "A stack or priority queue is defined by behavior, not one implementation."],
          ["Complexity budget", "Input size and operation frequency determine whether asymptotic gains matter."],
        ],
        "Memorizing implementations without understanding the invariant each operation must preserve.",
        "A data structure is an engineered building: its internal supports make certain entrances and routes fast.",
      ),
      makeTopic(
        "Trees/Graphs",
        "Trees and graphs represent hierarchical or networked relationships between nodes.",
        "Model adjacency and traverse it with depth-first or breadth-first search while preventing revisits.",
        "from collections import deque\n\ngraph = {\"A\": [\"B\", \"C\"], \"B\": [\"D\"], \"C\": [], \"D\": []}\nqueue, seen = deque([\"A\"]), {\"A\"}\nwhile queue:\n    node = queue.popleft()\n    for neighbor in graph[node]:\n        if neighbor not in seen:\n            seen.add(neighbor)\n            queue.append(neighbor)",
        [
          ["Nodes and edges", "Nodes represent entities and edges represent directed or undirected relationships."],
          ["Traversal", "DFS explores depth; BFS explores layers and finds shortest paths in unweighted graphs."],
          ["Visited state", "A seen set prevents cycles from causing repeated work or infinite traversal."],
        ],
        "Applying tree assumptions to a general graph and forgetting that cycles or multiple parents may exist.",
        "A graph is a map of rooms and doors; traversal chooses how to explore while marking rooms already visited.",
      ),
      makeTopic(
        "Algorithms",
        "Algorithms are precise strategies whose correctness and efficiency can be reasoned about independently of one input.",
        "Select searching, sorting, divide-and-conquer, greedy, or dynamic techniques and justify correctness.",
        "def binary_search(values, target):\n    low, high = 0, len(values) - 1\n    while low <= high:\n        middle = (low + high) // 2\n        if values[middle] == target:\n            return middle\n        if values[middle] < target:\n            low = middle + 1\n        else:\n            high = middle - 1\n    return -1",
        [
          ["Preconditions", "Algorithms rely on stated conditions, such as sorted input for binary search."],
          ["Invariant", "A fact preserved by every step provides a backbone for correctness reasoning."],
          ["Strategy choice", "Input shape and constraints guide the appropriate algorithmic family."],
        ],
        "Using a remembered algorithm without verifying that its preconditions match the actual data.",
        "An algorithm is a route with guarantees: assumptions define the terrain, and invariants keep every turn valid.",
      ),
      makeTopic(
        "Memory concepts",
        "Python variables reference objects whose identity, mutability, sharing, and lifetime affect program behavior.",
        "Reason about aliases, shallow versus deep copies, object identity, and garbage-collection eligibility.",
        "from copy import deepcopy\n\noriginal = {\"tools\": [\"field scanner\"]}\nclone = deepcopy(original)\nclone[\"tools\"].append(\"repair tool\")\nassert original != clone",
        [
          ["References", "Assignment copies an object reference, not necessarily the object itself."],
          ["Mutability", "Shared mutable objects reveal changes through every alias pointing to them."],
          ["Copy depth", "A shallow copy duplicates the outer container; a deep copy recursively duplicates contents."],
        ],
        "Using is to compare equal values; identity and equality answer different questions.",
        "Names are arrows pointing to objects: copying an arrow does not duplicate the target it points toward.",
      ),
      makeTopic(
        "Hashing",
        "Hashing converts a stable key into an integer used by dictionaries and sets to locate values efficiently.",
        "Identify hashable values, maintain equality/hash consistency, and analyze collision-aware lookup.",
        "coordinates = {(10, 64, -2): \"relay station\"}\nlocation = coordinates.get((10, 64, -2))\nprint(hash((10, 64, -2)), location)",
        [
          ["Hashability", "A hashable object has a stable hash and compatible equality behavior for its lifetime."],
          ["Buckets and collisions", "Different keys may share a hash, so containers still compare candidates for equality."],
          ["Average lookup", "Well-distributed hashes support average constant-time membership and access."],
        ],
        "Using a mutable list as a dictionary key or changing fields that determine a custom key's hash.",
        "A hash is a shelf locator: it narrows the search quickly, while equality confirms the exact item.",
      ),
      makeTopic(
        "Concurrency intro",
        "Concurrency lets multiple tasks make progress during overlapping time, especially while work is waiting on I/O.",
        "Distinguish concurrency from parallelism and choose threads, processes, or asyncio for the workload.",
        "from concurrent.futures import ThreadPoolExecutor\nfrom urllib.request import urlopen\n\ndef size(url):\n    with urlopen(url, timeout=5) as response:\n        return len(response.read())\n\nwith ThreadPoolExecutor(max_workers=4) as pool:\n    sizes = list(pool.map(size, [\"https://example.com\"] * 2))",
        [
          ["Workload type", "I/O-bound work waits on external systems; CPU-bound work spends time computing."],
          ["Execution models", "Threads share memory, processes isolate memory, and asyncio cooperatively schedules coroutines."],
          ["Coordination cost", "Shared state, scheduling, serialization, and failure handling add complexity."],
        ],
        "Adding concurrency before measuring a bottleneck, making a simple program slower and harder to reason about.",
        "Concurrency is a cook rotating among simmering dishes; parallelism is several cooks working at the same instant.",
      ),
      makeTopic(
        "Project structure",
        "Project structure turns a growing codebase into clear packages with deliberate boundaries and tooling configuration.",
        "Organize source, tests, configuration, and entry points using a modern src layout and pyproject.toml.",
        "# src/codecraft/services.py\ndef award_xp(current: int, earned: int) -> int:\n    return current + earned\n\n# tests/test_services.py\nfrom codecraft.services import award_xp",
        [
          ["Package boundary", "A package exposes cohesive capabilities and hides replaceable implementation details."],
          ["Src layout", "Keeping importable code under src helps tests use the installed package consistently."],
          ["Configuration", "pyproject.toml centralizes build metadata and many development-tool settings."],
        ],
        "Using the project root as a miscellaneous folder until imports depend on the current working directory.",
        "A project is a town: packages are districts, public interfaces are roads, and configuration is the zoning plan.",
      ),
      makeTopic(
        "PostgreSQL",
        "PostgreSQL is a production relational database with rich types, transactions, indexes, and concurrency control.",
        "Connect safely, parameterize queries, scope transactions, and use PostgreSQL-specific capabilities deliberately.",
        "import psycopg\n\nwith psycopg.connect(\"dbname=codecraft\") as connection:\n    with connection.cursor() as cursor:\n        cursor.execute(\n            \"SELECT title FROM quest WHERE xp >= %s\",\n            (100,),\n        )\n        titles = [row[0] for row in cursor.fetchall()]",
        [
          ["Transactions", "A transaction groups statements into one atomic, consistent unit of work."],
          ["Constraints and types", "Database-enforced rules protect data across every application client."],
          ["Indexes", "Indexes accelerate selected access patterns while adding storage and write cost."],
        ],
        "Holding a transaction open across slow network or user interactions and creating unnecessary contention.",
        "PostgreSQL is a shared ledger: transactions reserve a coherent page, constraints enforce rules, and indexes speed lookup.",
      ),
    ],
  },
  {
    id: "expert",
    label: "Expert",
    tagline: "Engineer Python systems from runtime to production.",
    description:
      "Explore Python's object and runtime machinery, design resilient production systems, and make informed performance, security, and architecture decisions.",
    recommendedFor:
      "Experienced Python developers preparing to own production services, platforms, libraries, or specialized technical systems.",
    estimatedLevel: "Production Python experience",
    topics: [
      makeTopic(
        "Object model",
        "Python's object model unifies values, functions, classes, and modules as objects governed by types and attribute lookup.",
        "Trace object creation and attribute resolution across instances, classes, descriptors, and the method resolution order.",
        "class Beacon:\n    power = 1\n\nbeacon = Beacon()\nbeacon.color = \"blue\"\nprint(type(beacon), beacon.__dict__, Beacon.__mro__)",
        [
          ["Everything is an object", "Runtime values carry identity, a type, and behavior exposed through that type."],
          ["Class-instance relationship", "Instances hold per-object state while their class supplies shared attributes and methods."],
          ["Attribute resolution", "Lookup considers data descriptors, instance storage, class hierarchy, and fallback hooks in a defined order."],
        ],
        "Treating classes as compile-time templates instead of live runtime objects that can be inspected and modified.",
        "The object model is a chain of delegation: an instance searches increasingly shared neighborhoods until an attribute is found.",
      ),
      makeTopic(
        "Dunder methods",
        "Double-underscore methods connect custom objects to Python's syntax, built-ins, and data-model protocols.",
        "Implement only the protocols a type genuinely supports while preserving their documented semantic expectations.",
        "class Toolkit:\n    def __init__(self, items):\n        self._items = list(items)\n\n    def __len__(self):\n        return len(self._items)\n\n    def __iter__(self):\n        return iter(self._items)\n\n    def __repr__(self):\n        return f\"Toolkit({self._items!r})\"",
        [
          ["Protocol integration", "len(), iteration, comparison, arithmetic, and context management delegate to dunder methods."],
          ["Semantic contracts", "Implementations should behave like the familiar built-in protocol they join."],
          ["Not direct calls", "Application code normally uses syntax or built-ins rather than invoking dunder methods explicitly."],
        ],
        "Implementing __eq__ or ordering inconsistently with hashing and creating surprising container behavior.",
        "Dunder methods are standardized ports: matching a port lets an object plug into Python's existing controls.",
      ),
      makeTopic(
        "Descriptors",
        "Descriptors customize attribute access by defining __get__, __set__, or __delete__ on a class attribute.",
        "Build a validating descriptor and explain its precedence, naming, and interaction with instance dictionaries.",
        "class Positive:\n    def __set_name__(self, owner, name):\n        self.storage_name = f\"_{name}\"\n\n    def __get__(self, instance, owner=None):\n        return self if instance is None else getattr(instance, self.storage_name)\n\n    def __set__(self, instance, value):\n        if value <= 0:\n            raise ValueError(\"must be positive\")\n        setattr(instance, self.storage_name, value)",
        [
          ["Managed attributes", "A descriptor centralizes reusable access, validation, conversion, or lazy loading."],
          ["Data precedence", "A descriptor defining __set__ or __delete__ takes precedence over an instance attribute."],
          ["Binding behavior", "Functions are descriptors, which is why accessing a method through an instance binds self."],
        ],
        "Storing descriptor-managed data under the public attribute name and recursively triggering the descriptor forever.",
        "A descriptor is a customs desk on an attribute route: every read or write passes through its policy.",
      ),
      makeTopic(
        "Metaclasses",
        "A metaclass is the type responsible for constructing and configuring class objects.",
        "Explain type's role, create a narrowly scoped registry metaclass, and prefer simpler class hooks when sufficient.",
        "class Registered(type):\n    registry = {}\n\n    def __new__(mcls, name, bases, namespace):\n        cls = super().__new__(mcls, name, bases, namespace)\n        if name != \"Handler\":\n            mcls.registry[name] = cls\n        return cls\n\nclass Handler(metaclass=Registered):\n    pass",
        [
          ["Classes are instances", "Most class objects are instances of type, just as regular objects are instances of classes."],
          ["Creation pipeline", "A metaclass can prepare namespaces, create a class, validate it, and initialize it."],
          ["Simpler alternatives", "Class decorators and __init_subclass__ often solve registration or validation with less machinery."],
        ],
        "Using a metaclass for ordinary instance behavior and introducing conflicts when multiple class hierarchies combine.",
        "A metaclass is a factory inspector for blueprints: it checks and registers classes before any instances exist.",
      ),
      makeTopic(
        "Memory internals",
        "Python memory behavior emerges from object headers, references, allocators, container storage, and implementation details.",
        "Measure object size carefully, reason about aliases and reference counts, and distinguish logical from resident memory.",
        "import sys\n\nvalues = [1, 2, 3]\nalias = values\nprint(id(values) == id(alias))\nprint(sys.getsizeof(values), sys.getrefcount(values))",
        [
          ["Object layout", "CPython objects carry metadata such as type and reference-count information alongside payload."],
          ["Allocator layers", "CPython manages small-object arenas and may retain freed memory for later reuse."],
          ["Measurement limits", "getsizeof reports an object's direct footprint, not every referenced child or process overhead."],
        ],
        "Interpreting id() as a permanent memory address or getsizeof() as total transitive memory use.",
        "Memory is a warehouse of linked crates: a container's label and frame are separate from the crates it references.",
      ),
      makeTopic(
        "Garbage collection",
        "CPython reclaims most objects with reference counting and supplements it with a collector for reference cycles.",
        "Identify object reachability and cycles, use weak references, and investigate leaks before tuning collection.",
        "import gc\nimport weakref\n\nclass Node:\n    pass\n\nnode = Node()\nobserver = weakref.ref(node)\ndel node\ngc.collect()\nassert observer() is None",
        [
          ["Reference counting", "An object is normally finalized when no strong references remain."],
          ["Cycle detection", "The cyclic collector finds unreachable groups that still reference one another."],
          ["Weak references", "A weak reference observes an object without extending its lifetime."],
        ],
        "Calling gc.collect() repeatedly as a universal leak fix instead of finding the strong references keeping objects alive.",
        "Garbage collection is warehouse cleanup: unreferenced crates leave immediately, while tied-together abandoned crates need a special sweep.",
      ),
      makeTopic(
        "GIL/runtime model",
        "In standard CPython builds, the global interpreter lock coordinates execution of Python bytecode among threads.",
        "Predict how the GIL affects CPU and I/O workloads and choose an execution model based on measurement and runtime version.",
        "from concurrent.futures import ThreadPoolExecutor\nfrom time import sleep\n\ndef wait_for_io(delay):\n    sleep(delay)\n    return delay\n\nwith ThreadPoolExecutor() as pool:\n    results = list(pool.map(wait_for_io, [0.1, 0.1, 0.1]))",
        [
          ["Bytecode coordination", "The GIL traditionally allows one thread at a time to execute Python bytecode in a process."],
          ["I/O overlap", "Threads remain effective when operations release the GIL while waiting on external work."],
          ["Runtime evolution", "GIL behavior is an implementation and build concern, so assumptions should be version-aware."],
        ],
        "Saying the GIL makes all threading useless or assuming C extensions always hold it during heavy work.",
        "The GIL is a shared workshop key: threads take turns at the Python bench but can wait elsewhere simultaneously.",
      ),
      makeTopic(
        "Advanced threading",
        "Advanced threading coordinates shared-memory workers with locks, conditions, events, local state, and managed pools.",
        "Protect invariants with minimal critical sections and design shutdown, cancellation, and exception propagation.",
        "from threading import Lock\n\nclass Counter:\n    def __init__(self):\n        self._value = 0\n        self._lock = Lock()\n\n    def increment(self):\n        with self._lock:\n            self._value += 1",
        [
          ["Atomic invariants", "A lock protects a related state transition, not merely one syntactic line."],
          ["Coordination primitives", "Events signal state, conditions wait for predicates, and semaphores cap access."],
          ["Lifecycle", "Reliable thread systems define ownership, exception reporting, and graceful termination."],
        ],
        "Holding a non-reentrant lock while calling unknown code that may block or attempt to acquire the same lock.",
        "Thread synchronization is traffic control at shared intersections: narrow, explicit signals prevent collisions and gridlock.",
      ),
      makeTopic(
        "Multiprocessing",
        "Multiprocessing uses separate interpreter processes to achieve isolation and CPU parallelism at serialization cost.",
        "Use process pools safely, choose data transfer boundaries, and manage startup, failures, and shared resources.",
        "from concurrent.futures import ProcessPoolExecutor\n\ndef square(number):\n    return number * number\n\nif __name__ == \"__main__\":\n    with ProcessPoolExecutor() as pool:\n        results = list(pool.map(square, range(6)))",
        [
          ["Separate memory", "Processes do not share ordinary Python objects, reducing races but requiring communication."],
          ["Serialization", "Pool tasks and results generally cross boundaries through pickling."],
          ["Startup modes", "spawn, fork, and forkserver carry different platform and inherited-state implications."],
        ],
        "Omitting the main guard, which can recursively create processes on spawn-based platforms.",
        "Multiprocessing is a team of separate workshops: work can happen truly in parallel, but materials must be shipped between them.",
      ),
      makeTopic(
        "Advanced Asyncio",
        "Advanced asyncio structures large numbers of cooperative I/O tasks with explicit lifetimes, cancellation, and backpressure.",
        "Use TaskGroup, timeout scopes, semaphores, queues, and cancellation-safe cleanup.",
        "import asyncio\n\nasync def fetch(name):\n    await asyncio.sleep(0.1)\n    return name\n\nasync def main():\n    async with asyncio.TaskGroup() as group:\n        tasks = [group.create_task(fetch(name)) for name in (\"a\", \"b\")]\n    return [task.result() for task in tasks]\n\nasyncio.run(main())",
        [
          ["Structured concurrency", "A task group ties child-task completion and failure to a visible parent scope."],
          ["Cooperative cancellation", "Cancellation arrives at await points and cleanup should re-raise it after restoring invariants."],
          ["Backpressure", "Bounded concurrency and queues keep producers from overwhelming downstream capacity."],
        ],
        "Creating background tasks without retaining ownership, observing their exceptions, or defining when they must finish.",
        "An event loop is a stage manager: tasks yield during waits, and structured scopes ensure every performer leaves with the scene.",
      ),
      makeTopic(
        "Advanced typing",
        "Advanced typing describes reusable relationships with protocols, type variables, generics, overloads, and narrowing.",
        "Model behavior structurally and preserve type relationships across generic APIs without escaping to Any.",
        "from typing import Protocol, TypeVar\n\nclass HasName(Protocol):\n    name: str\n\nT = TypeVar(\"T\", bound=HasName)\n\ndef by_name(items: list[T]) -> dict[str, T]:\n    return {item.name: item for item in items}",
        [
          ["Structural subtyping", "A protocol accepts any value with the required behavior, without nominal inheritance."],
          ["Generic relationships", "Type variables connect input and output types more precisely than broad unions."],
          ["Narrowing", "Type guards and control flow refine a broad value into a safe, specific type."],
        ],
        "Adding casts or Any to silence the checker without proving the runtime assumption they conceal.",
        "Advanced types are algebra for contracts: they describe how shapes and relationships flow through an API.",
      ),
      makeTopic(
        "Production APIs",
        "Production APIs combine stable contracts with authentication, validation, idempotency, rate limits, and operational safety.",
        "Design versionable resources and consistent failures while separating transport, application, and persistence layers.",
        "from fastapi import Header, HTTPException\n\nasync def require_idempotency_key(\n    idempotency_key: str | None = Header(default=None),\n):\n    if not idempotency_key:\n        raise HTTPException(400, \"Idempotency-Key required\")\n    return idempotency_key",
        [
          ["Stable contracts", "Compatibility policy covers schemas, status codes, side effects, and deprecation windows."],
          ["Idempotency", "A retried mutation with the same key should not create duplicate business effects."],
          ["Failure design", "Consistent error envelopes and correlation IDs make failures actionable for clients and operators."],
        ],
        "Treating a successful HTTP response as the only design goal while ignoring retries, duplicate requests, and partial failure.",
        "A production API is a public border crossing: contracts, identity checks, receipts, and repeat-entry rules must all be dependable.",
      ),
      makeTopic(
        "PostgreSQL engineering",
        "PostgreSQL engineering aligns schemas, indexes, query plans, isolation, pooling, and migrations with real workloads.",
        "Read EXPLAIN plans, design composite indexes, manage contention, and evolve schemas without unsafe downtime.",
        "query = \"\"\"\nEXPLAIN (ANALYZE, BUFFERS)\nSELECT player_id, SUM(xp)\nFROM completion\nWHERE completed_at >= %s\nGROUP BY player_id\n\"\"\"\ncursor.execute(query, (cutoff,))",
        [
          ["Query plans", "EXPLAIN ANALYZE reveals chosen access paths, row estimates, actual work, and buffer use."],
          ["Concurrency control", "Isolation and locking determine which interleavings transactions can observe."],
          ["Operational evolution", "Backward-compatible expand-and-contract migrations avoid coordinating an instant global switch."],
        ],
        "Adding indexes based only on individual columns instead of the query's filters, ordering, selectivity, and write cost.",
        "A database is a busy city: schemas set laws, indexes build express routes, and transactions control intersection safety.",
      ),
      makeTopic(
        "Caching",
        "Caching trades freshness and complexity for faster access by keeping reusable results closer to consumers.",
        "Choose cache keys and TTLs, implement cache-aside safely, and plan invalidation, stampede control, and failure modes.",
        "from functools import lru_cache\n\n@lru_cache(maxsize=512)\ndef badge_rules(badge_id: str) -> tuple[str, ...]:\n    return tuple(load_badge_rules(badge_id))",
        [
          ["Locality and keys", "A useful key uniquely represents every input that can change the cached result."],
          ["Freshness policy", "TTL, explicit invalidation, or versioned keys define when stale data is replaced."],
          ["Stampede control", "Coalescing, jitter, or leases prevent many misses from recomputing the same value simultaneously."],
        ],
        "Caching a result without including tenant, authorization, locale, or another behavior-changing input in its key.",
        "A cache is a nearby data relay: fast to reach, but someone must keep its labels and contents current.",
      ),
      makeTopic(
        "Queues",
        "Queues decouple producers and consumers so work can be buffered, retried, prioritized, and processed asynchronously.",
        "Design message schemas, acknowledgment and retry behavior, idempotent consumers, and dead-letter handling.",
        "import asyncio\n\nasync def worker(queue):\n    while True:\n        job = await queue.get()\n        try:\n            await process(job)\n        finally:\n            queue.task_done()",
        [
          ["Delivery semantics", "At-most-once, at-least-once, and effectively-once designs carry distinct tradeoffs."],
          ["Acknowledgment", "A message is removed only according to the broker's success and timeout policy."],
          ["Poison messages", "Bounded retries and dead-letter queues isolate work that repeatedly fails."],
        ],
        "Assuming a message is delivered exactly once and making a consumer unsafe to retry.",
        "A queue is a loading dock: producers leave labeled crates, consumers claim them, and receipts govern redelivery.",
      ),
      makeTopic(
        "Docker",
        "Docker packages an application and its user-space dependencies into a reproducible container image.",
        "Write a secure multi-stage-friendly image, control build context, and run configuration outside the image.",
        "FROM python:3.13-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nUSER 10001\nCMD [\"python\", \"-m\", \"codecraft\"]",
        [
          ["Image layers", "Stable dependency steps placed early improve build-cache reuse."],
          ["Runtime boundary", "Images contain code and dependencies; secrets and environment configuration arrive at runtime."],
          ["Least privilege", "Small bases, pinned inputs, and non-root users reduce unnecessary attack surface."],
        ],
        "Copying the whole repository before dependency installation and baking secrets or local artifacts into image layers.",
        "A container image is a sealed expedition crate: reproducible supplies inside, destination-specific instructions outside.",
      ),
      makeTopic(
        "CI/CD",
        "Continuous integration validates every change, while continuous delivery moves verified artifacts through controlled release stages.",
        "Design a pipeline with deterministic checks, immutable artifacts, gated deployment, and safe rollback.",
        "name: verify\non: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: python -m pip install -r requirements.txt\n      - run: python -m pytest",
        [
          ["Fast feedback", "Cheap formatting, type, and unit checks should fail before slower integration work."],
          ["Artifact promotion", "Build once and promote the same immutable artifact between environments."],
          ["Deployment safety", "Health checks, canaries, feature flags, and rollback limit the blast radius."],
        ],
        "Rebuilding separately for production, so the deployed artifact is not the one the pipeline actually tested.",
        "CI/CD is a guarded railway: checks inspect the cargo, one sealed carriage advances, and gates control each station.",
      ),
      makeTopic(
        "Cloud",
        "Cloud platforms expose managed compute, storage, networking, and identity that applications compose under elastic failure-prone conditions.",
        "Design a stateless service, externalize configuration, and select managed resources with cost and resilience awareness.",
        "import os\n\nDATABASE_URL = os.environ[\"DATABASE_URL\"]\nREGION = os.getenv(\"REGION\", \"local\")\n\ndef health():\n    return {\"status\": \"ok\", \"region\": REGION}",
        [
          ["Ephemeral compute", "Instances can be replaced, so durable state belongs in external managed storage."],
          ["Shared responsibility", "Providers secure underlying infrastructure while teams still secure configuration and workloads."],
          ["Elastic economics", "Autoscaling improves responsiveness but requires quotas, cost controls, and load-aware design."],
        ],
        "Treating a cloud virtual machine like a permanent hand-maintained server with local-only state.",
        "The cloud is a utility grid: consume managed capabilities through contracts and design for individual stations to be replaced.",
      ),
      makeTopic(
        "Security",
        "Application security protects confidentiality, integrity, and availability through layered design and continuous verification.",
        "Threat-model trust boundaries, validate input, enforce authorization, protect secrets, and manage dependency risk.",
        "import secrets\n\ndef can_edit(user, quest):\n    return user.is_admin or quest.owner_id == user.id\n\ncsrf_token = secrets.token_urlsafe(32)\nif not can_edit(current_user, quest):\n    raise PermissionError(\"not authorized\")",
        [
          ["Authentication vs authorization", "Identity establishes who acts; authorization decides whether that identity may perform this action."],
          ["Input and output boundaries", "Validate untrusted data and encode output for its destination context."],
          ["Defense in depth", "Least privilege, secure defaults, monitoring, and patching prevent one failure from becoming total compromise."],
        ],
        "Checking only that a user is signed in without verifying access to the specific resource being changed.",
        "Security is a castle of layered gates: each trust boundary verifies identity, intent, and permitted movement.",
      ),
      makeTopic(
        "Observability",
        "Observability combines logs, metrics, and traces to explain a system's internal state from its outputs.",
        "Instrument requests with correlated context, service-level indicators, spans, and actionable alert thresholds.",
        "import logging\nfrom time import perf_counter\n\nlogger = logging.getLogger(__name__)\nstarted = perf_counter()\ntry:\n    result = handle(request)\nfinally:\n    logger.info(\"request_finished\", extra={\"elapsed_ms\": (perf_counter() - started) * 1000})",
        [
          ["Three signals", "Logs record events, metrics summarize trends, and traces connect work across services."],
          ["Service objectives", "SLIs and SLOs turn user-facing reliability into measurable engineering targets."],
          ["Cardinality discipline", "Unbounded labels can make telemetry expensive and operationally unusable."],
        ],
        "Collecting large volumes of telemetry without consistent identifiers, questions, retention, or alerts.",
        "Observability is a system's instrument panel and flight recorder: it shows current health and reconstructs the journey.",
      ),
      makeTopic(
        "Performance",
        "Performance engineering measures real workloads, identifies limiting resources, and optimizes the highest-impact path.",
        "Profile CPU and wall time, benchmark carefully, reduce algorithmic work, and verify gains against regression risk.",
        "from cProfile import Profile\nfrom pstats import SortKey, Stats\n\nwith Profile() as profile:\n    run_workload()\nStats(profile).sort_stats(SortKey.CUMULATIVE).print_stats(10)",
        [
          ["Measure first", "Profiling locates expensive call paths that intuition often misidentifies."],
          ["Representative workload", "Input size, data distribution, warmup, and environment determine whether a benchmark is meaningful."],
          ["Whole-system tradeoff", "Latency, throughput, memory, cost, and maintainability can pull in different directions."],
        ],
        "Micro-optimizing a frequently visible line without proving it contributes materially to end-to-end cost.",
        "Performance work is finding a river's narrowest channel: widening somewhere else does not increase total flow.",
      ),
      makeTopic(
        "CPython internals",
        "CPython turns source into code objects evaluated by frames while managing objects through C-level runtime structures.",
        "Inspect frames and code objects and connect Python behavior to evaluation, allocation, and extension boundaries.",
        "import sys\n\ndef inspect_call(value):\n    frame = sys._getframe()\n    return {\n        \"function\": frame.f_code.co_name,\n        \"locals\": dict(frame.f_locals),\n        \"implementation\": sys.implementation.name,\n    }\n\nprint(inspect_call(42))",
        [
          ["Compilation pipeline", "CPython parses source, builds an AST, and emits code objects containing bytecode and metadata."],
          ["Evaluation frames", "Each active call has a frame linking code, local/global namespaces, and execution state."],
          ["Implementation boundary", "Reference counting, object layout, and extension APIs are CPython details rather than universal language guarantees."],
        ],
        "Depending on an observed CPython optimization as though the Python language specification guaranteed it.",
        "CPython is a theater backstage: source is the script, code objects are cues, frames are live scenes, and the evaluator runs them.",
      ),
      makeTopic(
        "Bytecode",
        "Python bytecode is the instruction representation stored in code objects and executed by CPython's evaluation loop.",
        "Disassemble functions, relate instructions to source constructs, and avoid treating version-specific opcodes as stable APIs.",
        "import dis\n\ndef total(values):\n    return sum(value * 2 for value in values)\n\ndis.dis(total)\nprint(total.__code__.co_names)",
        [
          ["Code objects", "Functions reference immutable code objects containing instructions, constants, names, and source metadata."],
          ["Stack machine", "Many bytecode operations move values through an evaluation stack."],
          ["Adaptive execution", "Modern CPython may specialize instructions at runtime according to observed values."],
        ],
        "Comparing bytecode instruction counts across Python releases as a reliable measure of real performance.",
        "Bytecode is a stage cue sheet: lower-level than the script, but still interpreted by the runtime crew.",
      ),
      makeTopic(
        "AST",
        "The abstract syntax tree represents Python source as structured semantic nodes before bytecode generation.",
        "Parse, inspect, transform, validate, and compile an AST while preserving locations and security boundaries.",
        "import ast\n\ntree = ast.parse(\"reward = base + bonus\")\nassignments = [node for node in ast.walk(tree) if isinstance(node, ast.Assign)]\ncompiled = compile(tree, filename=\"<lesson>\", mode=\"exec\")\nnamespace = {\"base\": 10, \"bonus\": 5}\nexec(compiled, namespace)",
        [
          ["Semantic structure", "AST nodes represent constructs such as calls, names, branches, and comprehensions rather than raw text."],
          ["Transformation", "NodeVisitor inspects trees and NodeTransformer can replace nodes before compilation."],
          ["Untrusted execution", "Parsing is not sandboxing; compiling or evaluating untrusted trees still executes dangerous code."],
        ],
        "Using regular expressions to rewrite Python syntax when nesting and language grammar require structural parsing.",
        "An AST is a building blueprint: decoration is removed so rooms, connections, and structural changes are explicit.",
      ),
      makeTopic(
        "Architecture",
        "Software architecture organizes responsibilities and dependency direction so a system can change without widespread coordination.",
        "Separate domain policy from delivery and infrastructure using explicit ports, adapters, and bounded contexts.",
        "from typing import Protocol\n\nclass QuestStore(Protocol):\n    def completed(self, player_id: str) -> int: ...\n\ndef rank_player(player_id: str, store: QuestStore) -> str:\n    return \"expert\" if store.completed(player_id) >= 20 else \"learner\"",
        [
          ["Dependency direction", "Stable domain policy should not import volatile frameworks or infrastructure details."],
          ["Boundaries", "Interfaces make ownership, data flow, and substitution points visible."],
          ["Architectural fitness", "Automated checks and review practices keep intended constraints true as code evolves."],
        ],
        "Creating layers named after technical patterns while business rules still depend directly on framework and database objects.",
        "Architecture is a city's road plan: boundaries direct traffic so one neighborhood can change without rebuilding every street.",
      ),
      makeTopic(
        "Distributed systems",
        "Distributed systems coordinate independent nodes across unreliable networks without shared instantaneous state.",
        "Design for timeouts, retries, duplication, ordering, consistency tradeoffs, and partial failure.",
        "import random\nimport time\n\ndef with_retry(operation, attempts=4):\n    for attempt in range(attempts):\n        try:\n            return operation()\n        except TimeoutError:\n            if attempt == attempts - 1:\n                raise\n            time.sleep((2**attempt + random.random()) / 10)",
        [
          ["Partial failure", "One component may fail or become unreachable while the rest of the system continues."],
          ["Consistency choices", "Replication and partition behavior determine when different nodes observe the same state."],
          ["Idempotent recovery", "Retries are safer when duplicate delivery cannot repeat the business effect."],
        ],
        "Retrying every error immediately and indefinitely, amplifying overload into a cascading failure.",
        "A distributed system is an expedition communicating by delayed radio: messages can be lost, repeated, reordered, or misunderstood.",
      ),
      makeTopic(
        "Design patterns",
        "Design patterns name recurring collaboration structures and the tradeoffs they address.",
        "Apply strategy, adapter, factory, observer, and related patterns only when they simplify a real variation point.",
        "from typing import Protocol\n\nclass RewardPolicy(Protocol):\n    def reward(self, base: int) -> int: ...\n\nclass DoubleWeekend:\n    def reward(self, base: int) -> int:\n        return base * 2\n\ndef award(base: int, policy: RewardPolicy) -> int:\n    return policy.reward(base)",
        [
          ["Problem vocabulary", "A pattern gives teams a shared name for a known arrangement and its intent."],
          ["Variation points", "Strategy or factory isolates behavior expected to vary independently."],
          ["Tradeoffs", "Every pattern adds structure, so its flexibility must repay the added indirection."],
        ],
        "Starting with a pattern diagram and forcing a simple problem into it before variation or complexity exists.",
        "A design pattern is a proven construction technique, not a prefabricated building that fits every site.",
      ),
      makeTopic(
        "Package design",
        "Package design creates a small stable public API around cohesive capabilities and hides internal evolution.",
        "Define exports, dependency direction, versioning, typing, documentation, and distribution metadata.",
        "# codecraft/__init__.py\nfrom .progress import Progress, load_progress\n\n__all__ = [\"Progress\", \"load_progress\"]\n__version__ = \"1.0.0\"",
        [
          ["Public surface", "Explicit exports reduce accidental coupling to internal modules."],
          ["Compatibility", "Semantic versioning and deprecation paths communicate the impact of change."],
          ["Distribution", "pyproject metadata, wheels, and supported Python versions make installation reproducible."],
        ],
        "Exposing every internal module as public and later discovering consumers depend on implementation details.",
        "A package is a well-designed storefront: the catalog stays clear while storage and operations can change behind it.",
      ),
      makeTopic(
        "Open source",
        "Open-source engineering combines public code with licensing, governance, documentation, review, and sustainable maintenance.",
        "Evaluate a project, make a focused contribution, and communicate through issues, tests, changelogs, and review.",
        "def test_reported_edge_case():\n    # A regression test links the contribution to observable behavior.\n    assert normalize_name(\"  Nova  \") == \"Nova\"",
        [
          ["License and governance", "A license grants defined rights; governance explains how decisions and releases happen."],
          ["Contribution quality", "A focused change includes motivation, tests, documentation, and compatibility awareness."],
          ["Community maintenance", "Respectful review, issue triage, release notes, and security processes sustain a project."],
        ],
        "Submitting a broad rewrite before understanding the project's contribution guide, constraints, and maintainer priorities.",
        "Open source is a public garden: contribution means learning its rules, improving one plot, and helping others maintain it.",
      ),
      makeTopic(
        "Specialization",
        "Specialization combines deep Python foundations with a chosen domain such as web, data, automation, ML, security, or platform engineering.",
        "Choose a direction from evidence, identify domain gaps, and build a production-quality capstone that demonstrates end-to-end judgment.",
        "paths = {\n    \"web\": [\"FastAPI\", \"PostgreSQL\", \"observability\"],\n    \"data\": [\"NumPy\", \"pandas\", \"pipelines\"],\n    \"platform\": [\"containers\", \"cloud\", \"distributed systems\"],\n}\nchosen_path = paths[\"web\"]",
        [
          ["T-shaped growth", "Keep broad engineering literacy while developing unusual depth in one valuable domain."],
          ["Evidence through projects", "A capstone should solve a real problem and include tests, operations, documentation, and tradeoffs."],
          ["Continuous map", "Specialization is a direction, not an endpoint; tools change while durable principles compound."],
        ],
        "Collecting advanced tools from several domains without completing a substantial system or receiving real feedback.",
        "Specialization is choosing a domain to master after learning how to navigate the whole system.",
      ),
    ],
  },
];
