export type SQLPaceId = "beginner" | "intermediate" | "expert";

export type SQLTopic = {
  title: string;
  summary: string;
  learningGoal: string;
  example: string;
  keyIdeas: Array<{ title: string; body: string }>;
  commonMistake: string;
  mentalModel: string;
};

export type SQLPace = {
  id: SQLPaceId;
  label: string;
  tagline: string;
  description: string;
  recommendedFor: string;
  estimatedLevel: string;
  topics: SQLTopic[];
};

const makeTopic = (
  title: string,
  summary: string,
  learningGoal: string,
  example: string,
  principles: [string, string, string],
  commonMistake: string,
  mentalModel: string,
): SQLTopic => ({
  title,
  summary,
  learningGoal,
  example,
  keyIdeas: [
    { title: "Core idea", body: principles[0] },
    { title: "System view", body: principles[1] },
    { title: "Production check", body: principles[2] },
  ],
  commonMistake,
  mentalModel,
});

export const SQL_PACES: SQLPace[] = [
  {
    id: "beginner",
    label: "Beginner",
    tagline: "Build durable relational foundations.",
    description:
      "Learn how relational databases organize data, write accurate queries, enforce integrity, connect tables, and design a clean first schema.",
    recommendedFor:
      "New developers, analysts, and students who want to understand SQL from first principles with no database background assumed.",
    estimatedLevel: "No prior SQL experience",
    topics: [
      makeTopic("Database basics", "A database stores organized information so applications can create, retrieve, update, and protect it reliably.", "Distinguish databases, database management systems, relational models, schemas, and queries.", "CREATE DATABASE codecraft;\n-- connect, define a schema, then query it", ["A DBMS manages storage, concurrency, durability, and access around the data.", "Relational databases represent facts in related tables and expose them through SQL.", "Choose a database from workload, consistency, scale, and operational requirements rather than popularity."], "Treating the database as a passive file instead of a stateful service with rules and concurrent users.", "A database is the realm's durable record network; SQL is the language used to inspect and change it."),
      makeTopic("Tables/rows/columns", "A table represents one kind of entity or relationship using named columns and individual rows.", "Identify the meaning of a table, row, column, value, and schema from a real data model.", "CREATE TABLE relays (\n  relay_id bigint,\n  name text,\n  online boolean\n);", ["Columns define attributes and expected value domains.", "Each row records one occurrence of the table's subject.", "A table should have a clear purpose and a way to identify each row."], "Designing one giant table that mixes unrelated entities and repeats the same facts.", "A table is a typed signal grid: columns define channels and each row is one recorded event or entity."),
      makeTopic("Data types", "SQL data types define how values are stored, validated, compared, and processed.", "Choose appropriate numeric, text, boolean, date, timestamp, and identifier types.", "CREATE TABLE readings (\n  value numeric(10,2),\n  captured_at timestamptz,\n  valid boolean\n);", ["Types protect meaning and enable correct operators and indexes.", "Precision, range, timezone, and length requirements matter more than habit.", "Conversions can add cost or cause surprising comparison behavior."], "Storing dates, booleans, and numbers as text because it seems flexible.", "A data type is the protocol assigned to a column; only compatible signals should enter."),
      makeTopic("CRUD", "CRUD names the four basic data operations: create, read, update, and delete.", "Map product actions to INSERT, SELECT, UPDATE, and DELETE while understanding their effects.", "INSERT INTO relays (name) VALUES ('Aurora');\nSELECT * FROM relays;\nUPDATE relays SET online = true WHERE name = 'Aurora';", ["CRUD describes data operations, not a complete security or transaction model.", "Writes should target rows deliberately and return enough information to confirm the result.", "Every destructive operation needs a precise predicate and appropriate authorization."], "Running UPDATE or DELETE without a WHERE clause and changing every row.", "CRUD is the database control panel: add, inspect, revise, or retire records."),
      makeTopic("SELECT", "SELECT describes which expressions and columns a query should return from one or more data sources.", "Write readable projections, aliases, calculated columns, and explicit column lists.", "SELECT relay_id, name, power * efficiency AS output\nFROM relays;", ["The select list controls the shape of the result.", "Aliases make calculated or renamed fields understandable to callers.", "Explicit columns create a more stable application contract than SELECT *."], "Using SELECT * in production code and accidentally depending on column order or newly added fields.", "SELECT tunes the receiver to the exact channels needed from the data grid."),
      makeTopic("WHERE", "WHERE filters candidate rows using boolean conditions.", "Combine comparisons, ranges, membership, patterns, and boolean logic with correct NULL behavior.", "SELECT relay_id, name\nFROM relays\nWHERE online = true AND power >= 80;", ["Only rows whose predicate evaluates to true survive the filter.", "AND, OR, and NOT require careful precedence and parentheses.", "Predicates affect both correctness and whether indexes can be used efficiently."], "Writing mixed AND and OR conditions without parentheses and retrieving unintended rows.", "WHERE is a signal gate that passes only records satisfying its rule."),
      makeTopic("ORDER BY", "ORDER BY defines the sequence of result rows using one or more sort expressions.", "Sort ascending or descending, add deterministic tie-breakers, and control NULL placement.", "SELECT name, power\nFROM relays\nORDER BY power DESC, relay_id ASC;", ["SQL result order is unspecified unless ORDER BY is present.", "Multiple sort keys resolve ties from left to right.", "Large sorts can require memory, temporary storage, or a supporting index."], "Assuming rows naturally remain in insertion or primary-key order.", "ORDER BY is the routing queue that places returned signals into a deliberate sequence."),
      makeTopic("LIMIT", "LIMIT restricts how many rows a query returns, often after sorting.", "Use LIMIT with deterministic ordering and explain its role in previews and pagination.", "SELECT relay_id, name\nFROM relays\nORDER BY created_at DESC, relay_id DESC\nLIMIT 20;", ["LIMIT applies after the query's logical filtering and ordering stages.", "A stable ORDER BY prevents rows from changing position unpredictably.", "LIMIT reduces returned rows but does not automatically make an inefficient query fast."], "Using LIMIT without ORDER BY and expecting the same rows on every run.", "LIMIT closes the output channel after a chosen number of ordered records."),
      makeTopic("DISTINCT", "DISTINCT removes duplicate result rows based on every selected expression.", "Choose between DISTINCT, grouping, and better schema/query logic when duplicates appear.", "SELECT DISTINCT sector\nFROM relays\nORDER BY sector;", ["Distinctness applies to the complete selected row, not one column in isolation.", "Duplicates can be legitimate results of joins or a symptom of an incorrect relationship.", "Deduplication may require sorting or hashing and can hide modeling mistakes."], "Adding DISTINCT to silence duplicate rows without understanding which join created them.", "DISTINCT is a deduplication relay that keeps one copy of each output signal pattern."),
      makeTopic("Aggregates", "Aggregate functions summarize many input rows into values such as counts, totals, averages, minima, and maxima.", "Use COUNT, SUM, AVG, MIN, and MAX and predict their behavior with NULL values.", "SELECT COUNT(*) AS relay_count,\n       AVG(power) AS average_power\nFROM relays;", ["COUNT(*) counts rows while COUNT(column) counts non-NULL values.", "Most aggregates ignore NULL inputs.", "Aggregation changes result granularity from individual rows to summaries."], "Using COUNT(column) when the requirement is to count all rows, including rows where that column is NULL.", "An aggregate compresses a stream of records into one measured signal."),
      makeTopic("GROUP BY", "GROUP BY divides rows into groups and calculates aggregates separately for each group.", "Choose grouping keys and ensure every selected expression is grouped or aggregated.", "SELECT sector, COUNT(*) AS relay_count\nFROM relays\nGROUP BY sector;", ["Grouping keys define the result's granularity.", "Each group produces one result row.", "Adding a grouping column can dramatically change the meaning and size of the result."], "Selecting an ungrouped, non-aggregated column and expecting the database to choose a representative value.", "GROUP BY routes records into labeled sector queues before measuring each queue."),
      makeTopic("HAVING", "HAVING filters groups after aggregation, while WHERE filters rows before grouping.", "Place row predicates and aggregate predicates in the correct query stage.", "SELECT sector, AVG(power) AS avg_power\nFROM relays\nWHERE online = true\nGROUP BY sector\nHAVING AVG(power) >= 80;", ["WHERE reduces rows before aggregates are calculated.", "HAVING can refer to aggregate conditions.", "Filtering early usually reduces work when the predicate applies to individual rows."], "Putting a simple row filter in HAVING and forcing unnecessary grouping work.", "WHERE guards incoming signals; HAVING inspects the completed group summaries."),
      makeTopic("NULL", "NULL represents missing or unknown information and follows three-valued SQL logic.", "Test NULL with IS NULL, understand UNKNOWN, and use COALESCE only when a replacement is semantically correct.", "SELECT relay_id, COALESCE(last_error, 'none') AS status\nFROM relays\nWHERE repaired_at IS NULL;", ["NULL is not equal to anything, including another NULL.", "Predicates can evaluate to true, false, or unknown.", "Missing, empty, zero, and not applicable are different meanings."], "Writing column = NULL instead of column IS NULL.", "NULL is an absent signal, not an ordinary value with a known identity."),
      makeTopic("CASE", "CASE adds conditional logic to SQL expressions and produces one value from the first matching branch.", "Create derived categories, conditional values, and safe fallback branches.", "SELECT name,\n  CASE WHEN power >= 90 THEN 'critical'\n       WHEN power >= 60 THEN 'stable'\n       ELSE 'weak' END AS tier\nFROM relays;", ["CASE branches are evaluated in order.", "Every branch should return compatible data types.", "Conditional labels belong in queries only when that logic is appropriate at the data boundary."], "Placing a broad condition before a more specific condition so later branches can never match.", "CASE is a classification relay assigning one output state to each incoming record."),
      makeTopic("Primary keys", "A primary key uniquely and permanently identifies each row in a table.", "Choose stable key columns and explain uniqueness, non-nullability, and surrogate versus natural keys.", "CREATE TABLE relays (\n  relay_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  name text NOT NULL\n);", ["A primary key enforces one identity per row.", "Keys should remain stable when ordinary attributes change.", "Surrogate keys simplify references, while natural keys can enforce real-world uniqueness separately."], "Using a mutable value such as an email address or display name as the only row identity.", "A primary key is the permanent address assigned to one record in the realm."),
      makeTopic("Foreign keys", "A foreign key ensures a value refers to an existing row in another table.", "Create references, choose update/delete actions, and understand when checks occur.", "CREATE TABLE readings (\n  reading_id bigint PRIMARY KEY,\n  relay_id bigint REFERENCES relays(relay_id)\n);", ["Foreign keys preserve referential integrity between related tables.", "ON DELETE and ON UPDATE actions encode lifecycle behavior.", "Indexes on referencing columns are often needed for joins and parent-row changes."], "Removing foreign keys for convenience and allowing orphaned records to accumulate.", "A foreign key is a verified link from one record address to another."),
      makeTopic("Constraints", "Constraints enforce valid data at the database boundary through NOT NULL, UNIQUE, CHECK, primary keys, and foreign keys.", "Translate business invariants into declarative constraints and choose useful constraint names.", "CREATE TABLE batteries (\n  battery_id bigint PRIMARY KEY,\n  charge integer NOT NULL CHECK (charge BETWEEN 0 AND 100),\n  serial text UNIQUE\n);", ["Constraints protect every writer, not only one application path.", "Declarative rules are easier to inspect and harder to bypass than scattered checks.", "Constraint failures should be translated into clear application errors."], "Relying exclusively on frontend validation for data that multiple services can write.", "Constraints are invariant sensors at the entrance to persistent storage."),
      makeTopic("Relationships", "Relationships describe how entities connect: one-to-one, one-to-many, or many-to-many.", "Model cardinality with foreign keys, uniqueness, and junction tables.", "CREATE TABLE team_members (\n  team_id bigint REFERENCES teams(team_id),\n  member_id bigint REFERENCES members(member_id),\n  PRIMARY KEY (team_id, member_id)\n);", ["Cardinality comes from business rules, not diagram aesthetics.", "Many-to-many relationships need an associative table.", "Relationship tables can store facts about the connection itself."], "Placing comma-separated foreign IDs in one text column instead of modeling a relationship table.", "Relationships are typed routes connecting stable record addresses."),
      makeTopic("JOINs", "JOIN combines rows from related sources using an explicit matching condition.", "Use INNER and LEFT JOIN correctly and predict the result cardinality.", "SELECT r.name, s.name AS sector_name\nFROM relays r\nJOIN sectors s ON s.sector_id = r.sector_id;", ["The ON clause states how rows relate.", "INNER JOIN keeps matches; LEFT JOIN preserves every left row.", "One-to-many joins repeat the parent row once for each matching child."], "Joining on similarly named columns without verifying that they represent the same key relationship.", "A join follows verified routes between tables to assemble a wider record."),
      makeTopic("Subqueries", "A subquery is a query nested inside another statement and can produce a scalar, row, table, or set.", "Use scalar and IN/EXISTS subqueries and match the operator to the subquery's result shape.", "SELECT name\nFROM relays\nWHERE sector_id IN (\n  SELECT sector_id FROM sectors WHERE region = 'north'\n);", ["The inner query creates a value or relation consumed by the outer query.", "EXISTS checks whether any matching row exists.", "A subquery can often be expressed as a join, but the clearest correct form should win."], "Using = with a subquery that can return multiple rows.", "A subquery sends a focused scout query whose result guides the outer mission."),
      makeTopic("String functions", "String functions clean, combine, search, and transform textual values inside a query.", "Use concatenation, LOWER, UPPER, TRIM, LENGTH, REPLACE, and pattern operations carefully.", "SELECT relay_id,\n       upper(trim(name)) AS normalized_name\nFROM relays\nWHERE lower(name) LIKE 'aurora%';", ["String functions return transformed values without changing stored data unless used in a write.", "Case conversion and pattern matching can affect index use.", "Application and database normalization rules should agree."], "Applying a function to every indexed value in a filter and unintentionally preventing a normal index lookup.", "String functions are signal processors that reshape text as it passes through the query."),
      makeTopic("Date functions", "Date and time functions calculate intervals, truncate periods, extract components, and convert time zones.", "Work safely with dates, timestamps, intervals, current time, and reporting periods.", "SELECT date_trunc('day', captured_at) AS day,\n       COUNT(*)\nFROM readings\nGROUP BY day;", ["A date lacks time; a timestamp may or may not include timezone semantics.", "Store real instants consistently and convert for presentation.", "Calendar arithmetic differs from fixed-duration arithmetic."], "Storing local timestamps without timezone context and comparing records from different regions.", "Time functions align event signals onto a shared timeline for analysis."),
      makeTopic("Basic schema design", "Basic schema design turns product concepts into focused tables with identities, types, constraints, and relationships.", "Sketch a small relational schema, identify entities and facts, and test it against common reads and writes.", "relays(relay_id PK, sector_id FK, name, status)\nreadings(reading_id PK, relay_id FK, value, captured_at)", ["Each table should represent one clear entity or relationship.", "Store each fact once when practical and connect it through keys.", "Validate the design against real queries, update rules, and lifecycle events."], "Designing tables from screen layouts instead of stable domain concepts and invariants.", "A schema is the realm map defining record types, addresses, and legal routes."),
    ],
  },
  {
    id: "intermediate",
    label: "Intermediate",
    tagline: "Engineer analytical and transactional SQL.",
    description:
      "Master advanced queries, CTEs, analytical functions, normalization, indexes, transactions, PostgreSQL features, application access, and optimization.",
    recommendedFor:
      "Developers and analysts comfortable with SELECT, joins, grouping, subqueries, and basic relational design.",
    estimatedLevel: "Comfortable with core SQL",
    topics: [
      makeTopic("Advanced JOINs", "Advanced joins solve self-reference, range matching, anti-joins, lateral dependencies, and multi-table cardinality challenges.", "Use self, cross, full, lateral, semi, and anti-join patterns while predicting result size.", "SELECT r.name, prev.name AS predecessor\nFROM relays r\nLEFT JOIN relays prev ON prev.relay_id = r.predecessor_id;", ["Join type expresses which unmatched rows survive.", "LATERAL lets a right-side query refer to each left row.", "Cardinality estimation starts with understanding uniqueness on every join key."], "Stacking joins until results look right without checking row multiplication at each step.", "Advanced joins route records through specialized merge junctions."),
      makeTopic("Advanced subqueries", "Advanced subqueries use correlation, EXISTS, quantified comparisons, and nested relations to express dependent logic.", "Write correlated subqueries and choose among EXISTS, IN, ANY, ALL, joins, and windows.", "SELECT r.name\nFROM relays r\nWHERE EXISTS (\n  SELECT 1 FROM alerts a\n  WHERE a.relay_id = r.relay_id AND a.open\n);", ["A correlated subquery depends on values from the outer row.", "EXISTS can stop after finding one qualifying row.", "The optimizer may transform equivalent forms, but clarity and NULL semantics still differ."], "Using NOT IN with a subquery that may return NULL and unexpectedly matching nothing.", "A correlated subquery launches a targeted inspection for each candidate record."),
      makeTopic("CTEs", "A common table expression names an intermediate relation for readability and composition within one statement.", "Use WITH to structure multi-stage transformations and understand materialization behavior.", "WITH active_relays AS (\n  SELECT * FROM relays WHERE online\n)\nSELECT sector_id, COUNT(*) FROM active_relays GROUP BY sector_id;", ["CTEs create named query stages, not permanent tables.", "Modern optimizers may inline eligible CTEs.", "A CTE should clarify logic rather than fragment a simple query unnecessarily."], "Assuming every CTE automatically improves performance or is always materialized.", "A CTE labels an intermediate signal channel so later stages can reuse it clearly."),
      makeTopic("Recursive CTEs", "A recursive CTE repeatedly expands from anchor rows until no new recursive rows are produced.", "Traverse hierarchies and graphs with anchors, recursive terms, depth tracking, and cycle protection.", "WITH RECURSIVE tree AS (\n  SELECT relay_id, parent_id, 0 AS depth FROM relays WHERE parent_id IS NULL\n  UNION ALL\n  SELECT r.relay_id, r.parent_id, t.depth + 1 FROM relays r JOIN tree t ON r.parent_id = t.relay_id\n)\nSELECT * FROM tree;", ["The anchor seeds the result; the recursive term expands from prior output.", "UNION ALL is typical, but cycles need explicit detection.", "Depth and path columns make traversal behavior inspectable."], "Running recursion over cyclic data without a depth bound or visited-path check.", "A recursive CTE sends a signal outward one relationship layer at a time."),
      makeTopic("Window functions", "Window functions calculate across related rows while preserving every input row.", "Use OVER, PARTITION BY, ordering, frames, ranking, offsets, and running aggregates.", "SELECT relay_id, sector_id, power,\n       rank() OVER (PARTITION BY sector_id ORDER BY power DESC) AS sector_rank\nFROM relays;", ["Partitions define independent calculation groups.", "Window ordering controls sequence inside each partition.", "Frame clauses determine which neighboring rows feed an aggregate."], "Confusing window ORDER BY with the final display order or accepting an unintended default frame.", "A window function overlays analytical signals without collapsing the underlying records."),
      makeTopic("Set operations", "UNION, INTERSECT, and EXCEPT combine compatible query results using set semantics.", "Align result columns and choose duplicate-preserving or duplicate-removing operations.", "SELECT relay_id FROM active_relays\nUNION ALL\nSELECT relay_id FROM standby_relays;", ["Both inputs need the same column count and compatible types.", "UNION removes duplicates; UNION ALL preserves them and is usually cheaper.", "INTERSECT keeps shared rows while EXCEPT keeps rows only in the first input."], "Using UNION by default when duplicates are valid and paying an unnecessary deduplication cost.", "Set operations merge or compare complete signal streams."),
      makeTopic("Advanced aggregation", "Advanced aggregation includes filtered aggregates, multiple grouping levels, statistical functions, and ordered aggregates.", "Use FILTER, GROUPING SETS, ROLLUP, CUBE, and conditional aggregation.", "SELECT sector_id,\n  COUNT(*) FILTER (WHERE online) AS online_count,\n  percentile_cont(0.95) WITHIN GROUP (ORDER BY latency_ms) AS p95\nFROM relays GROUP BY sector_id;", ["FILTER gives each aggregate an independent row condition.", "Grouping sets produce several summary granularities in one scan.", "Statistical aggregates require enough data and clear NULL handling."], "Repeating large CASE expressions inside aggregates when FILTER would be clearer.", "Advanced aggregation measures several signal dimensions during one pass through the grid."),
      makeTopic("Views", "A view stores a query definition and exposes it like a table without storing its result separately.", "Create stable data interfaces and understand permissions, dependencies, and update limitations.", "CREATE VIEW active_relay_summary AS\nSELECT relay_id, name, sector_id\nFROM relays WHERE online;", ["Views centralize reusable query logic and can restrict exposed columns.", "Normal views run their underlying query when referenced.", "Schema changes and nested views can create hidden dependency complexity."], "Treating a view as a performance cache or building deep layers of opaque views.", "A view is a named observation window onto live underlying records."),
      makeTopic("Materialized views", "A materialized view stores a query result and refreshes it explicitly, trading freshness for faster reads.", "Choose refresh strategies, indexes, and consistency expectations for expensive derived data.", "CREATE MATERIALIZED VIEW sector_metrics AS\nSELECT sector_id, COUNT(*) FROM relays GROUP BY sector_id;\nREFRESH MATERIALIZED VIEW sector_metrics;", ["Materialized results can be indexed like stored relations.", "Refresh cost and staleness must match product requirements.", "Concurrent refresh has prerequisites and different locking behavior."], "Serving stale materialized data without exposing its refresh time or freshness contract.", "A materialized view is a captured signal snapshot that must be deliberately recharged."),
      makeTopic("Normalization", "Normalization reduces update anomalies by separating facts according to keys and dependencies.", "Apply first, second, and third normal form pragmatically and recognize justified denormalization.", "sectors(sector_id PK, name UNIQUE)\nrelays(relay_id PK, sector_id FK, name)", ["A column should describe the key, the whole key, and nothing but the key.", "Normalization prevents one fact from needing inconsistent updates in many rows.", "Denormalization is a measured read optimization with a synchronization plan."], "Repeating descriptive data across rows because joins initially seem inconvenient.", "Normalization assigns each fact one authoritative relay address."),
      makeTopic("Schema design", "Schema design balances domain meaning, integrity, query patterns, lifecycle rules, and future change.", "Model entities, events, states, histories, ownership, and boundaries from real workflows.", "relay_events(event_id PK, relay_id FK, event_type, occurred_at, payload)", ["State tables answer the present; event tables preserve what happened over time.", "Ownership and tenant boundaries should be visible in keys and constraints.", "Design reviews should walk through writes, reads, deletions, and migrations."], "Optimizing a schema for one dashboard while making writes and future requirements fragile.", "Schema design is the structural blueprint for how the realm remembers and evolves."),
      makeTopic("Indexes", "An index is an auxiliary data structure that speeds selected lookups and ordering at the cost of storage and write work.", "Choose indexed columns, order, uniqueness, partial predicates, expressions, and included data.", "CREATE INDEX relays_sector_power_idx\nON relays (sector_id, power DESC)\nWHERE online;", ["B-tree indexes support equality, ranges, and ordered scans.", "Column order follows query predicates and sorting needs.", "Every index must justify its write amplification and maintenance cost."], "Creating one index per column without matching actual multi-column query patterns.", "An index is a compact navigation grid pointing to table records."),
      makeTopic("EXPLAIN ANALYZE", "EXPLAIN ANALYZE executes a query and reports the chosen plan with actual timing and row counts.", "Read scan, join, sort, aggregate, loop, buffer, and estimation information safely.", "EXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT)\nSELECT * FROM relays WHERE sector_id = 42;", ["Estimated rows versus actual rows reveal statistics or correlation problems.", "Time on parent nodes includes child work, so plans must be read as trees.", "ANALYZE runs the statement and can change data for writes."], "Running EXPLAIN ANALYZE on a destructive production statement without a safe transaction.", "EXPLAIN ANALYZE is the query flight recorder showing the route actually traveled."),
      makeTopic("Transactions", "A transaction groups database operations into one atomic unit that commits together or rolls back together.", "Use BEGIN, COMMIT, ROLLBACK, and savepoints while keeping transactions focused.", "BEGIN;\nUPDATE accounts SET balance = balance - 50 WHERE account_id = 1;\nUPDATE accounts SET balance = balance + 50 WHERE account_id = 2;\nCOMMIT;", ["Atomicity protects multi-statement invariants.", "Transactions hold snapshots and may hold locks until completion.", "Application error handling must always commit or roll back deliberately."], "Keeping a transaction open while waiting for user input or remote network calls.", "A transaction is a sealed mission: every required change lands together or none do."),
      makeTopic("ACID", "ACID describes transaction guarantees: atomicity, consistency, isolation, and durability.", "Connect each guarantee to database mechanisms and application responsibilities.", "BEGIN;\n-- all invariant-preserving changes\nCOMMIT;", ["Atomicity prevents partial committed work.", "Consistency combines database constraints with correct transaction logic.", "Isolation and durability have configurable implementation and operational tradeoffs."], "Assuming ACID means every business rule is automatically correct or every transaction behaves serially.", "ACID is the four-part stability protocol protecting database state transitions."),
      makeTopic("Isolation levels", "Isolation levels control which concurrent effects a transaction can observe and which anomalies are prevented.", "Compare read committed, repeatable read, and serializable behavior and choose by invariant.", "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;\nSELECT ...;\nUPDATE ...;", ["Read committed takes a new snapshot per statement in PostgreSQL.", "Repeatable read holds a transaction snapshot but concurrent writes can still conflict.", "Serializable may abort transactions that must be retried."], "Choosing a stronger isolation level without adding application retry handling.", "Isolation defines how much each concurrent mission can see of the others."),
      makeTopic("Locks", "Locks coordinate concurrent access to database objects and rows when operations could conflict.", "Recognize row and table locks, lock modes, wait behavior, and explicit locking patterns.", "SELECT * FROM jobs\nWHERE status = 'queued'\nFOR UPDATE SKIP LOCKED\nLIMIT 1;", ["Writes acquire locks automatically.", "Lock order influences deadlock risk.", "NOWAIT and SKIP LOCKED suit specific queue and contention patterns."], "Using SELECT FOR UPDATE broadly and serializing work that could proceed concurrently.", "Locks are temporary access signals guarding records during sensitive transitions."),
      makeTopic("Functions/procedures", "Database functions and procedures package reusable logic close to data with different transaction and return behaviors.", "Choose SQL functions, procedural functions, or procedures and define stable interfaces.", "CREATE FUNCTION relay_count(p_sector bigint)\nRETURNS bigint LANGUAGE sql STABLE AS\n'SELECT count(*) FROM relays WHERE sector_id = p_sector';", ["Functions can return scalar, row, or set results.", "Volatility categories inform optimization and correctness.", "Database logic should protect data-centric invariants without absorbing unrelated product behavior."], "Moving all application logic into stored procedures and creating hard-to-version coupling.", "A database function is a trusted operation installed beside the record grid."),
      makeTopic("Triggers", "A trigger runs database code automatically in response to insert, update, delete, or truncate events.", "Use triggers sparingly for auditing, derived values, or invariants and understand timing and recursion.", "CREATE TRIGGER audit_relay_changes\nAFTER UPDATE ON relays\nFOR EACH ROW EXECUTE FUNCTION record_relay_audit();", ["BEFORE triggers can modify or reject rows; AFTER triggers observe completed row changes.", "Row triggers run once per row while statement triggers run once per statement.", "Hidden side effects require documentation, tests, and monitoring."], "Using triggers for complex workflows that callers cannot see or reason about.", "A trigger is an automatic sensor activated when a record crosses a defined boundary."),
      makeTopic("JSON/JSONB", "PostgreSQL JSON and JSONB store semi-structured documents while supporting extraction, containment, and indexing.", "Choose relational columns versus JSONB, query paths, and create targeted JSON indexes.", "SELECT payload->>'status' AS status\nFROM relay_events\nWHERE payload @> '{\"severity\":\"high\"}'::jsonb;", ["JSONB is decomposed and indexable; JSON preserves input text formatting.", "Frequently constrained or joined attributes often deserve typed columns.", "Document shape still needs application validation and migration strategy."], "Putting an entire mutable domain model into one JSONB column to avoid schema design.", "JSONB is a flexible payload channel attached to a relationally identified record."),
      makeTopic("Application DB access", "Application database access manages connections, parameters, transactions, result mapping, and errors across a driver or data layer.", "Use parameterized queries, bounded pools, transaction scopes, timeouts, and error translation.", "row = db.query_one('SELECT * FROM relays WHERE relay_id = $1', [relay_id])", ["Parameters separate query structure from untrusted values.", "Connections are finite resources and should be returned promptly.", "Timeouts and cancellation prevent abandoned work from consuming capacity."], "Building SQL with string interpolation or opening a new physical connection for every request.", "The database access layer is the guarded gateway between application missions and persistent records."),
      makeTopic("ORM", "An object-relational mapper translates application models and operations into SQL while managing identity and relationships.", "Use an ORM without losing visibility into generated queries, transactions, and schema behavior.", "relay = session.query(Relay).where(Relay.id == relay_id).one()", ["ORMs reduce repetitive mapping but do not remove relational semantics.", "Eager, lazy, and explicit loading create different query patterns.", "Migrations and constraints remain database responsibilities."], "Treating ORM calls as free in-memory operations and ignoring the generated SQL.", "An ORM is a translation layer, not a replacement for understanding the database language."),
      makeTopic("N+1 problem", "The N+1 problem occurs when code loads a list with one query and then issues another query for each row.", "Detect N+1 traces and fix them using joins, eager loading, batching, or prefetching.", "relays = load_relays_with_sector()\n-- one bounded query instead of one sector lookup per relay", ["Network round trips often dominate the cost of many tiny queries.", "The right fix depends on result size and relationship cardinality.", "Query-count tests and traces can catch regressions."], "Fixing N+1 by eager-loading a huge relationship graph on every request.", "N+1 is a relay repeatedly returning to the archive for records it could collect in one trip."),
      makeTopic("Security", "Database security applies least privilege, authentication, encryption, row boundaries, safe queries, and auditable administration.", "Design roles, grants, secrets, network controls, row-level security, and secure operational access.", "GRANT SELECT, INSERT ON relay_events TO app_writer;\nREVOKE ALL ON relays FROM PUBLIC;", ["Application roles need only the actions required by their workload.", "Parameterized queries stop data from becoming executable SQL structure.", "Backups, replicas, logs, and admin tools are part of the data security perimeter."], "Running the application with a database owner or superuser credential.", "Database security places independent authorization gates around every record route."),
      makeTopic("PostgreSQL deeper", "PostgreSQL combines a rich SQL engine with MVCC, extensible types, operators, indexes, and operational catalogs.", "Navigate schemas, extensions, system catalogs, configuration, and PostgreSQL-specific capabilities deliberately.", "SELECT schemaname, tablename\nFROM pg_catalog.pg_tables\nWHERE schemaname NOT IN ('pg_catalog', 'information_schema');", ["Schemas provide namespaces and access boundaries inside one database.", "Extensions add trusted capabilities but become lifecycle dependencies.", "System catalogs reveal metadata and runtime state needed for operations."], "Using PostgreSQL-specific features accidentally without documenting portability and operational dependencies.", "PostgreSQL is an extensible record engine with a visible control and metadata plane."),
      makeTopic("Query optimization", "Query optimization improves SQL, schema, statistics, and indexes based on measured execution plans and workload goals.", "Establish a baseline, identify the dominant cost, change one factor, and verify the result under realistic data.", "EXPLAIN (ANALYZE, BUFFERS)\nSELECT ...;\n-- compare plan, rows, reads, and latency after one change", ["Optimize user-visible workload outcomes rather than isolated syntax.", "Cardinality errors often lead the optimizer toward poor plans.", "A faster read can increase write cost, storage, or operational complexity."], "Guessing at indexes or rewriting queries without capturing a plan and representative benchmark.", "Optimization tunes the route with the largest measured signal delay."),
    ],
  },
  {
    id: "expert",
    label: "Expert",
    tagline: "Design and operate database platforms.",
    description:
      "Understand PostgreSQL execution and storage internals, concurrency, recovery, scale, availability, observability, analytical modeling, and architecture.",
    recommendedFor:
      "Senior engineers, database specialists, and architects responsible for high-scale or high-reliability data platforms.",
    estimatedLevel: "Production database experience",
    topics: [
      makeTopic("Query optimizer", "The query optimizer explores legal plan alternatives and estimates their cost from statistics, configuration, and physical properties.", "Reason about search space, cardinality, cost parameters, path selection, and plan stability.", "EXPLAIN (COSTS, VERBOSE)\nSELECT ...;", ["SQL is declarative; the optimizer chooses physical operators and order.", "Cardinality estimates influence nearly every cost decision.", "Statistics, parameterization, and data correlation can change chosen plans."], "Trying to force a preferred plan before identifying why the optimizer estimated the alternatives incorrectly.", "The optimizer is the route planner comparing many legal paths through the record network."),
      makeTopic("Execution internals", "The executor runs a physical plan as a tree of nodes that produce tuples through scans, joins, sorts, and aggregates.", "Trace tuple flow, node loops, memory contexts, parallel workers, and instrumentation.", "EXPLAIN (ANALYZE, BUFFERS, VERBOSE, SETTINGS)\nSELECT ...;", ["Plan nodes request rows from child nodes and transform or combine them.", "Loops multiply per-loop work and explain many hidden costs.", "Materialization, spills, and parallel coordination affect runtime behavior."], "Reading only the top-level execution time and ignoring node loops, rows, and buffers.", "The executor is the relay machinery physically moving tuples along the chosen plan."),
      makeTopic("Advanced EXPLAIN", "Advanced EXPLAIN analysis connects estimates, actual rows, buffers, I/O timing, memory, WAL, parallelism, and settings.", "Diagnose misestimation and resource bottlenecks while separating cold-cache, warm-cache, and concurrency effects.", "EXPLAIN (ANALYZE, BUFFERS, WAL, SETTINGS, SUMMARY)\nUPDATE ...;", ["Shared hit, read, dirtied, and written buffers reveal different work.", "Rows removed by filters expose wasted tuple processing.", "One plan capture is not a workload benchmark."], "Treating planning and execution times from one warm run as universally representative.", "Advanced EXPLAIN is the full telemetry trace for one query mission."),
      makeTopic("Join algorithms", "Nested loop, hash, and merge joins have different input, memory, ordering, and cardinality strengths.", "Predict which join algorithm fits a workload and diagnose spills or excessive rescans.", "SET LOCAL work_mem = '128MB';\nEXPLAIN (ANALYZE, BUFFERS) SELECT ... JOIN ... ON ...;", ["Nested loops excel when the outer side is small and inner lookups are cheap.", "Hash joins need build-side memory and equality conditions.", "Merge joins benefit from ordered inputs and support ordered equality processing."], "Disabling a join algorithm globally instead of fixing estimates, indexes, or memory for the affected workload.", "Join algorithms are different physical junction designs for pairing record streams."),
      makeTopic("Index internals", "PostgreSQL indexes use access methods such as B-tree, hash, GiST, SP-GiST, GIN, and BRIN with distinct structures and operators.", "Choose an access method and reason about pages, splits, visibility, deduplication, and vacuum interaction.", "CREATE INDEX events_time_brin ON relay_events USING brin (occurred_at);", ["B-tree is general purpose; other access methods target specialized data and scale patterns.", "Index-only scans still depend on visibility-map coverage.", "Index bloat and page splits reflect workload and maintenance behavior."], "Choosing an exotic index type from the data type alone without testing actual operators and selectivity.", "Index internals are specialized navigation structures laid over the storage pages."),
      makeTopic("Storage internals", "PostgreSQL stores table and index data in fixed-size pages grouped into relation files with tuple headers and auxiliary maps.", "Explain pages, heap tuples, TOAST, free-space maps, visibility maps, and relation forks.", "SELECT pg_relation_size('relays'), pg_total_relation_size('relays');", ["Heap pages hold tuple versions and metadata.", "Large values may move to TOAST storage.", "Free-space and visibility maps guide inserts, vacuum, and index-only scans."], "Reasoning about storage only from logical row sizes and ignoring tuple, page, index, and bloat overhead.", "Storage internals are the physical sectors beneath the logical record grid."),
      makeTopic("MVCC", "Multi-version concurrency control keeps multiple row versions so readers and writers can proceed with limited blocking.", "Trace snapshots, tuple visibility, transaction IDs, old versions, and cleanup requirements.", "BEGIN;\nSELECT txid_current(), * FROM relays WHERE relay_id = 42;", ["A snapshot decides which tuple versions a transaction can see.", "Updates create new tuple versions rather than overwriting in place.", "Long-running transactions prevent cleanup of versions they might still need."], "Assuming MVCC removes all locks or that old row versions disappear immediately.", "MVCC gives each mission a consistent view of the record timeline."),
      makeTopic("Vacuum", "VACUUM reclaims reusable space, maintains visibility information, and prevents transaction ID wraparound.", "Tune autovacuum from table workload, monitor progress and dead tuples, and distinguish vacuum from space compaction.", "VACUUM (VERBOSE, ANALYZE) relay_events;", ["Standard vacuum marks dead space reusable inside the relation.", "Autovacuum thresholds depend on table size and change volume.", "Anti-wraparound vacuum is a correctness requirement, not optional maintenance."], "Disabling autovacuum to avoid load or expecting regular VACUUM to return all space to the operating system.", "Vacuum is the maintenance relay retiring invisible record versions and refreshing navigation signals."),
      makeTopic("Advanced transactions", "Advanced transaction design coordinates retries, savepoints, external side effects, idempotency, and long-running workflows.", "Design transactional boundaries and patterns such as outbox, inbox, advisory locks, and compensation.", "BEGIN;\nINSERT INTO orders ...;\nINSERT INTO outbox(event_type, payload) VALUES (...);\nCOMMIT;", ["A database transaction cannot atomically commit an arbitrary remote API call.", "Outbox patterns connect durable state changes to asynchronous delivery.", "Retry-safe commands need idempotency keys and clear ownership."], "Holding a database transaction open across remote calls to simulate distributed atomicity.", "Advanced transactions seal local state changes and emit durable signals for the wider system."),
      makeTopic("Deadlocks", "A deadlock occurs when transactions form a cycle of waits that cannot resolve without aborting one participant.", "Read deadlock reports, reproduce lock order, and redesign transactions to acquire resources consistently.", "BEGIN;\n-- update resources in canonical relay_id order\nUPDATE relays SET ... WHERE relay_id IN (...) ORDER BY relay_id;", ["PostgreSQL detects cycles and aborts one transaction.", "Consistent lock ordering prevents many deadlocks.", "Applications must retry aborted transactions safely."], "Increasing lock timeouts instead of removing cyclic acquisition patterns.", "A deadlock is a closed loop of missions each waiting for another to release a gate."),
      makeTopic("WAL", "Write-ahead logging records changes durably before modified data pages reach permanent storage.", "Explain WAL records, LSNs, checkpoints, archiving, full-page writes, and durability settings.", "SELECT pg_current_wal_lsn();\nCHECKPOINT;", ["Committed changes become durable through WAL flush guarantees.", "Checkpoints bound recovery work but can create I/O pressure.", "WAL volume affects replication, backups, storage, and write throughput."], "Disabling durability settings for speed without understanding the exact failure and data-loss window.", "WAL is the append-only recovery signal emitted before storage pages are allowed to change."),
      makeTopic("Recovery", "Recovery replays WAL from a consistent starting point to restore database state after failure.", "Describe crash recovery, restore recovery, timelines, recovery targets, and validation.", "restore base backup\nreplay archived WAL until target_lsn or target_time", ["Crash recovery uses local WAL after an unclean stop.", "Archive recovery combines a base backup with subsequent WAL.", "Recovery procedures must be rehearsed and measured, not merely documented."], "Assuming a successful backup guarantees recovery without performing restore tests.", "Recovery reconstructs the realm by replaying its durable change signal history."),
      makeTopic("Replication", "Replication copies changes to other database instances for availability, read scale, migration, or distribution.", "Compare physical streaming and logical replication, lag, slots, failover, and consistency.", "SELECT application_name, state, replay_lag\nFROM pg_stat_replication;", ["Physical replication follows storage-level WAL and closely mirrors the primary.", "Logical replication sends selected row changes with more topology flexibility.", "Replication is usually asynchronous, so lag and data-loss windows need explicit limits."], "Sending all reads to replicas without accounting for stale data and read-after-write requirements.", "Replication broadcasts change signals from one authoritative node to followers."),
      makeTopic("Partitioning", "Partitioning divides one logical table into physical child tables based on a key and routing rule.", "Choose range, list, or hash partitioning and plan pruning, indexes, retention, and maintenance.", "CREATE TABLE relay_events (...) PARTITION BY RANGE (occurred_at);", ["Partition pruning avoids scanning irrelevant partitions.", "The partition key must match dominant management or query boundaries.", "Too many partitions increase planning and operational overhead."], "Partitioning a table merely because it is large without a pruning or lifecycle requirement.", "Partitioning divides one record realm into separately managed sectors behind one logical interface."),
      makeTopic("Sharding", "Sharding distributes rows across independent database nodes to exceed one node's capacity or isolate workloads.", "Choose a shard key and reason about routing, resharding, cross-shard queries, and global constraints.", "shard_id = hash(tenant_id) % shard_count\nroute(shard_id, query)", ["The shard key determines locality, balance, and hotspot risk.", "Cross-shard joins and transactions add coordination cost.", "Resharding and operational tooling are part of the design from day one."], "Choosing a monotonically increasing or uneven shard key that concentrates load on one node.", "Sharding assigns record regions to independent realm nodes through a routing map."),
      makeTopic("Connection pooling", "Connection pooling multiplexes application work over a bounded number of expensive database sessions.", "Size pools from database capacity and workload, then choose session, transaction, or statement pooling.", "pool = create_pool(min_size=5, max_size=30, timeout=2)", ["More connections can reduce performance through memory and scheduler contention.", "Transaction pooling restricts session-level features.", "Pool queues and acquisition latency need monitoring."], "Setting every application instance's pool to a large number and overwhelming the database during scale-out.", "A connection pool is a bounded set of database channels shared by many application missions."),
      makeTopic("Caching architecture", "Caching architecture places reusable results at client, application, query, or derived-data layers with explicit consistency rules.", "Choose cache-aside, write-through, invalidation, TTLs, and stampede protection by data semantics.", "value = cache.get(key)\nif value is None:\n    value = database.load(key)\n    cache.set(key, value, ttl=60)", ["Cache keys need tenant, version, and query identity.", "Invalidation strategy is part of the data contract.", "Caching shifts load but adds stale-data and failure behavior."], "Caching without a freshness requirement or allowing many misses to recompute the same expensive result simultaneously.", "A cache is a nearby signal buffer whose contents must expire or invalidate correctly."),
      makeTopic("High availability", "High availability keeps database service within an agreed recovery time despite node, zone, or operational failures.", "Design redundancy, health detection, failover, fencing, routing, and recovery objectives.", "primary -> synchronous standby\n        -> asynchronous standby in second region", ["Availability architecture begins with RTO, RPO, and failure assumptions.", "Failover requires preventing the old primary from accepting conflicting writes.", "A standby is not a backup against logical corruption or deletion."], "Calling a replica high availability without automated, tested failover and client reconnection behavior.", "High availability maintains an alternate relay command node ready to assume authority safely."),
      makeTopic("Backup/PITR", "Backups and point-in-time recovery combine base backups with archived WAL to restore a chosen historical state.", "Set retention, encryption, verification, restore targets, and regular recovery drills from business requirements.", "base_backup + continuous_WAL_archive -> restore_target_time", ["Logical and physical backups solve different recovery needs.", "PITR needs an unbroken WAL archive after the base backup.", "Recovery time includes downloading, replaying, validating, and reconnecting."], "Keeping backups on the same infrastructure and never measuring a complete restore.", "PITR rebuilds the realm at a selected moment using a snapshot plus every subsequent change signal."),
      makeTopic("Monitoring", "Database monitoring tracks workload, latency, locks, connections, replication, storage, maintenance, and operating-system resources.", "Define service-level indicators and investigate using PostgreSQL statistics, logs, and query telemetry.", "SELECT queryid, calls, total_exec_time, mean_exec_time\nFROM pg_stat_statements\nORDER BY total_exec_time DESC;", ["Workload-level metrics reveal more than host utilization alone.", "Cumulative statistics need rates and time windows.", "Monitoring queries and logging must be useful without exposing sensitive data."], "Alerting on CPU alone or collecting metrics without runbooks and ownership.", "Monitoring is the sensor grid showing the health and pressure of every database subsystem."),
      makeTopic("Performance engineering", "Performance engineering measures database behavior under representative load and improves the dominant bottleneck across queries, schema, resources, and architecture.", "Create workload models, latency percentiles, throughput targets, controlled experiments, and capacity plans.", "benchmark(workload, concurrency=[1, 10, 50], dataset_scale='production-like')", ["Average latency hides tail behavior that users experience.", "Concurrency can expose contention absent from single-query tests.", "Improvements must be remeasured for reads, writes, storage, and operational cost."], "Optimizing one query on a laptop and projecting the result to production concurrency and data scale.", "Performance engineering tunes the entire relay network against a measured mission workload."),
      makeTopic("Keyset pagination", "Keyset pagination fetches the next page using the last ordered key rather than skipping an increasing number of rows.", "Build stable forward and backward pagination with composite cursors and matching indexes.", "SELECT relay_id, created_at\nFROM relays\nWHERE (created_at, relay_id) < ($1, $2)\nORDER BY created_at DESC, relay_id DESC\nLIMIT 50;", ["The cursor contains the complete deterministic ordering key.", "Seek predicates let the index resume near the desired position.", "Arbitrary page numbers are not a natural fit for keyset pagination."], "Using a non-unique sort column in the cursor and losing or repeating tied rows.", "Keyset pagination resumes the signal stream from the last verified coordinate."),
      makeTopic("OLTP vs OLAP", "OLTP workloads optimize frequent, small, concurrent transactions while OLAP workloads optimize large scans and analytical aggregation.", "Classify workload needs and separate or integrate transactional and analytical systems deliberately.", "OLTP: lookup one relay and commit a status change\nOLAP: scan years of events by region and month", ["OLTP favors low-latency indexed access and strong transactional integrity.", "OLAP favors columnar processing, large scans, and complex aggregation.", "Mixed workloads require resource isolation, replicas, or data pipelines."], "Running heavy unbounded analytical queries on the primary transactional database during peak traffic.", "OLTP operates the live relay controls; OLAP studies the historical signal field."),
      makeTopic("Dimensional modeling", "Dimensional modeling organizes analytical data into fact tables and descriptive dimensions for clear, performant reporting.", "Define grain, facts, dimensions, surrogate keys, and slowly changing dimension strategies.", "fact_readings(date_key, relay_key, sector_key, value)\ndim_relay(relay_key, relay_id, name, valid_from, valid_to)", ["The fact table's grain must be stated before choosing measures.", "Dimensions provide descriptive analysis context.", "Historical attribute changes need an explicit slowly changing strategy."], "Mixing multiple grains in one fact table and producing incorrect aggregates.", "A dimensional model is an analytical coordinate system around measurable events."),
      makeTopic("Distributed SQL", "Distributed SQL systems present relational semantics across multiple nodes using replication, consensus, and distributed transactions.", "Evaluate consistency, locality, transaction coordination, failure behavior, and operational tradeoffs.", "BEGIN;\n-- transaction spans ranges on multiple nodes\nCOMMIT; -- requires distributed agreement", ["Data placement and consensus determine latency.", "Distributed transactions pay coordination costs across failure domains.", "SQL compatibility does not guarantee identical semantics or operational behavior."], "Choosing distributed SQL for simple scale-up workloads and accepting avoidable latency and complexity.", "Distributed SQL extends one logical record realm across a coordinated node federation."),
      makeTopic("SQL vs NoSQL", "SQL and NoSQL systems offer different data models, query capabilities, consistency choices, and scaling patterns.", "Choose technology from access patterns, invariants, change rate, scale, and operational maturity.", "relational: transactions + joins + constraints\ndocument: aggregate documents + key-oriented access", ["The categories contain many distinct systems and are not strict opposites.", "Relational databases can store documents; NoSQL systems may support transactions.", "Polyglot persistence adds integration and consistency costs."], "Selecting NoSQL to avoid schema design or SQL solely because relational databases are familiar.", "SQL and NoSQL are different record engines; the mission requirements choose the engine."),
      makeTopic("Multi-tenancy", "Multi-tenancy stores data for multiple customers while preserving isolation, performance fairness, and operational manageability.", "Compare shared tables, schemas, databases, and clusters with tenant-aware keys and policies.", "CREATE POLICY tenant_isolation ON relays\nUSING (tenant_id = current_setting('app.tenant_id')::bigint);", ["Tenant identity must travel through every query and cache key.", "Row-level security can add defense in depth but requires strict session handling.", "Large or regulated tenants may need stronger physical isolation."], "Filtering by tenant only in application code and missing one query path.", "Multi-tenancy partitions one realm into independently protected customer sectors."),
      makeTopic("Zero-downtime migrations", "Zero-downtime migrations change schema and data while old and new application versions continue serving traffic.", "Use expand-contract changes, backfills, compatibility windows, validation, and safe index creation.", "ALTER TABLE relays ADD COLUMN status_v2 text;\n-- dual write, backfill in batches, validate, switch reads, later remove old column", ["Expand first so old code remains compatible.", "Large backfills need batching, throttling, and resumability.", "Constraint validation and concurrent index creation reduce blocking when used correctly."], "Renaming or dropping a column in the same release that introduces replacement application code.", "A zero-downtime migration builds a parallel signal route before retiring the old one."),
      makeTopic("Database architecture", "Database architecture aligns ownership, data models, topology, consistency, availability, security, observability, and lifecycle with product needs.", "Create an evidence-based architecture and evolution plan across transactional, analytical, and derived data systems.", "system_of_record -> outbox -> event stream -> search/cache/warehouse\n        |-> replicas and verified backups", ["Each datum needs an authoritative owner and consistency model.", "Derived stores require replay, reconciliation, and deletion strategies.", "Architecture decisions should include failure modes, operating cost, and migration paths."], "Adding databases for individual features without defining ownership, synchronization, and recovery.", "Database architecture is the complete map of authoritative records and every signal route derived from them."),
    ],
  },
];
