import { s } from "./topic";

export const INTERMEDIATE_SECURITY = [
  s("Model a feature's threats", "Identify plausible misuse before building a sharing feature.",
    "A threat model names assets, actors, entry points, and trust boundaries for one feature. It considers how a legitimate capability can be abused; it is not a catalogue of every possible vulnerability.",
    "Trace a document from creation through sharing, access, revocation, and deletion. Mark who can control links and identifiers, then choose tests for the highest-impact paths.",
    "Listing controls before naming the asset can miss the real abuse case: a revoked guest using a cached export link.",
    "Owner → create link → invited guest views document. Revoked guest → same link → denied; cached copies and logs have separate retention rules.",
    "What makes a sharing threat model reviewable?", "Actors, assets, boundaries, misuse paths, assumptions, and tests for each important decision.", "A list of security product names.", "A single green scan with no feature context.",
    "invited guest reads shared document", "revoked guest reads document", ["asset-flow-map", "revocation-policy", "misuse-test"], "revoked_link_denials", "architecture"),
  s("Prioritize controls", "Rank risks using exposure, impact, prerequisites, and control cost.",
    "Risk is contextual. A weakness in a public upload path differs from the same pattern in an unreachable test fixture. Confidence and unknowns matter, so a ranking should state the assumptions behind it.",
    "Compare plausible caller access, data sensitivity, blast radius, and ease of repair. Revisit the decision when evidence changes; a temporary mitigation needs an owner and expiry.",
    "Treating a severity label as the whole decision can defer a reachable cross-tenant leak while chasing a high-scored but unused package path.",
    "Risk A: public upload parser handles untrusted files. Risk B: local test tool has a high CVSS advisory but never ships. Investigate A first and document B's reachability.",
    "Two findings compete for one release slot. What should drive priority?", "Reachable exposure and user impact, with documented assumptions and a fix plan.", "The highest identifier number.", "Whichever change is easiest to demo.",
    "team remediates reachable exposure", "known public path remains exposed", ["reachability", "impact-estimate", "decision-record"], "unmitigated_exposed_risks", "architecture"),
  s("Web sessions and CSRF", "Match request protections to the session and browser behavior.",
    "Browsers may attach cookies automatically to requests. A forged page can exploit that ambient authority when a state-changing endpoint trusts the cookie alone. SameSite helps but does not replace a complete design for every flow.",
    "Use an appropriate SameSite mode, a CSRF token or origin checks for sensitive cookie-authenticated mutations, and server authorization on the target object. Test a legitimate form and a cross-origin submission.",
    "Switching to localStorage bearer tokens avoids one CSRF shape but exposes tokens to script injection. Security choices change the threat, not erase it.",
    "POST /payout with a valid session cookie plus a bound anti-CSRF token succeeds; an off-site form lacking the token fails before the payout changes.",
    "A state-changing endpoint accepts cookie-only POSTs from another origin. What is missing?", "A request-origin or anti-CSRF check appropriate to the cookie session.", "A prettier login form.", "More database indexes.",
    "owner submits payout change", "off-site form changes payout", ["same-site-cookie", "csrf-check", "resource-policy"], "cross_origin_mutation_denials", "web"),
  s("API authorization and abuse limits", "Protect objects and capacity without breaking normal API clients.",
    "API risks include a user reading another object, receiving excess fields, or issuing costly requests faster than the service can safely handle. Authentication alone addresses none of those fully.",
    "Authorize every requested object, return only fields needed by the caller, and use bounded limits tied to user, operation, and service capacity. Expose useful retry information for legitimate clients.",
    "A global limit on a shared IP can punish many users while one authenticated account continues abuse through distributed addresses.",
    "GET /reports/81 returns owner-visible fields only. A foreign id returns a safe denial. A burst above the account's limit receives 429 with a bounded retry hint.",
    "A signed-in client requests another tenant's report at a low rate. Which control must reject it?", "Object-level authorization, independent of rate limiting.", "A global IP rate limit only.", "A client-side hidden button.",
    "owner reads own report", "foreign client reads report", ["object-policy", "response-minimization", "account-limit"], "cross_tenant_report_denials", "web"),
  s("Project: Review a new feature", "Threat-model and test document sharing from invitation to revocation.",
    "A sharing feature crosses identity, storage, notification, and cache boundaries. Review each stage as one journey so a revoked link cannot survive through a secondary path.",
    "Write abuse cases for public links, forwarded invitations, object IDs, and stale caches. Prioritize controls, then show one allowed guest read and one revoked guest denial.",
    "Checking only the primary API leaves previews, exports, and cached copies with different authorization behavior.",
    "Invitation scoped to document 81 expires in 24 hours. After revocation, direct GET, preview, and export all refuse the token; the owner still reads normally.",
    "A revoked link fails in the API but succeeds in preview. What should the review conclude?", "The feature still has an authorization gap at the preview boundary.", "Revocation is complete because one route denies.", "The browser should hide the preview link.",
    "invited guest reads active share", "revoked guest reads any representation", ["feature-threat-model", "cross-route-policy", "revocation-test"], "revoked_share_denials", "architecture"),
  s("IAM least privilege", "Grant a workload only the actions and resources it needs.",
    "A workload role is a capability. Broad actions or wildcard resources expand the damage if that workload is compromised. A temporary identity reduces credential lifetime, but its permissions still matter.",
    "Specify who may assume the role, what object path it may read, and which operations are denied. Test permitted read, deletion attempt, and access to an unrelated resource.",
    "A policy that looks narrow because it names one service can still allow all actions on every resource.",
    "Relay exporter role: allow GetObject on reports/tenant-7/*; deny DeleteObject. The runtime obtains temporary credentials; no key is committed.",
    "An export worker needs object reads only. Which policy is strongest?", "A scoped read action on its report path with a restricted role assumption.", "Administrator access on all buckets.", "A permanent key in the image.",
    "export worker reads assigned object", "worker deletes or crosses tenant objects", ["scoped-action", "scoped-resource", "short-lived-identity"], "out_of_scope_access_denials", "cloud"),
  s("Storage and network boundaries", "Keep sensitive objects private and service routes narrow.",
    "Network placement and storage policy protect different layers. A private bucket can still be read by an overprivileged role; a private database can still be reached through an exposed application route.",
    "Trace client → edge → app → data. Allow only required ports and identities, block anonymous reads, and test both the user journey and direct access attempts.",
    "Using encryption as a substitute for access control leaves the application free to publish decrypted content.",
    "Client reaches HTTPS edge; app reaches private database; report objects require the export role. Anonymous object GET and direct database connection fail.",
    "Objects are encrypted but anonymously readable. What must change?", "The object access policy, plus a test of anonymous denial.", "Only the encryption key name.", "The application's font settings.",
    "authorized report download works", "anonymous object fetch succeeds", ["private-object-policy", "narrow-network-path", "identity-check"], "anonymous_report_denials", "cloud"),
  s("Containers and runtime controls", "Reduce the authority of a container without breaking service behavior.",
    "An image packages code and dependencies; a runtime policy controls the process that executes them. Pinning image content helps reproducibility, while non-root identity and limited capabilities reduce the damage of a compromise.",
    "Use an immutable image digest, a non-root UID, denied privilege escalation, a read-only root filesystem where compatible, and bounded resources. Verify the service still starts and passes readiness.",
    "A container that starts is not necessarily safe or able to serve. Disabling writes without providing a needed temporary directory can break healthy traffic.",
    "Image pinned by sha256; UID 10001; no privilege escalation; writable scratch mounted explicitly; /ready succeeds. A privileged shell request is refused.",
    "A rollout pins its image but still runs privileged as root. What remains exposed?", "Runtime authority and escalation, which image pinning does not constrain.", "Only image identity.", "No risk because the image started.",
    "service passes readiness", "container gains host-level privilege", ["image-digest", "non-root-runtime", "readiness-test"], "privileged_workload_count", "cloud"),
  s("Infrastructure policy", "Read the meaning of a Terraform plan and Kubernetes diff.",
    "A plan reports intended changes; a successful parse is not approval. Review the semantic effect of network exposure, IAM scope, secrets, image identity, and workload privileges.",
    "Compare before and after states with the service contract. Stop on unintended broadening, state who approved any exception, and run a post-change denial test.",
    "A small diff can be high impact: changing a policy resource to '*' may expose more than creating several private resources.",
    "Plan: role resource reports/tenant-7/* → *. Kubernetes: runAsNonRoot true → false. Both changes broaden access and need deliberate review.",
    "A plan exits successfully but changes Resource to '*'. What does that prove?", "Only that the plan was produced; the broadened access still needs review and likely rejection.", "That the change is secure.", "That no runtime test is needed.",
    "reviewer approves bounded change", "wildcard access reaches production", ["semantic-diff", "policy-gate", "post-change-test"], "wildcard_policy_changes", "cloud"),
  s("Project: Harden a deployment", "Repair IAM, Terraform, and Kubernetes controls as one service path.",
    "A secure deployment requires compatible identity, network, workload, and delivery settings. Fixing one YAML field cannot compensate for an IAM role that reaches every tenant.",
    "Review the supplied nested artifacts, trace allowed traffic, reject a public database and wildcard role, and verify the patched workload still passes readiness.",
    "Overhardening by blocking every network path appears safe in a denial-only test but stops all customers.",
    "HTTPS user request reaches a non-root API, which reads one scoped object path. Direct DB access and object deletion fail; health checks remain green.",
    "The database is private, but the workload role can delete every report. Is the system ready?", "No; restrict actions and resources, then test deletion denial.", "Yes; private placement overrides IAM.", "Yes; health checks are green.",
    "user request and scoped read succeed", "direct database or broad delete succeeds", ["private-route", "least-privilege-role", "hardened-workload"], "out_of_scope_operations", "cloud"),
  s("Triage dependency findings", "Connect an advisory to installed code and a reachable path.",
    "An advisory identifies affected versions and conditions. A lockfile shows what is installed; call paths and configuration show whether the vulnerable behavior can be reached by an untrusted actor.",
    "Record package version, dependency path, affected feature, exposure, fix version, and tests. Update promptly when the path is reachable; document uncertainty rather than declaring false safety.",
    "A scanner's severity label alone does not prove exploitability. Conversely, absence of a public proof of concept does not make a reachable flaw harmless.",
    "An image parser sits behind public uploads, and the affected mode is enabled. Upgrade, replay a safe fixture, and watch upload failures after release.",
    "A critical advisory affects an unused optional parser mode. What should triage record?", "Installed version, whether the mode is enabled and reachable, uncertainty, and a supported remediation.", "Only the CVSS number.", "A permanent ignore rule with no owner.",
    "supported upload path works", "affected parser mode receives untrusted file", ["version-proof", "reachability-trace", "upgrade-test"], "reachable_vulnerable_paths", "delivery"),
  s("Inventory and provenance", "Know which components are in an artifact and where it came from.",
    "An SBOM inventories components; provenance links an artifact to its source and build process. Neither proves code is harmless. Together they make a finding traceable and a release reproducible.",
    "Compare the deployed digest with the build attestation, source revision, and component inventory. Investigate missing or unexpected dependencies before promotion.",
    "A signed artifact built from the wrong source can still be the wrong release. A complete SBOM does not guarantee no vulnerabilities exist.",
    "Release digest D links to source commit C, builder B, and an SBOM listing package P version 2.1. The deployment must promote D, not rebuild from a branch name.",
    "An artifact is signed, but its attestation names an unexpected source commit. What next?", "Block promotion and reconcile the provenance with the intended change.", "Deploy because a signature exists.", "Ignore the source field and check only file size.",
    "verified digest is promoted", "unverified build reaches production", ["sbom-review", "source-attestation", "digest-promotion"], "unverified_artifact_promotions", "delivery"),
  s("CI/CD permissions", "Constrain workflow authority and keep untrusted code from deployment secrets.",
    "A pipeline executes code from commits and sometimes pull requests. Its default token, environment secrets, and deployment identity decide what that code can access.",
    "Give test jobs read permission, pin third-party actions, separate untrusted pull-request checks from protected production promotion, and use short-lived identity where supported.",
    "A workflow with write-all permissions can turn an unrelated test step into a repository or cloud control path.",
    "Pull request job: contents read, no production secrets. Protected main deployment: reviewed artifact digest, environment approval, scoped short-lived identity.",
    "A pull-request test job receives production credentials. What is the primary risk?", "Untrusted change code can run with deployment authority.", "Tests will run too slowly.", "The branch name will be shorter.",
    "trusted release deploys", "untrusted PR reads deploy secret", ["read-only-default", "protected-environment", "short-lived-deploy"], "untrusted_secret_exposure", "delivery"),
  s("Security tests in delivery", "Choose checks that exercise contracts, not just syntax.",
    "Static analysis, dependency review, integration tests, and authorization tests answer different questions. A parser can be valid while the policy still permits the wrong user.",
    "Use focused tests for the known risk: one legitimate operation, a denied cross-tenant operation, a failure path, and artifact provenance. Triage false positives with evidence and expiry.",
    "A green scanner cannot prove the API enforces ownership at runtime. A single successful API call cannot prove the forbidden path is blocked.",
    "Release gate: JSON schema passes; owner GET returns 200; foreign GET returns 403; deployed digest matches approved build.",
    "A policy file parses and unit tests pass, but no cross-tenant test exists. What is missing?", "A negative authorization test at the actual API boundary.", "Another syntax formatter.", "A different badge color.",
    "authorized request passes gate", "cross_tenant request passes gate", ["static-check", "negative-integration-test", "provenance-check"], "escaped_authorization_regressions", "delivery"),
  s("Project: Protect the release path", "Triage a finding and repair the build-to-deploy chain.",
    "A trusted release needs a known source, reviewed dependencies, a bounded workflow identity, tests, and a recoverable previous artifact. Each link can fail independently.",
    "Inspect a fictional dependency advisory and workflow diff. Show the affected path, patch choice, protected promotion, negative security test, and rollback trigger.",
    "Pinning an action does not repair a vulnerable application dependency; patching the package does not remove a write-all CI token.",
    "Source C builds digest D with a reviewed SBOM. Test and authorization gates pass. A protected job promotes D with short-lived identity; error signal triggers rollback to D-1.",
    "Tests pass, but the deployment job rebuilds from mutable main. What is unproven?", "That production receives the artifact the team actually tested and approved.", "Whether the repository has a README.", "Whether the deployment has a name.",
    "reviewed digest deploys", "unreviewed artifact deploys", ["dependency-triage", "protected-promotion", "rollback-trigger"], "unverified_release_events", "delivery"),
  s("Correlate logs and traces", "Join events across services without mistaking sequence for cause.",
    "A trace follows one request; logs provide discrete facts. Shared correlation ids and timestamps can reveal where a decision happened and which user-visible response followed.",
    "Start with the affected request id, follow identity and resource decisions, and compare a successful request. Note clock skew and missing spans before declaring a root cause.",
    "Reading the final 500 line alone may blame the edge even when the first failing decision occurred inside authorization middleware.",
    "req-7f2: edge 403 at 10:14:03; API policy deny at 10:14:02; identity token valid at 10:14:01. The denial may be correct; inspect resource ownership next.",
    "A valid token is followed by a 403. Which evidence distinguishes failure from correct denial?", "The resource policy decision tied to the same request id and owner context.", "The edge status alone.", "The user's browser theme.",
    "responder traces access decision", "correlation gap hides policy decision", ["request-id", "policy-event", "normal-comparison"], "uncorrelated_security_events", "incident"),
  s("Detect account abuse", "Recognize suspicious patterns without locking out legitimate users blindly.",
    "Account abuse can appear as repeated failures across many users, unusual successful sign-ins, or rapid sensitive actions. A detection needs a baseline and a response proportionate to confidence.",
    "Compare source diversity, affected accounts, success rate, device changes, and known travel or automation. Add step-up or rate limits for suspicious activity before a global block when possible.",
    "One overseas login is not proof of compromise. A low-and-slow campaign across many accounts can hide beneath a per-account threshold.",
    "Within ten minutes, 500 accounts each have two failed attempts from a new source pool. Aggregate by source and campaign, then investigate successful follow-on actions.",
    "Why might a per-account failure threshold miss a campaign?", "The attacker spreads attempts across many accounts below each local threshold.", "It always catches distributed sources.", "It makes passwords reversible.",
    "legitimate users keep access", "distributed account abuse proceeds unseen", ["cross-account-aggregate", "step-up-response", "false-positive-review"], "campaign_account_count", "incident"),
  s("Contain without blind spots", "Limit an incident while preserving service and forensic context.",
    "Containment changes the system while investigation is still in progress. Broad revocation can stop an attack but also erase a service's ability to function; delayed revocation can extend harm.",
    "Identify affected identity and resource scope, preserve relevant logs, revoke the narrow capability, replace it safely, and test both blocked misuse and restored legitimate work.",
    "Rotating a secret in one service while leaving copies active elsewhere gives false closure. Deleting logs before capture destroys the ability to learn scope.",
    "Compromised export role R can read tenant 7. Snapshot relevant access events, disable R, issue R2 with narrower scope, and verify exports and denial tests.",
    "A role is compromised. What does a sound containment plan include?", "Scoped revocation, evidence retention, safe replacement, and outcome checks.", "Deleting all identity logs first.", "A dashboard screenshot only.",
    "export resumes under replacement role", "compromised role still reads objects", ["scope-inventory", "role-revocation", "replacement-test"], "revoked_role_acceptance", "incident"),
  s("Investigate safely", "State what the evidence proves, suggests, and cannot show.",
    "Forensic confidence depends on record completeness, time synchronization, retention, and integrity. A missing log entry is not proof an event never happened.",
    "Preserve originals, document collection time, correlate independent sources, and label each finding by evidence strength. Request the next narrow data source needed to resolve an important uncertainty.",
    "A single IP address may represent shared infrastructure. Naming an attacker from that field alone overstates the evidence.",
    "Storage audit confirms three object reads by role R at 10:14–10:16. It does not prove who controlled R. Identity logs and deployment changes are next sources.",
    "Audit logs show role R accessed objects, but no human identity. What is justified?", "State role-level access and seek independent identity evidence.", "Name a specific employee as the attacker.", "Assume no objects were read.",
    "investigator preserves supported finding", "uncertain actor is presented as certain", ["original-evidence", "confidence-level", "next-source"], "unsupported_incident_claims", "incident"),
  s("Post-incident improvement", "Turn a failure mode into an owned, testable change.",
    "A useful follow-up changes a system property and defines how its effect will be measured. Blaming an individual or writing an unowned checklist rarely prevents recurrence.",
    "Tie each action to the observed path, assign an owner and deadline, add a regression test or detection, and revisit residual risk after deployment.",
    "A vague 'be more careful' action cannot be verified. A broad rule that blocks all exports may create a new availability incident.",
    "Failure: export role allowed every tenant. Follow-up: scope role by tenant, add cross-tenant denial test, alert on wildcard policy diffs, review in 30 days.",
    "After a cross-tenant export incident, which follow-up would be measurable and help prevent recurrence?", "Scope the role, add a negative test, assign an owner, and review the result by a date.", "Tell everyone to be careful.", "Close the incident without tracking changes.",
    "owner verifies remediation", "same failure mode returns unnoticed", ["root-cause-link", "assigned-owner", "regression-evidence"], "repeat_incident_count", "incident"),
  s("Capstone: Secure and recover a service", "Threat-model, harden, investigate, and recover a fictional API.",
    "Security across a production journey includes feature design, identity, workload controls, trusted delivery, detection, and response. The capstone combines those contracts rather than treating one scanner result as proof.",
    "Build a threat model, repair IAM and release artifacts, demonstrate permitted and denied requests, correlate a staged incident, and explain a bounded recovery and residual risk.",
    "A passing test suite can miss an unmodeled threat. An incident report can be persuasive yet unsupported if it lacks traceable events.",
    "Approved source C produces digest D. Tenant 7 accesses its own report. Tenant 8 is denied. A role anomaly is detected and contained; the service returns to a tested state.",
    "What makes this capstone complete?", "Reviewed design, tested boundaries, release provenance, incident evidence, and demonstrated recovery.", "A single vulnerability scan.", "A diagram with no runtime outcome.",
    "tenant completes report journey", "foreign tenant reads report after incident", ["threat-model", "secure-release", "incident-recovery"], "verified_secure_journeys", "incident"),
];
