import { s } from "./topic";

export const BEGINNER_SECURITY = [
  s("Assets and adversaries", "Identify what a service must protect and who might misuse it.",
    "An asset is anything whose loss would matter: private records, the ability to change them, an available service, or a trusted identity. An adversary is defined by capability and goal, not a movie-villain label.",
    "List the data, actors, and operations first. Ask which actor can reach each entry point and what they could gain if one check failed. Rank harm to users before choosing a tool.",
    "Treating the server as the only asset misses copied exports, account recovery, and the integrity of records. A firewall cannot repair an API that authorizes the wrong owner.",
    "Support agent → read ticket metadata: allowed\nUnknown visitor → read private ticket body: denied\nAsset: customer support record",
    "A private ticket is exposed through a public link. What is the first useful security question?", "Which asset and trust boundary let an unauthenticated visitor read it?", "Which antivirus product is newest?", "How many servers are running?",
    "authorized agent reads assigned ticket", "anonymous visitor reads private ticket", ["asset-inventory", "actor-map", "boundary-review"], "unauthorized_ticket_reads", "architecture"),
  s("Security properties", "Distinguish confidentiality, integrity, and availability in a real scenario.",
    "Confidentiality concerns who can see information; integrity concerns whether it remains correct; availability concerns whether a legitimate user can use it. One incident can affect all three, but a control rarely addresses them equally.",
    "Name the user-visible harm and the affected property. Then choose a control and test the property it claims to protect. Encryption at rest does not by itself stop an authorized but overprivileged account from deleting data.",
    "Calling every failure a data leak hides important differences. Restoring a backup can repair lost integrity yet still leave the original exposure open.",
    "A report is accidentally overwritten. Version history helps integrity recovery; a private access policy protects confidentiality; redundant service capacity protects availability.",
    "An attacker changes a payment destination but does not read the account. Which property failed first?", "Integrity: the stored payment instruction is no longer trustworthy.", "Confidentiality: a secret was necessarily disclosed.", "Availability: every user is necessarily offline.",
    "owner updates payment destination", "unapproved actor changes payment destination", ["write-authorization", "change-audit", "version-recovery"], "unapproved_change_count", "architecture"),
  s("Follow a network request", "Trace a browser request through DNS, TLS, edge, application, and data.",
    "DNS chooses an address; TLS authenticates and protects the connection; HTTP carries the request; the application decides what it means. Success at one hop does not prove security at the next.",
    "Draw the full path and mark where identities, headers, and data are checked. Diagnose a failure at the earliest failing hop before widening access or disabling a control.",
    "A valid certificate does not authorize a database query, and a private database does not protect a public API that returns another user's record.",
    "Browser --TLS--> edge --private route--> API --scoped identity--> database. A 200 response proves the route worked; it does not prove the returned record belongs to the caller.",
    "DNS and TLS succeed, but the API serves another user's record. Where is the failing boundary?", "The API's resource authorization decision.", "The DNS lookup, because it returned an address.", "TLS, because the certificate was valid.",
    "user fetches own profile", "user fetches another profile by changing id", ["tls-validation", "resource-authorization", "request-trace"], "cross_account_read_denials", "web"),
  s("Find the trust boundary", "Locate every place untrusted data or identity claims gain authority.",
    "A trust boundary is crossed when data from a less trusted context influences a more privileged decision. Browser fields, uploaded files, webhook bodies, and retrieved AI content are inputs even when they look well formed.",
    "For each boundary, specify who can control the value, which parser sees it, and what sensitive action follows. Put validation and authorization before that action, on the server that owns it.",
    "Hiding a field in the UI does not make its value trustworthy. A caller can send a request directly with a changed account identifier.",
    "POST /reports with {ownerId: 42}. The client controls ownerId; the server must derive permitted ownership from the authenticated subject before storing the report.",
    "A client sends accountId in JSON. Which value should decide record ownership?", "The server-verified caller identity and resource policy.", "The JSON field because the form hid it.", "The most recent account in a cache.",
    "member creates own report", "member assigns report to another account", ["server-side-identity", "input-validation", "ownership-check"], "ownership_rejections", "web"),
  s("Project: Map the attack surface", "Map actors, assets, boundaries, and a defensible risk order.",
    "An attack surface is the set of reachable entry points and trust transitions, not a count of routes. The same endpoint can expose several risks if it accepts files, identity claims, or privileged options.",
    "Start with one legitimate journey. Add an anonymous request, a different signed-in user, and a failed dependency. Rank risks by plausible exposure and impact, stating assumptions that could change the order.",
    "A diagram without permitted and denied paths is too vague to review. Marking every component high risk also prevents sensible prioritization.",
    "Relay: visitor → login → ticket API → records. Risk 1: cross-account read; risk 2: leaked export; risk 3: noisy login attempts. Explain which evidence supports that order.",
    "The team can fix one issue first. Which argument best supports the priority?", "An exposed private-record path with reachable callers and material user harm.", "The issue with the longest technical name.", "The issue in the newest service regardless of exposure.",
    "assigned agent reads ticket", "unassigned caller reads ticket", ["actor-asset-map", "trust-boundary-map", "risk-ranking"], "unauthorized_ticket_reads", "architecture"),
  s("Authentication versus authorization", "Separate proof of identity from permission for one action.",
    "Authentication answers who the caller is. Authorization decides whether that caller may perform a particular action on a particular resource. A valid session can still belong to someone with no right to the requested record.",
    "Check the resource and action on every server request. Use deny by default and compare the verified subject with the resource's owner or role policy.",
    "A route protected only by a signed-in check can still expose every user's data through a changed URL identifier.",
    "GET /tickets/42 with a valid session for user 7. If ticket 42 belongs to user 9, the API returns a safe denial even though authentication succeeded.",
    "A signed-in user opens another user's ticket URL. What should the server do?", "Authenticate the session, then deny this resource read.", "Return the ticket because the session is valid.", "Ask the browser to hide the link after returning the data.",
    "owner reads own ticket", "signed-in stranger reads ticket", ["verified-session", "resource-policy", "default-deny"], "object_level_denials", "identity"),
  s("Sessions and MFA", "Choose bounded session behavior and stronger proof for sensitive actions.",
    "A session connects successive requests to an authenticated identity. Its identifier is a bearer capability: whoever holds it may be treated as the user until it expires or is revoked. MFA strengthens a sign-in or step-up decision but does not repair bad authorization.",
    "Use secure, HTTP-only, same-site cookies where appropriate; set expiry and revocation; require recent stronger proof for changing a payout destination. Test sign-out and expired-session behavior.",
    "A long-lived token in script-readable storage expands the damage of script injection. MFA at login cannot prevent misuse of a stolen active session by itself.",
    "Cookie: Secure; HttpOnly; SameSite=Lax. A payout change requires recent step-up proof. A revoked session receives 401 on the next request.",
    "A user signs out on a shared device. What proves sign-out worked?", "The old session identifier no longer authorizes a protected request.", "The button label changed to Sign in.", "The browser history was cleared.",
    "active user views dashboard", "revoked session changes payout", ["secure-cookie", "session-revocation", "step-up-check"], "revoked_session_denials", "identity"),
  s("Input validation", "Validate shape, meaning, and size before untrusted values reach sensitive work.",
    "Parsing says an input has a type; validation says it belongs to the application's domain. A string can be valid JSON yet still be an impossible date, an oversized upload, or an unauthorized identifier.",
    "Validate at the server boundary with length, format, range, and cross-field rules. Keep errors useful but avoid echoing secrets or internal parser details.",
    "Accepting any JSON because the browser form constrained input misses callers that bypass the form. Rejecting all unusual names can harm legitimate users, so define domain rules carefully.",
    "A reservation accepts 1–8 seats and a future date. {seats: 1000000} parses, but fails the business limit before capacity is queried.",
    "A valid JSON request asks for one million seats. What is the right response?", "Reject it against the server's documented domain limit.", "Accept it because JSON parsing succeeded.", "Truncate silently to eight seats.",
    "customer submits valid reservation", "caller submits oversized reservation", ["schema-check", "domain-limit", "safe-error"], "invalid_request_rejections", "web"),
  s("Output encoding and browser defenses", "Keep untrusted text from becoming executable browser content.",
    "A browser interprets HTML, attributes, URLs, and JavaScript differently. Data placed in an executable context can become script. Safe rendering keeps user content as text; a content security policy adds a second boundary.",
    "Use the framework's text rendering for comments, avoid raw HTML sinks, and sanitize only when rich HTML is a real requirement. Test the rendered DOM and a policy violation report.",
    "Escaping a value for an HTML text node does not automatically make it safe inside a script or URL. A permissive CSP cannot compensate for unsafe rendering.",
    "Comment text: <script>…</script>. The page displays those characters as text; the browser never creates a script node. CSP blocks an unexpected inline script attempt.",
    "A comment contains angle brackets and script-like text. What should the page do?", "Render the submitted content as inert text in the correct context.", "Insert it with innerHTML and trust CSP alone.", "Remove all comments from the database.",
    "reader views comment text", "comment executes as script", ["context-encoding", "safe-dom-sink", "csp-report"], "blocked_script_execution", "web"),
  s("Project: Secure a request flow", "Repair login, ownership, input, and browser output in one journey.",
    "A request can be safe at one layer and unsafe at another. A verified session still needs resource authorization, and validated input still needs safe rendering on output.",
    "Trace login → profile edit → profile view. Verify a normal edit, an expired session, another user's record, and a script-like display name. Record which boundary rejects each case.",
    "Passing only the happy path or blocking all requests can make a security test appear green while the product is unusable.",
    "User 7 updates their display name. User 8 cannot update record 7. The stored name appears as text. A revoked session cannot repeat either action.",
    "The UI hides other users' profiles, but a direct edit request succeeds. Which fix is required?", "Server-side authorization for the target profile on every edit.", "A stronger CSS hidden rule.", "A warning in the profile form.",
    "owner edits and reads profile", "other user edits profile", ["session-validation", "object-authorization", "safe-rendering"], "unauthorized_profile_edits", "web"),
  s("Parameterized queries", "Keep user values separate from SQL syntax.",
    "SQL injection occurs when untrusted input becomes part of a query's executable structure. Prepared statements bind values as data after the statement shape is defined.",
    "Parameterize every value, including search terms and limits. Table or column names usually cannot be value parameters; select them from a narrow allowlist instead.",
    "Escaping a few quotes or rejecting a known attack string is brittle. A test should prove a special-character search stays a value and returns only authorized rows.",
    "SELECT * FROM tickets WHERE owner_id = ? AND subject = ?; parameters [verifiedUserId, submittedSubject]. The submitted text cannot add another WHERE clause.",
    "A search term contains quote characters. What preserves the query's meaning?", "Bind it as a parameter and keep the SQL structure fixed.", "Concatenate it after removing single quotes.", "Run the query as a database administrator.",
    "owner searches own tickets", "search input changes query structure", ["bound-values", "owner-filter", "query-test"], "cross_owner_query_results", "web"),
  s("Password storage and secrets", "Choose hashing, encryption, and secret references for their different jobs.",
    "Passwords should be verified against a slow, salted password hash; they need not be decrypted. Encryption protects recoverable data. Application credentials need controlled storage, access, rotation, and revocation.",
    "Keep password hashes, encrypted records, and runtime secret references distinct. After a credential leak, rotate or revoke it; deleting one log line does not invalidate copied values.",
    "Hashing an API key without a rotation plan does not fix an exposed live key. Encrypting a password with a reversible shared key creates a decryption target.",
    "User password → salted password hash. Database credential → secret reference resolved by a scoped workload identity. Leaked credential → revoke, rotate, and review use.",
    "A database password appears in a debug log. What is the first complete response?", "Revoke or rotate it, inspect use, and remove the logging path.", "Delete the newest log entry only.", "Encrypt the log but keep the password active forever.",
    "service retrieves scoped credential", "credential value appears in logs", ["password-hash", "runtime-secret", "rotation-plan"], "secret_exposure_events", "identity"),
  s("Object-level access control", "Enforce ownership on each record, including reads and background work.",
    "An object identifier is a locator, not proof of permission. Authorization must combine the verified caller, the specific record, the action, and any tenant context.",
    "Use a server-side policy for read and write paths, and carry explicit tenant context into queued jobs. Test adjacent identifiers and bulk endpoints as well as the normal UI.",
    "A global lookup by id can leak a record even when list endpoints filter by owner. The same mistake can appear in download links and caches.",
    "SELECT ... WHERE id = ? AND tenant_id = ?; the tenant id comes from server-verified identity, never from a caller-controlled query parameter.",
    "A valid user changes /files/100 to /files/101 and gets another tenant's file. What failed?", "Object-level authorization on the requested file.", "DNS resolution.", "Password hashing.",
    "tenant member downloads own file", "tenant member downloads foreign file", ["resource-scope", "tenant-context", "negative-test"], "cross_tenant_file_denials", "web"),
  s("Dependencies and configuration", "Triage component risk and unsafe defaults using actual exposure.",
    "A dependency advisory describes a possible weakness in a version or behavior; impact depends on whether the component and vulnerable path are reachable. Configuration can create equal risk without a vulnerable package.",
    "Confirm installed version, usage, affected feature, exposure, and supported fix. Record a time-bound exception only when a tested compensating control actually blocks the relevant path.",
    "Ignoring all alerts because some are false positives is unsafe. Upgrading every package blindly can break the service and miss the exposed public setting beside it.",
    "An image parser advisory affects uploads. The service accepts untrusted images, so patching and an upload test take priority over an unused development-only library alert.",
    "Two advisories are open: reachable upload parser and unused test helper. What should lead?", "The reachable upload parser with a clear remediation and regression test.", "The advisory with the longest identifier.", "The unused helper because it is easier to update.",
    "safe upload is processed", "vulnerable parser receives untrusted upload", ["reachability-review", "supported-update", "regression-test"], "unsafe_upload_rejections", "web"),
  s("Project: Repair a vulnerable API", "Fix injection, authorization, and secret handling together.",
    "A secure API keeps query values separate from syntax, checks resource ownership, and obtains credentials without durable exposure. Each control protects a different boundary.",
    "Review a fictional ticket endpoint, its SQL, and its deployment configuration. Keep a legitimate owner request working, reject another owner, and verify that no secret value enters logs or source.",
    "A patched query does not repair cross-account access. A private database does not compensate for a leaked administrator credential.",
    "Owner search uses parameters and a tenant filter; a foreign id returns 403 or safe 404; the database credential is a runtime reference and is rotated after the staged leak.",
    "After parameterizing SQL, a foreign ticket is still returned. What should the team inspect next?", "The object-level policy and tenant filter on that read.", "The query syntax again only.", "The color of the error banner.",
    "owner searches and views ticket", "foreign caller reads ticket", ["parameterized-query", "tenant-policy", "secret-rotation"], "cross_tenant_ticket_denials", "web"),
  s("Useful security logs", "Record decisions and correlation without leaking sensitive values.",
    "A useful security event names time, actor or pseudonymous subject, action, target category, decision, and request id. It explains a decision without copying credentials, request bodies, or private records.",
    "Log both allowed and denied security decisions at a bounded level. Correlate related service events with a stable request id and set access and retention limits on the logs themselves.",
    "A log containing every header may appear detailed yet expose session cookies. A single generic 'error' line lacks the context needed to investigate.",
    "{time: 10:14, actor: user-7, action: ticket.read, target: ticket, decision: deny, request_id: req-42}; no ticket body or cookie.",
    "An access denial is logged. Which fields help investigate without copying private data?", "Actor, action, target category, decision, time, and request id.", "Full session cookie and ticket body.", "Only the word error.",
    "security reviewer correlates request", "log exposes session secret", ["structured-event", "secret-redaction", "retention-limit"], "denied_access_events", "incident"),
  s("Alert triage", "Separate an actionable anomaly from expected traffic.",
    "An alert compares a signal with an expected baseline over time. One denied request can be a normal typo; repeated denials across many accounts may indicate abuse. Detection should provide an owner and a next investigative step.",
    "Check volume, rate, affected accounts, source diversity, and deploy context. Confirm whether legitimate traffic is harmed before taking a broad blocking action.",
    "Paging on every 401 trains responders to ignore alerts. Blocking a shared office address after one failed sign-in can lock out real users.",
    "09:00–09:10: 4 denials from one known user. 09:10–09:20: 900 denials across 250 accounts from a new source group. Investigate the change, not the absolute count alone.",
    "A login-denial alert fires after a deployment. What is a defensible first step?", "Compare baseline, affected users, sources, and deployment timing.", "Block all sign-ins immediately.", "Assume every denial is an attack.",
    "normal users authenticate", "coordinated account abuse continues unseen", ["baseline-window", "actor-correlation", "triage-owner"], "distinct_accounts_with_denials", "incident"),
  s("Incident timelines", "Separate observations, hypotheses, and unknowns in chronological evidence.",
    "An incident timeline orders events from independent sources. It helps test causality, but close timing alone does not prove root cause. Clock skew and missing events can change the interpretation.",
    "Record source, timestamp, observation, action, and confidence. Correlate request ids and identity events, then label claims as observed, inferred, or unresolved.",
    "A rollback followed by recovery makes the release a strong hypothesis, but another simultaneous change could explain the result. Avoid declaring certainty before comparison.",
    "09:02 release begins; 09:05 foreign-record denials drop; 09:07 complaint; 09:12 rollback; 09:16 denials recover. Compare code and request samples before naming the defect.",
    "Failures stop after rollback. Which statement is justified?", "The release is a leading hypothesis that needs a focused comparison.", "The exact offending line is proven.", "The event could not be security-related.",
    "responder reconstructs sequence", "team erases uncertain evidence", ["timestamped-events", "source-correlation", "confidence-label"], "incident_timeline_gaps", "incident"),
  s("Containment and recovery", "Limit harm while preserving evidence and restoring legitimate service.",
    "Containment stops a harmful path; recovery restores a trusted operating state. Revoking a credential can limit misuse, but responders must know which service depends on it and how a replacement will be distributed.",
    "Choose a reversible, bounded action first when possible. Preserve relevant logs and snapshots, rotate affected secrets, validate data, and test the restored user journey before declaring recovery.",
    "Deleting logs to 'clean up' destroys evidence. Disabling the entire platform may cause needless harm if only one token or route is affected.",
    "A scoped API token is exposed. Suspend the token, issue a replacement to the owning service, inspect its use, and verify the service's authorized request succeeds again.",
    "One API token is compromised. What is the best initial containment?", "Revoke that token, preserve evidence, and rotate the dependent service safely.", "Delete all logs first.", "Leave it active until the next monthly release.",
    "service resumes with rotated token", "compromised token remains valid", ["scoped-revocation", "evidence-preservation", "recovery-test"], "revoked_token_acceptance", "incident"),
  s("Clear communication", "Report impact, actions, uncertainty, and next update without overclaiming.",
    "Incident communication helps users and responders make decisions. A good update states what is known, the affected surface and period, mitigation status, remaining uncertainty, and when the next update will arrive.",
    "Use plain language, distinguish observed impact from possible impact, and assign an owner for remediation. Keep internal secrets and speculative attacker attribution out of public updates.",
    "Saying 'all data is safe' before checking exports creates false assurance. Saying only 'we are investigating' gives affected users no useful guidance.",
    "At 10:20 UTC, ticket exports were paused after unauthorized download attempts. We are checking whether any downloads succeeded and will update by 11:00 UTC.",
    "The team knows an export route was abused but cannot yet prove data access. What should the update say?", "State the observed attempts, current mitigation, uncertainty, and next update time.", "Claim no data was accessed.", "Publish a guessed attacker identity.",
    "affected users receive accurate update", "uncertain impact is stated as fact", ["confirmed-impact", "uncertainty-label", "next-update"], "unverified_public_claims", "incident"),
  s("Capstone: Protect the Relay", "Review, repair, test, and explain a fictional web service end to end.",
    "Security is a chain of decisions across identity, data, execution, observation, and recovery. A polished diagram cannot substitute for a working normal path and a denied abuse path.",
    "Map assets and trust boundaries, repair the supplied session, query, and access policies, then investigate synthetic logs. Present tests, residual risk, and a contained recovery plan.",
    "A system that blocks every request is unavailable; a system that allows every signed-in request is exposed. Both must be tested against the service's intended users.",
    "Owner logs in, reads own ticket, and logs out. Foreign ticket and revoked-session requests fail. A simulated incident is detected, contained, and explained with evidence.",
    "Which capstone evidence most strongly supports release?", "Passing normal and denied journeys, a reviewed artifact, and a recovery drill.", "One green syntax check.", "A diagram with no observed behavior.",
    "owner completes ticket journey", "foreign or revoked caller reads ticket", ["identity-and-access", "safe-data-path", "incident-readiness"], "verified_ticket_journeys", "incident"),
];
