"use client";
/* eslint-disable @next/next/no-html-link-for-pages -- Full document navigation keeps hosted track transitions reliable. */
import { SignInButton, useAuth, useUser } from "@clerk/react";
import { useEffect, useState } from "react";
import CloudLab from "../cloud/cloud-lab";
import DailyQuestCard from "../components/daily-quest-card";
import { DAILY_QUEST_XP, getDailyQuestIndex } from "../daily-quest";
import { loadJourneyPreferences } from "../hooks/use-journey";
import { useProgressSync } from "../hooks/use-progress-sync";
import type { PlayerProgress } from "../progress";
import { getSecurityLesson, getSecurityLessons } from "./curriculum";
import { completeSecurityDailyQuest, completeSecurityLesson, isSecurityLessonUnlocked, securityCompleted, securityLessonXp } from "./progress";
import { SECURITY_PATHS, SECURITY_PATH_TOTAL, getSecurityPath, getSecurityWorlds, type SecurityPaceId } from "./track";

const lessonPath = (paceId: SecurityPaceId, id: number) => "/lesson/security/" + paceId + "/" + id;
const navigate = (destination: string) => window.location.assign(destination);
const FIT: Record<SecurityPaceId, string> = {
  beginner: "I want to understand common vulnerabilities and defend a small application.",
  intermediate: "I ship services and want secure cloud, identity, and release practices.",
  expert: "I own architecture, detection, or coordinated incident response.",
};

function PacePicker({ progress, ready, recommendation, onRecommend, onSelect }: { progress: PlayerProgress; ready: boolean; recommendation: SecurityPaceId; onRecommend: (pace: SecurityPaceId) => void; onSelect: (pace: SecurityPaceId) => void }) {
  return <section className="python-pace-picker cloud-pace-picker backend-pace-picker frontend-pace-picker data-pace-picker security-pace-picker" id="security-content">
    <div className="pace-picker-hero"><button onClick={() => navigate("/tracks")}>← All tracks</button><p className="pixel-kicker">TRUST CITADEL · CHOOSE YOUR PATH</p><h1>Learn to build<br /><span>safer systems</span></h1><p>Choose your level. Each path has 21 carefully explained lessons, evidence-based scenarios, static artifact reviews, and four connected world projects.</p></div>
    <section className="pace-recommender" aria-labelledby="security-recommender-title"><div><p>PACE FINDER</p><h2 id="security-recommender-title">Where are you in your security journey?</h2></div><div>{SECURITY_PATHS.map((path) => <button key={path.id} className={recommendation === path.id ? "active" : ""} onClick={() => onRecommend(path.id)}><strong>{path.label}</strong><span>{FIT[path.id]}</span></button>)}</div><p>Recommended path: <strong>{getSecurityPath(recommendation).label}</strong>. Switching paths will not erase progress.</p></section>
    <div className="pace-grid">{SECURITY_PATHS.map((path, index) => { const topics = getSecurityLessons(path.id); const count = ready ? securityCompleted(progress, path.id).length : 0; return <article key={path.id} className={"pace-card " + path.id + (recommendation === path.id ? " recommended" : "")}><div className="pace-card-art" aria-hidden="true"><span>{index + 1}</span><i /><i /><b>{path.estimatedLevel}</b></div><div className="pace-card-body"><div className={"recommendation-badge " + (recommendation === path.id ? "" : "recommendation-placeholder")} aria-hidden={recommendation !== path.id}>RECOMMENDED START</div><div className="pace-tier"><span>PATH {String(index + 1).padStart(2, "0")}</span><small>21 TOPICS</small></div><h2>{path.label}</h2><strong>{path.tagline}</strong><p>{path.description}</p><div className="pace-for"><small>RECOMMENDED FOR</small><span>{path.recommendedFor}</span></div><div className="pace-topic-preview">{topics.slice(0, 5).map((topic) => <span key={topic.id}>{topic.title}</span>)}<span>+16 more</span></div><div className="pace-card-progress"><div role="progressbar" aria-label={path.label + " progress"} aria-valuemin={0} aria-valuemax={21} aria-valuenow={count}><i style={{ width: count / 21 * 100 + "%" }} /></div><span>{ready ? count + "/21 complete" : "Loading…"}</span></div><button className="pace-card-cta" disabled={!ready} onClick={() => onSelect(path.id)}>{!ready ? "Loading progress…" : count ? "Continue " + path.label : "Start " + path.label} →</button></div></article>; })}</div>
    <div className="pace-picker-note"><span>◇</span><p><strong>Safe, fictional exercises.</strong>Inspect simulated requests, logs, timelines, JSON policies, and selected infrastructure artifacts. No attacks are launched and no cloud account or credential is needed.</p></div>
  </section>;
}

function Roadmap({ paceId, progress, ready }: { paceId: SecurityPaceId; progress: PlayerProgress; ready: boolean }) {
  const path = getSecurityPath(paceId); const all = getSecurityLessons(paceId); const worlds = getSecurityWorlds(paceId); const done = ready ? securityCompleted(progress, paceId) : []; const next = Math.min(done.length + 1, SECURITY_PATH_TOTAL); const today = new Date().toISOString().slice(0, 10); const daily = all[getDailyQuestIndex(today, "security", paceId, all.length)]; const dailyDone = ready && progress.game.dailyQuestDate === today && progress.game.dailyQuestCompleted;
  return <section className="python-pace-picker cloud-path-picker backend-path-picker frontend-path-picker data-path-picker security-path-picker" id="security-content">
    <div className="pace-picker-hero"><button onClick={() => navigate("/tracks/security")}>← Security paths</button><p className="pixel-kicker">TRUST CITADEL · {path.title.toUpperCase()}</p><h1>Explore your<br /><span>{path.label} roadmap</span></h1><p>{path.description} Each lesson explains the boundary, demonstrates a failure, asks you to reason through evidence, and checks a defensible repair.</p></div>
    <DailyQuestCard completed={dailyDone} title={daily.title} trackLabel="Cybersecurity Engineering" paceLabel={path.label} streak={progress.game.dailyQuestStreak} onOpen={() => navigate("/daily-quest/security/" + paceId)} />
    <section className="journey-resume cloud-path-resume" aria-label="Security path progress"><div><span>{done.length === SECURITY_PATH_TOTAL ? "PATH COMPLETE" : "YOUR SECURITY JOURNEY"}</span><h2>{done.length}/21 lessons completed</h2><p>21 lessons · 4 worlds · 4 required projects</p></div><button disabled={!ready} onClick={() => navigate(lessonPath(paceId, next))}>{!ready ? "Loading progress…" : done.length === 21 ? "Revisit capstone →" : done.length ? "Continue lesson " + next + " →" : "Start first lesson →"}</button></section>
    <div className="pace-grid">{worlds.map((world, index) => { const lessons = all.filter((lesson) => lesson.id >= world.start && lesson.id <= world.end); const count = done.filter((id) => id >= world.start && id <= world.end).length; const unlocked = ready && isSecurityLessonUnlocked(progress, world.start, paceId); const current = next >= world.start && next <= world.end; const destination = count === lessons.length ? world.start : Math.max(world.start, next); return <article key={world.id} className={"pace-card cloud-world-card " + (index === 0 ? "beginner" : index === 1 ? "intermediate" : "expert") + (current ? " recommended" : "")}><div className="pace-card-art" aria-hidden="true"><span>{count === lessons.length ? "✓" : world.id}</span><i /><i /><b>{count === lessons.length ? "SECURED" : unlocked ? "UNLOCKED" : "LOCKED"}</b></div><div className="pace-card-body"><div className={"recommendation-badge " + (current ? "" : "recommendation-placeholder")} aria-hidden={!current}>YOUR NEXT WORLD</div><div className="pace-tier"><span>WORLD {String(world.id).padStart(2, "0")}</span><small>{lessons.length} LESSONS</small></div><h2>{world.name}</h2><strong>{world.focus}</strong><p>{world.summary}</p><div className="pace-for"><small>WORLD PROJECT</small><span>{lessons.at(-1)?.title}</span></div><ol className="cloud-world-lessons" start={world.start}>{lessons.map((lesson) => { const available = ready && isSecurityLessonUnlocked(progress, lesson.id, paceId); const complete = done.includes(lesson.id); const label = <><span aria-hidden="true">{complete ? "✓" : String(lesson.id).padStart(2, "0")}</span><span>{lesson.title}<small>{lesson.minutes} min · {complete ? "Complete" : available ? "Ready" : "Locked"}</small></span></>; return <li key={lesson.id} className={complete ? "done" : available ? "available" : "locked"}>{available ? <a href={lessonPath(paceId, lesson.id)}>{label}</a> : <div>{label}</div>}</li>; })}</ol><div className="pace-card-progress"><div role="progressbar" aria-label={world.name + " progress"} aria-valuemin={0} aria-valuemax={lessons.length} aria-valuenow={count}><i style={{ width: count / lessons.length * 100 + "%" }} /></div><span>{count}/{lessons.length} complete</span></div><button className="pace-card-cta" disabled={!unlocked} onClick={() => navigate(lessonPath(paceId, destination))}>{!ready ? "Loading progress…" : count === lessons.length ? "Review secured world →" : unlocked ? "Enter " + world.name + " →" : "Complete prior world to unlock"}</button></div></article>; })}</div>
    <div className="pace-picker-note cloud-path-note"><span>◇</span><p><strong>Learn and verify safely.</strong>Every case and artifact is fictional, inspected as inert text, and validated in your browser. Real authorization must also be enforced by the actual service.</p></div>
  </section>;
}

export default function SecurityApp({ paceId = "beginner", lessonId, roadmap = false, daily = false }: { paceId?: SecurityPaceId; lessonId?: number; roadmap?: boolean; daily?: boolean }) {
  const { getToken, isLoaded, isSignedIn } = useAuth(); const { user } = useUser();
  const { progress, persistProgress, progressReady, cloudState } = useProgressSync({ clerkLoaded: Boolean(isLoaded), clerkSignedIn: Boolean(isSignedIn), getToken, displayName: user?.fullName ?? user?.firstName ?? "CodeCraft learner", email: user?.primaryEmailAddress?.emailAddress ?? "" });
  const [mounted, setMounted] = useState(false); const [recommendation, setRecommendation] = useState<SecurityPaceId>("beginner");
  useEffect(() => { const timer = window.setTimeout(() => { setMounted(true); const saved = loadJourneyPreferences(); if (saved.trackId === "security") setRecommendation(saved.paceId); }, 0); return () => window.clearTimeout(timer); }, []);
  const ready = mounted && progressReady; const path = getSecurityPath(paceId); const completed = ready ? securityCompleted(progress, paceId) : []; const nextId = Math.min(completed.length + 1, SECURITY_PATH_TOTAL); const today = new Date().toISOString().slice(0, 10); const dailyLessonId = getDailyQuestIndex(today, "security", paceId, SECURITY_PATH_TOTAL) + 1; const effectiveId = daily ? dailyLessonId : lessonId; const lesson = effectiveId === undefined ? undefined : getSecurityLesson(paceId, effectiveId); const world = getSecurityWorlds(paceId).find((entry) => lesson && lesson.id >= entry.start && lesson.id <= entry.end); const unlocked = ready && lesson && (daily || isSecurityLessonUnlocked(progress, lesson.id, paceId)); const dailyCompleted = ready && progress.game.dailyQuestDate === today && progress.game.dailyQuestCompleted; const totalBadges = ready ? Object.values(progress.completed).reduce((total, ids) => total + ids.length, 0) : 0; const level = ready ? Math.floor(Math.max(0, progress.xp - 120) / 100) + 1 : 1; const avatarId = ready ? progress.game.avatarId : "relay-scout"; const avatarGlyph = avatarId === "signal-mage" ? "✦" : avatarId === "core-runner" ? "◆" : "◇";
  const selectPace = (selected: SecurityPaceId) => { window.localStorage.setItem("codecraft-journey-v1", JSON.stringify({ ...loadJourneyPreferences(), trackId: "security", paceId: selected, started: true, tutorialComplete: true })); navigate("/roadmap/security/" + selected); };
  const saveCompletion = () => { if (!lesson || !ready) throw new Error("Your saved progress is still loading."); persistProgress(daily ? completeSecurityDailyQuest(progress, paceId, lesson.id) : completeSecurityLesson(progress, lesson.id, paceId)); window.localStorage.setItem("codecraft-journey-v1", JSON.stringify({ ...loadJourneyPreferences(), trackId: "security", paceId, started: true, tutorialComplete: true })); };
  return <main className="app-shell track-python cloud-app backend-app frontend-app data-app security-app"><a className="cloud-skip" href="#security-content">Skip to learning content</a>
    <header className="topbar"><button className="brand" onClick={() => navigate("/tracks")} aria-label="Open CodeCraft tracks"><span className="brand-cube" aria-hidden="true"><i /></span><span>CODECRAFT</span></button><nav className="main-nav" aria-label="Main navigation"><button onClick={() => navigate("/tracks")}>Tracks</button><button className={!lessonId && !roadmap && !daily ? "active" : ""} onClick={() => navigate("/tracks/security")}>Security Paths</button><button className={roadmap ? "active" : ""} onClick={() => navigate("/roadmap/security/" + paceId)}>Roadmap</button><button className={Boolean(lessonId) && !daily ? "active" : ""} disabled={!ready} onClick={() => navigate(lessonPath(paceId, nextId))}>Quest</button><button className={daily ? "active daily-nav" : "daily-nav"} onClick={() => navigate("/daily-quest/security/" + (!lessonId && !roadmap ? recommendation : paceId))}>Daily Quest</button></nav><div className="player-stats"><button className="stat-chip profile-stat-trigger" onClick={() => navigate("/profile")} aria-label="Open profile"><b>◆</b> {ready ? progress.xp : 120} XP</button><span className="stat-chip badge-count"><b>✦</b> {totalBadges}</span><button className={"avatar " + avatarId} onClick={() => navigate("/profile")} aria-label={"Open profile, level " + level}>{avatarGlyph}<small>LV {level}</small></button>{isSignedIn ? <span className={"auth-account " + cloudState} role="status">{cloudState === "synced" ? "Cloud saved" : cloudState === "syncing" ? "Syncing…" : cloudState === "error" ? "Sync error" : "Signed in"}</span> : <SignInButton mode="modal"><button className={"auth-chip " + cloudState}>{isLoaded ? "Sign in to sync" : "Checking…"}</button></SignInButton>}</div></header>
    {effectiveId !== undefined ? <section className="lesson-page" id="security-content"><div className="lesson-bar"><button onClick={() => navigate("/roadmap/security/" + paceId)}>← Roadmap</button><div><span>{daily ? "DAILY QUEST · " + path.title.toUpperCase() : path.title.toUpperCase() + " · " + (world ? "WORLD " + world.id : "TRUST CITADEL")}</span><strong>{lesson?.title ?? "Lesson not found"}</strong></div><div className="lesson-progress" role="progressbar" aria-label={daily ? "Daily Quest completion" : path.title + " progress"} aria-valuemin={0} aria-valuemax={daily ? 1 : SECURITY_PATH_TOTAL} aria-valuenow={daily ? dailyCompleted ? 1 : 0 : completed.length}><i style={{ width: daily ? dailyCompleted ? "100%" : "50%" : completed.length / SECURITY_PATH_TOTAL * 100 + "%" }} /></div><span>{daily ? "UTC · +" + DAILY_QUEST_XP + " XP" : lesson ? lesson.id + "/" + SECURITY_PATH_TOTAL + " · " + securityLessonXp(lesson.id, paceId) + " XP" : "21 LESSONS"}</span></div>
      {!lesson ? <div className="cloud-gate"><h1>Lesson not found</h1><a href="/tracks/security">Explore Security paths →</a></div> : !ready ? <p className="view-loading" role="status">Loading your learning progress…</p> : !unlocked ? <section className="cloud-gate"><h1>This lesson is locked</h1><p>Complete lesson {nextId} and its static practice first.</p><a className="curriculum-next cloud-button" href={lessonPath(paceId, nextId)}>Continue lesson {nextId} →</a></section> : <>{daily && <section className={"daily-quest-brief " + (dailyCompleted ? "complete" : "")}><div className="daily-quest-emblem" aria-hidden="true">◇<span>DQ</span></div><div><p>TODAY&apos;S TRUST CITADEL CHALLENGE</p><h1>{lesson.title}</h1><span>Reason through the scenario, investigate evidence, and repair the static security contracts.</span><div><b>Cybersecurity Engineering</b><b>{path.label}</b><b>15–30 min</b></div></div><aside><small>REWARD</small><strong>+{DAILY_QUEST_XP} XP</strong><span>{progress.game.dailyQuestStreak} day streak</span><i>{dailyCompleted ? "REWARD CLAIMED" : "AVAILABLE TODAY"}</i></aside></section>}<CloudLab key={(daily ? "daily-" : "") + "security-" + paceId + "-" + lesson.id} trackKind="security" paceId={paceId} lesson={lesson} completed={daily ? dailyCompleted : completed.includes(lesson.id)} daily={daily} onComplete={saveCompletion} /></>}
    </section> : roadmap ? <Roadmap paceId={paceId} progress={progress} ready={ready} /> : <PacePicker progress={progress} ready={ready} recommendation={recommendation} onRecommend={setRecommendation} onSelect={selectPace} />}
  </main>;
}
